// Code generated by cli/verb/gen. DO NOT EDIT.
//
// The struct fields and the assignments that fill them both come from the
// declaration in table.go, so the two cannot disagree. Adding an option means
// adding a Flag with a Field -- never editing this file, and never a matching
// edit in two places.

package verb

import (
	"fmt"
	"strconv"
	"time"

	"github.com/on-keyday/agent-harness/runner/protocol"
)

// AgentAction is built by: agent inbox, agent purge, agent read, agent retained, agent retract, agent subscribe, agent subscriptions, agent topics, agent unsubscribe, agent wait.
type AgentAction struct {
	ActionMarker
	// server ConnectionID (env: HARNESS_SERVER_CID)
	ServerCID string
	// start from this seq (0 = whole ring)
	Since uint64
	// JSON Lines instead of text
	JSON bool
	// hook mode: ask for what has not been injected, and mark it injected in the same operation
	UserPromptSubmitHook bool
	// only messages replying to this seq
	InReplyTo uint64
	Sub       string
	// topic to wait on
	Topic string
	// max block duration
	Timeout time.Duration
	// this agent's own chat.<short-id> topic
	Self bool
	// drop one message by seq; omitted drops the topic's retained buffer
	Seq uint64
}

// AgentSendAction is built by: agent dispatch, agent send.
type AgentSendAction struct {
	ActionMarker
	// server ConnectionID (env: HARNESS_SERVER_CID)
	ServerCID string
	// agentboard topic
	Topic string
	// whether --data was typed, which its zero value cannot say
	DataSet bool
	// payload string, or "-" to read stdin
	Data string
	// route replies to THIS message to this topic instead of your own chat.<short-id>
	ReplyTo string
	// seq of the message being replied to; with it, --topic may be omitted
	InReplyTo uint64
	// keep this message on the board even after its recipient replies
	NoRetireOnReply bool
	// the message body is free-form; --data or stdin are the alternatives
	Positional string
	Kind       string
	// max wait for the whole call (publish ack + reply)
	Timeout time.Duration
}

// BoardAction is built by: board purge, board read, board retract, board subscribers, board topics.
type BoardAction struct {
	ActionMarker
	Sub string
	// only messages replying to this seq
	InReplyTo uint64
	// JSON Lines instead of text
	JSON  bool
	Topic string
	// the message to withdraw; required — there is no whole-topic retract
	Seq uint64
}

// CancelAction is built by: cancel.
type CancelAction struct {
	ActionMarker
	TaskID string
}

// CatalogAction is built by: caps, notify-watch, skill, version, watch, whoami.
type CatalogAction struct {
	ActionMarker
	// output the capability catalog as JSON
	JSON bool
	Sub  string
	// name every embedded skill with its description instead of printing one
	List bool
	Name string
}

// ConnsAction is built by: conns.
type ConnsAction struct {
	ActionMarker
	// output JSON lines instead of a table
	JSON bool
	// stream live connection events (conns.status)
	Follow bool
}

// ExecRunAction is built by: exec, exec kill, exec ls.
type ExecRunAction struct {
	ActionMarker
	// hand it to the RUNNER's shell as one line (sh -c / cmd /c by its platform)
	Shell bool
	// run under the task's sshd parent process
	SshdParent bool
	TaskID     string
	// everything after `--` is the argv verbatim; re-scanning it for flags is how a command whose own firs…
	Argv []string
	Sub  string
	// only execs against this task id
	TaskFilter string
	// one JSON object per exec
	JSON    bool
	ExecIDs []uint64
}

// FileDeleteAction is built by: file delete.
type FileDeleteAction struct {
	ActionMarker
	// target a directory tree instead of a single file (uses dir_delete)
	Recursive bool
	// with -r: delete non-empty directory contents recursively (RemoveAll). Ignored without -r
	Force   bool
	TaskID  string
	RelPath string
}

// FileEditAction is built by: file edit.
type FileEditAction struct {
	ActionMarker
	TaskID  string
	RelPath string
}

// FileLsAction is built by: file ls.
type FileLsAction struct {
	ActionMarker
	TaskID  string
	RelPath string
}

// FileMkdirAction is built by: file mkdir.
type FileMkdirAction struct {
	ActionMarker
	// create missing parent directories (mkdir -p); also makes an existing directory a success
	Parents bool
	TaskID  string
	RelPath string
}

// FileNewAction is built by: file new.
type FileNewAction struct {
	ActionMarker
	TaskID  string
	RelPath string
}

// FilePullAction is built by: file pull.
type FilePullAction struct {
	ActionMarker
	// transfer a directory tree
	Recursive bool
	// overwrite existing destination
	Force bool
	// first byte to pull (single-file pull only)
	Offset uint64
	// max bytes to pull; 0 = to end of file
	Length    uint64
	TaskID    string
	RemoteSrc string
	LocalDst  string
}

// FilePushAction is built by: file push.
type FilePushAction struct {
	ActionMarker
	// transfer a directory tree
	Recursive bool
	// overwrite existing destination
	Force bool
	// create missing parent directories of the destination (mkdir -p)
	Parents   bool
	TaskID    string
	LocalSrc  string
	RemoteDst string
}

// ForwardKillAction is built by: forward kill.
type ForwardKillAction struct {
	ActionMarker
	ForwardIDs []uint64
}

// ForwardLsAction is built by: forward ls.
type ForwardLsAction struct {
	ActionMarker
	// only forwards for this task id
	TaskFilter string
	// one JSON object per forward
	JSON bool
}

// ForwardOpenAction is built by: forward.
type ForwardOpenAction struct {
	ActionMarker
	// local forward [bind:]localport:remotehost:remoteport (repeatable)
	L []string
	// remote forward [bind:]runnerport:dialhost:dialport (repeatable)
	R []string
	// raw stdio forward host:port (mutually exclusive with -L / -R)
	W string
	// with -W --http-path: HTTP method
	HTTPMethod string
	// with -W: send this HTTP request path instead of splicing stdin
	HTTPPath string
	// with --http-path: request body (literal, @file, or - for stdin)
	HTTPBody string
	// with --http-path: "Name: value" (repeatable)
	HTTPHeaders []string
	TaskID      string
}

// ForwardTapAction is built by: forward tap.
type ForwardTapAction struct {
	ActionMarker
	// to-target, from-target or both
	Dir string
	// cut each record's payload to this many bytes (0 = whole payload)
	MaxRecordBytes uint32
	ForwardID      uint64
	// hex | text | raw | json
	Mode string
}

// GitAction is built by: git diff, git file, git log, git show, git status, git subrepos.
type GitAction struct {
	ActionMarker
	// maximum commits (0 = 100, capped at 1000)
	Max uint32
	// run the query inside this worktree-relative nested repo
	Subrepo string
	BaseRev string
	// the pathspec after `--`, which filters within a repository
	Path string
	Sub  string
	// diff the index instead of the working tree
	Staged bool
	// inline a submodule's own file-level changes (the output is then not an applyable patch)
	Submodule bool
	// maximum diff bytes (0 = 2MiB, capped at 8MiB)
	MaxBytes  uint32
	TargetRev string
	// set by the surface after Build, not by the parse
	TaskID string
}

// GridAction is built by: grid.
type GridAction struct {
	ActionMarker
	// the anchor whose working set to show: itself, its descendants, and the tasks its own scope names
	Anchor string
	IDs    []string
	// computed by gridMode from the whole line
	Mode GridScopeMode
}

// ListAction is built by: ls.
type ListAction struct {
	ActionMarker
	// emit a single JSON object {"runners":[...],"tasks":[...]} instead of the table
	JSON bool
	// order tasks by their creator link and draw the hierarchy
	Tree bool
	// list only the rows the task-list filter currently admits
	Filtered bool
}

// LogsAction is built by: logs.
type LogsAction struct {
	ActionMarker
	// after dumping history, keep streaming live chunks (no-op when the task is terminal)
	Follow bool
	TaskID string
}

// NotifyAction is built by: notify.
type NotifyAction struct {
	ActionMarker
	// short heading for the notification
	Title string
	// severity: info|warn|error
	Level string
	// the notification body is free-form
	Text string
}

// PruneAction is built by: prune.
type PruneAction struct {
	ActionMarker
	// forget terminal tasks older than this (ignored when TASK_IDs are passed)
	Before time.Duration
	// with TASK_IDs: also forget tasks the server still considers active (Queued/Running/Detached)
	Force   bool
	TaskIDs []string
}

// PruneLocalAction is built by: prune-local.
type PruneLocalAction struct {
	ActionMarker
	// repo to prune
	Repo string
	// remove worktrees older than this (ignored when TASK_IDs are passed)
	Before time.Duration
	// with TASK_IDs: remove even when the server still considers the task active
	Force   bool
	TaskIDs []string
}

// SSHGatewayAction is built by: ssh-gateway, ssh-gateway start, ssh-gateway status, ssh-gateway stop.
type SSHGatewayAction struct {
	ActionMarker
	// ssh listen host:port (no ssh auth on a loopback bind; --authorized-keys is required off loopback)
	Listen string
	// ssh host key path (default: alongside the workspace config; generated on first run)
	HostKeyPath string
	// OpenSSH authorized_keys file; optional on a loopback bind, required otherwise
	AuthorizedKeys string
	Sub            string
}

// SendAction is built by: session send.
type SendAction struct {
	ActionMarker
	// append a carriage return (Enter) after the text
	Enter bool
	// interpret backslash escapes (\n \r \t \e \xHH \\)
	Interp bool
	// suppress the one-line summary of what was sent (stderr)
	Quiet bool
	// ms to let the input drain to the runner before detaching
	FlushMs uint
	// before sending, set the PTY size to ROWSxCOLS (e.g. 40x150)
	Resize string
	// after sending, render the session's screen to stdout
	Snapshot bool
	// with --snapshot: fallback rows
	Rows uint
	// with --snapshot: fallback cols
	Cols uint
	// with --snapshot: ms to collect output before rendering
	SettleMs uint
	// with --snapshot: also print attribute spans
	Style bool
	// with --snapshot: also print colour spans
	Color bool
	// with --snapshot: emit the screen as one JSON object
	JSON bool
	// with --snapshot: re-emit the screen WITH its colours
	ANSI bool
	// with --snapshot: render only what the PTY produced, dropping the server's replay additions
	WithoutSynth bool
	// with --snapshot: judge the resulting state (working / blocked / idle / unknown)
	Detect bool
	// with --detect: which agent's rule set to judge by
	DetectAgent string
	TaskID      string
	// the literal text to type into the PTY
	Text string
}

// ServerDialRunnerAction is built by: server dial-runner.
type ServerDialRunnerAction struct {
	ActionMarker
	// relay through this registered runner CID (copy from `harness-cli ls`)
	Via       string
	RunnerCID string
}

// SessionAction is built by: session attach, session await-idle, session kill, session ls, session resize, session snapshot, session stream approve, session stream attach, session stream finish, session stream interrupt, session stream turn.
type SessionAction struct {
	ActionMarker
	// ms to let the line drain to the runner before detaching
	FlushMs uint
	TaskID  string
	// the user turn's text
	Text string
	Sub  string
	// attach in view-only mode
	View bool
	// quiescence threshold in ms (0 = server default)
	ThresholdMs uint
	// fire via the operator-notification egress
	Notify bool
	// fire via an agentboard publish to this topic
	Topic string
	// new PTY size as ROWSxCOLS (e.g. 40x150)
	Size string
	// ms to wait for the server to echo the new size back — that echo is the acknowledgement
	WaitMs uint
	// suppress the one-line result on stderr
	Quiet bool
	// fallback rows when the session reports no size
	Rows uint
	// fallback cols when the session reports no size
	Cols uint
	// ms to collect output before rendering
	SettleMs uint
	// also print attribute spans
	Style bool
	// also print fg/bg colour spans
	Color bool
	// render only what the PTY produced, dropping the server's replay additions
	WithoutSynth bool
	// write the verbatim replay bytes instead of the VT-rendered screen
	Raw bool
	// emit the screen as one JSON object
	JSON bool
	// re-emit the screen WITH its colours and attributes
	ANSI bool
	// also judge what STATE the screen shows (working / blocked / idle / unknown)
	Detect bool
	// with --detect: which agent's rule set
	DetectAgent string
	// run the tool as requested
	Allow bool
	// refuse it
	Deny bool
	// with --deny, the reason. It reaches the AGENT verbatim as a failed tool result
	Message string
	// whether --suggestion was typed, which its zero value cannot say
	SuggestionSet bool
	// accept the request's Nth suggestion (0-based) as well; a suggestion is a STANDING change (e.g. stop …
	Suggestion uint
	RequestID  string
}

// SessionExecAction is built by: session exec.
type SessionExecAction struct {
	ActionMarker
	// max wait for the command to finish before giving up (exit 124)
	Timeout time.Duration
	// emit {"exit":N,"output":"…","timed_out":bool,"duration_ms":N} as one JSON object
	JSON bool
	// print no output; only propagate the exit code
	ExitOnly bool
	// return the verbatim output bytes (escape sequences intact)
	Raw    bool
	TaskID string
	// the command line to run in the session's foreground shell
	Cmd string
}

// SetCapsAction is built by: caps set.
type SetCapsAction struct {
	ActionMarker
	// whether --caps was typed, which its zero value cannot say
	CapsPresent bool
	// new capability set (same syntax as --caps on submit); omitted = keep the task's current caps
	Caps *protocol.Capability
	// whether --scope was typed, which its zero value cannot say
	ScopePresent bool
	// new scope; omitted = keep the task's current scope
	Scope *protocol.TaskScope
	// narrow ONE capability below --scope (written with --scope; they are one half of the authority)
	Overrides []protocol.ScopeOverride
	// also clamp every descendant to the new authority — without this a revoked task can still act throu…
	Cascade bool
	// on a narrowing, leave the affected tasks' connections open
	KeepConns bool
	TaskID    string
}

// SetParentAction is built by: caps set-parent.
type SetParentAction struct {
	ActionMarker
	// new parent task id (32 hex); the target and its whole subtree move under it
	ParentID string
	// detach the task to the operator root
	None bool
	// invert the task with its CURRENT parent
	Swap   bool
	TaskID string
}

// SpawnAction is built by: interactive, session new, submit.
type SpawnAction struct {
	ActionMarker
	// repo identifier; must match a runner-registered RepoPath verbatim
	Repo string
	// task id (32 hex) to resume — the server reuses the id and worktree branch, so the agent's project …
	ResumeTaskID string
	// with --resume, also ask the runner to resume the agent's own conversation state
	ResumeConversation bool
	// whether --caps was typed, which its zero value cannot say
	CapsPresent bool
	// comma-separated capability names to grant (e.g. spawn,file_read / all / none)
	Caps *protocol.Capability
	// whether --scope was typed, which its zero value cannot say
	ScopePresent bool
	// which tasks those capabilities may target; default subtree (self + descendants)
	Scope *protocol.TaskScope
	// agent profile name (empty = runner default; not to be confused with --agent-arg)
	Agent string
	// narrow ONE capability (or a comma-separated list of them) to a tighter scope than --scope
	Overrides []protocol.ScopeOverride
	// extra CLI arg to forward to the agent (repeatable; appended after the runner-global --agent-args)
	ExtraArgs []string
	// pin to a specific runner by ConnectionID (the id= value from `ls`)
	Runner string
	// pin to a runner by hostname
	Host string
	// pin to a runner by IP address
	IP string
	// prompt text
	Task string
	Kind string
	// forward X11: inject DISPLAY/XAUTHORITY so GUI apps render on your local X server
	X11 bool
	// with --x11: the local display number (0..99, default 10)
	X11Display uint
	// start the session and exit immediately (don't attach the terminal)
	Detach bool
	// open an event-stream session (structured events, no PTY)
	Stream bool
	// initial PTY rows (0 = unset; needs --cols too)
	Rows uint
	// initial PTY columns (0 = unset; needs --rows too)
	Cols uint
}

// WorkspaceAction is built by: workspace apply, workspace detach, workspace ls, workspace rm, workspace save, workspace show.
type WorkspaceAction struct {
	ActionMarker
	// record only this task (32 hex); omitted = every task the registry reports a forward for
	TaskID string
	// no | continue | fresh — for a task block being written for the FIRST time
	Resume string
	// assigned | any — for a task block being written for the FIRST time
	Runner string
	// repo identifier to record in the workspace
	Repo string
	// write every live session without opening the picker
	All  bool
	Name string
	Sub  string
	// also stop what the workspace started
	Stop bool
}

// The builds the declaration implies, one per verb path, registered into
// generated.go's map at init. Registering rather than declaring is what lets
// the package compile when this file is absent -- which it must, because the
// generator imports it.
func init() {
	registerGenerated(map[string]func(Bound) (Action, error){
		"prune\x00cli": func(b Bound) (Action, error) {
			a := PruneAction{}
			a.Before = durationOf(b.Flags["before"])
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskIDs = b.Args[0:]
			}
			return a, nil
		},
		"prune\x00tui": func(b Bound) (Action, error) {
			a := PruneAction{}
			a.Before = durationOf(b.Flags["before"])
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskIDs = b.Args[0:]
			}
			return a, nil
		},
		"prune\x00webui": func(b Bound) (Action, error) {
			a := PruneAction{}
			a.Before = durationOf(b.Flags["before"])
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskIDs = b.Args[0:]
			}
			return a, nil
		},
		"file push\x00cli": func(b Bound) (Action, error) {
			a := FilePushAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.LocalSrc = b.Args[1]
			}
			if len(b.Args) > 2 {
				a.RemoteDst = b.Args[2]
			}
			return a, nil
		},
		"file push\x00tui": func(b Bound) (Action, error) {
			a := FilePushAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.LocalSrc = b.Args[1]
			}
			if len(b.Args) > 2 {
				a.RemoteDst = b.Args[2]
			}
			return a, nil
		},
		"file push\x00webui": func(b Bound) (Action, error) {
			a := FilePushAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RemoteDst = b.Args[1]
			}
			return a, nil
		},
		"file pull\x00cli": func(b Bound) (Action, error) {
			a := FilePullAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Offset = uint64Of(b.Flags["offset"])
			a.Length = uint64Of(b.Flags["length"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RemoteSrc = b.Args[1]
			}
			if len(b.Args) > 2 {
				a.LocalDst = b.Args[2]
			}
			return a, nil
		},
		"file pull\x00tui": func(b Bound) (Action, error) {
			a := FilePullAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Offset = uint64Of(b.Flags["offset"])
			a.Length = uint64Of(b.Flags["length"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RemoteSrc = b.Args[1]
			}
			if len(b.Args) > 2 {
				a.LocalDst = b.Args[2]
			}
			return a, nil
		},
		"file pull\x00webui": func(b Bound) (Action, error) {
			a := FilePullAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			a.Offset = uint64Of(b.Flags["offset"])
			a.Length = uint64Of(b.Flags["length"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RemoteSrc = b.Args[1]
			}
			return a, nil
		},
		"file ls\x00cli": func(b Bound) (Action, error) {
			a := FileLsAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file ls\x00tui": func(b Bound) (Action, error) {
			a := FileLsAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file ls\x00webui": func(b Bound) (Action, error) {
			a := FileLsAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file mkdir\x00cli": func(b Bound) (Action, error) {
			a := FileMkdirAction{}
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file mkdir\x00tui": func(b Bound) (Action, error) {
			a := FileMkdirAction{}
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file mkdir\x00webui": func(b Bound) (Action, error) {
			a := FileMkdirAction{}
			a.Parents = b.Bool("parents")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file delete\x00cli": func(b Bound) (Action, error) {
			a := FileDeleteAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file delete\x00tui": func(b Bound) (Action, error) {
			a := FileDeleteAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file delete\x00webui": func(b Bound) (Action, error) {
			a := FileDeleteAction{}
			a.Recursive = b.Bool("recursive")
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file edit\x00cli": func(b Bound) (Action, error) {
			a := FileEditAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file edit\x00tui": func(b Bound) (Action, error) {
			a := FileEditAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file edit\x00webui": func(b Bound) (Action, error) {
			a := FileEditAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file new\x00cli": func(b Bound) (Action, error) {
			a := FileNewAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file new\x00tui": func(b Bound) (Action, error) {
			a := FileNewAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"file new\x00webui": func(b Bound) (Action, error) {
			a := FileNewAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RelPath = b.Args[1]
			}
			return a, nil
		},
		"git log\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "log"
			a.Max = uint32(uintOf(b.Flags["max"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git log\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "log"
			a.Max = uint32(uintOf(b.Flags["max"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git log\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "log"
			a.Max = uint32(uintOf(b.Flags["max"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git diff\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "diff"
			a.Staged = b.Bool("staged")
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.TargetRev = b.Args[1]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git diff\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "diff"
			a.Staged = b.Bool("staged")
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.TargetRev = b.Args[1]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git diff\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "diff"
			a.Staged = b.Bool("staged")
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.TargetRev = b.Args[1]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git show\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "show"
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git show\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "show"
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git show\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "show"
			a.Submodule = b.Bool("submodule")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.BaseRev = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git status\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "status"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git status\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "status"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git status\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "status"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git subrepos\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "subrepos"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git subrepos\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "subrepos"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git subrepos\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "subrepos"
			a.Subrepo = b.Str("subrepo")
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git file\x00cli": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "file"
			a.Staged = b.Bool("staged")
			a.TargetRev = b.Str("rev")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.Path = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git file\x00tui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "file"
			a.Staged = b.Bool("staged")
			a.TargetRev = b.Str("rev")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.Path = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"git file\x00webui": func(b Bound) (Action, error) {
			a := GitAction{}
			a.Sub = "file"
			a.Staged = b.Bool("staged")
			a.TargetRev = b.Str("rev")
			a.MaxBytes = uint32(uintOf(b.Flags["max-bytes"]))
			a.Subrepo = b.Str("subrepo")
			if len(b.Args) > 0 {
				a.Path = b.Args[0]
			}
			if b.Pathspec != "" {
				a.Path = b.Pathspec
			}
			return a, nil
		},
		"exec\x00cli": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "run"
			a.Shell = b.Bool("shell")
			a.SshdParent = b.Bool("sshd-parent")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if b.Bool("shell") {
				a.Argv = []string{b.Trail}
			} else {
				a.Argv = b.TrailArgs
			}
			return a, nil
		},
		"exec\x00tui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "run"
			a.Shell = b.Bool("shell")
			a.SshdParent = b.Bool("sshd-parent")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if b.Bool("shell") {
				a.Argv = []string{b.Trail}
			} else {
				a.Argv = b.TrailArgs
			}
			return a, nil
		},
		"exec\x00webui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "run"
			a.Shell = b.Bool("shell")
			a.SshdParent = b.Bool("sshd-parent")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if b.Bool("shell") {
				a.Argv = []string{b.Trail}
			} else {
				a.Argv = b.TrailArgs
			}
			return a, nil
		},
		"exec ls\x00cli": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "ls"
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"exec ls\x00tui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "ls"
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"exec ls\x00webui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "ls"
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"exec kill\x00cli": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "kill"
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("exec kill: bad exec id %q", raw)
				}
				a.ExecIDs = append(a.ExecIDs, n)
			}
			return a, nil
		},
		"exec kill\x00tui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "kill"
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("exec kill: bad exec id %q", raw)
				}
				a.ExecIDs = append(a.ExecIDs, n)
			}
			return a, nil
		},
		"exec kill\x00webui": func(b Bound) (Action, error) {
			a := ExecRunAction{}
			a.Sub = "kill"
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("exec kill: bad exec id %q", raw)
				}
				a.ExecIDs = append(a.ExecIDs, n)
			}
			return a, nil
		},
		"forward\x00cli": func(b Bound) (Action, error) {
			a := ForwardOpenAction{}
			a.L = stringsOf(b.Custom["L"])
			a.R = stringsOf(b.Custom["R"])
			a.W = b.Str("W")
			a.HTTPMethod = b.Str("http-method")
			a.HTTPPath = b.Str("http-path")
			a.HTTPBody = b.Str("http-body")
			a.HTTPHeaders = stringsOf(b.Custom["http-header"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"forward ls\x00cli": func(b Bound) (Action, error) {
			a := ForwardLsAction{}
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"forward ls\x00tui": func(b Bound) (Action, error) {
			a := ForwardLsAction{}
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"forward ls\x00webui": func(b Bound) (Action, error) {
			a := ForwardLsAction{}
			a.TaskFilter = b.Str("task")
			a.JSON = b.Bool("json")
			return a, nil
		},
		"forward kill\x00cli": func(b Bound) (Action, error) {
			a := ForwardKillAction{}
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward kill: bad forward id %q", raw)
				}
				a.ForwardIDs = append(a.ForwardIDs, n)
			}
			return a, nil
		},
		"forward kill\x00tui": func(b Bound) (Action, error) {
			a := ForwardKillAction{}
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward kill: bad forward id %q", raw)
				}
				a.ForwardIDs = append(a.ForwardIDs, n)
			}
			return a, nil
		},
		"forward kill\x00webui": func(b Bound) (Action, error) {
			a := ForwardKillAction{}
			for _, raw := range b.Args[0:] {
				n, err := strconv.ParseUint(raw, 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward kill: bad forward id %q", raw)
				}
				a.ForwardIDs = append(a.ForwardIDs, n)
			}
			return a, nil
		},
		"forward tap\x00cli": func(b Bound) (Action, error) {
			a := ForwardTapAction{}
			a.Dir = b.Str("dir")
			a.MaxRecordBytes = uint32(uintOf(b.Flags["max-bytes"]))
			if len(b.Args) > 0 {
				n, err := strconv.ParseUint(b.Args[0], 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward tap: bad forward id %q", b.Args[0])
				}
				a.ForwardID = n
			}
			a.Mode = "hex"
			if b.Bool("text") {
				a.Mode = "text"
			}
			if b.Bool("raw") {
				a.Mode = "raw"
			}
			if b.Bool("json") {
				a.Mode = "json"
			}
			return a, nil
		},
		"forward tap\x00tui": func(b Bound) (Action, error) {
			a := ForwardTapAction{}
			a.Dir = b.Str("dir")
			a.MaxRecordBytes = uint32(uintOf(b.Flags["max-bytes"]))
			if len(b.Args) > 0 {
				n, err := strconv.ParseUint(b.Args[0], 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward tap: bad forward id %q", b.Args[0])
				}
				a.ForwardID = n
			}
			a.Mode = "hex"
			if b.Bool("text") {
				a.Mode = "text"
			}
			if b.Bool("raw") {
				a.Mode = "raw"
			}
			if b.Bool("json") {
				a.Mode = "json"
			}
			return a, nil
		},
		"forward tap\x00webui": func(b Bound) (Action, error) {
			a := ForwardTapAction{}
			a.Dir = b.Str("dir")
			a.MaxRecordBytes = uint32(uintOf(b.Flags["max-bytes"]))
			if len(b.Args) > 0 {
				n, err := strconv.ParseUint(b.Args[0], 10, 64)
				if err != nil {
					return nil, fmt.Errorf("forward tap: bad forward id %q", b.Args[0])
				}
				a.ForwardID = n
			}
			a.Mode = "hex"
			if b.Bool("text") {
				a.Mode = "text"
			}
			if b.Bool("raw") {
				a.Mode = "raw"
			}
			if b.Bool("json") {
				a.Mode = "json"
			}
			return a, nil
		},
		"server dial-runner\x00cli": func(b Bound) (Action, error) {
			a := ServerDialRunnerAction{}
			a.Via = b.Str("via")
			if len(b.Args) > 0 {
				a.RunnerCID = b.Args[0]
			}
			return a, nil
		},
		"server dial-runner\x00tui": func(b Bound) (Action, error) {
			a := ServerDialRunnerAction{}
			a.Via = b.Str("via")
			if len(b.Args) > 0 {
				a.RunnerCID = b.Args[0]
			}
			return a, nil
		},
		"server dial-runner\x00webui": func(b Bound) (Action, error) {
			a := ServerDialRunnerAction{}
			a.Via = b.Str("via")
			if len(b.Args) > 0 {
				a.RunnerCID = b.Args[0]
			}
			return a, nil
		},
		"ssh-gateway\x00cli": func(b Bound) (Action, error) {
			a := SSHGatewayAction{}
			a.Listen = b.Str("listen")
			a.HostKeyPath = b.Str("host-key")
			a.AuthorizedKeys = b.Str("authorized-keys")
			return a, nil
		},
		"ssh-gateway start\x00tui": func(b Bound) (Action, error) {
			a := SSHGatewayAction{}
			a.Sub = "start"
			if len(b.Args) > 0 {
				a.Listen = b.Args[0]
			}
			return a, nil
		},
		"ssh-gateway status\x00tui": func(b Bound) (Action, error) {
			a := SSHGatewayAction{}
			a.Sub = "status"
			return a, nil
		},
		"ssh-gateway stop\x00tui": func(b Bound) (Action, error) {
			a := SSHGatewayAction{}
			a.Sub = "stop"
			return a, nil
		},
		"workspace save\x00cli": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "save"
			a.TaskID = b.Str("task")
			a.Resume = b.Str("resume")
			a.Runner = b.Str("runner")
			a.Repo = b.Str("repo")
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace save\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "save"
			a.All = b.Bool("all")
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace rm\x00cli": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "rm"
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace rm\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "rm"
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace ls\x00cli": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "ls"
			return a, nil
		},
		"workspace ls\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "ls"
			return a, nil
		},
		"workspace show\x00cli": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "show"
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace show\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "show"
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace apply\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "apply"
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"workspace detach\x00tui": func(b Bound) (Action, error) {
			a := WorkspaceAction{}
			a.Sub = "detach"
			a.Stop = b.Bool("stop")
			return a, nil
		},
		"board topics\x00cli": func(b Bound) (Action, error) {
			a := BoardAction{}
			a.Sub = "topics"
			return a, nil
		},
		"board read\x00cli": func(b Bound) (Action, error) {
			a := BoardAction{}
			a.Sub = "read"
			a.InReplyTo = uint64Of(b.Flags["in-reply-to"])
			a.JSON = b.Bool("json")
			if len(b.Args) > 0 {
				a.Topic = b.Args[0]
			}
			return a, nil
		},
		"board subscribers\x00cli": func(b Bound) (Action, error) {
			a := BoardAction{}
			a.Sub = "subscribers"
			if len(b.Args) > 0 {
				a.Topic = b.Args[0]
			}
			return a, nil
		},
		"board retract\x00cli": func(b Bound) (Action, error) {
			a := BoardAction{}
			a.Sub = "retract"
			a.Seq = uint64Of(b.Flags["seq"])
			if len(b.Args) > 0 {
				a.Topic = b.Args[0]
			}
			return a, nil
		},
		"board purge\x00cli": func(b Bound) (Action, error) {
			a := BoardAction{}
			a.Sub = "purge"
			a.Seq = uint64Of(b.Flags["seq"])
			if len(b.Args) > 0 {
				a.Topic = b.Args[0]
			}
			return a, nil
		},
		"submit\x00cli": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "submit"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("submit: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.Task = b.Str("task")
			if a.Task == "" {
				a.Task = b.Trail
			}
			return a, nil
		},
		"submit\x00tui": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "submit"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("submit: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.Task = b.Str("task")
			if a.Task == "" {
				a.Task = b.Trail
			}
			return a, nil
		},
		"submit\x00webui": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "submit"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("submit: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("submit: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.Task = b.Str("task")
			if a.Task == "" {
				a.Task = b.Trail
			}
			return a, nil
		},
		"interactive\x00cli": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "interactive"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("interactive: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("interactive: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("interactive: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.X11 = b.Bool("x11")
			a.X11Display = uintOf(b.Flags["x11-display"])
			return a, nil
		},
		"interactive\x00tui": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "interactive"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("interactive: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("interactive: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("interactive: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.X11 = b.Bool("x11")
			a.X11Display = uintOf(b.Flags["x11-display"])
			return a, nil
		},
		"session new\x00cli": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "session-new"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("session new: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("session new: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("session new: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.X11 = b.Bool("x11")
			a.X11Display = uintOf(b.Flags["x11-display"])
			a.Detach = b.Bool("detach")
			a.Stream = b.Bool("stream")
			a.Rows = uintOf(b.Flags["rows"])
			a.Cols = uintOf(b.Flags["cols"])
			return a, nil
		},
		"session new\x00tui": func(b Bound) (Action, error) {
			a := SpawnAction{}
			a.Kind = "session-new"
			a.Repo = b.Str("repo")
			a.ResumeTaskID = b.Str("resume")
			a.ResumeConversation = b.Bool("resume-conversation")
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("session new: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"] || b.Set["scope-for"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("session new: --scope: %w", err)
				}
				a.Scope = v
			}
			a.Agent = b.Str("agent")
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("session new: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.ExtraArgs = stringsOf(b.Custom["agent-arg"])
			a.Runner = b.Str("runner")
			a.Host = b.Str("host")
			a.IP = b.Str("ip")
			a.X11 = b.Bool("x11")
			a.X11Display = uintOf(b.Flags["x11-display"])
			a.Detach = b.Bool("detach")
			a.Stream = b.Bool("stream")
			a.Rows = uintOf(b.Flags["rows"])
			a.Cols = uintOf(b.Flags["cols"])
			return a, nil
		},
		"session send\x00cli": func(b Bound) (Action, error) {
			a := SendAction{}
			a.Enter = b.Bool("enter")
			a.Interp = b.Bool("e")
			a.Quiet = b.Bool("quiet")
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			a.Resize = b.Str("resize")
			a.Snapshot = b.Bool("snapshot")
			a.Rows = uintOf(b.Flags["rows"])
			a.Cols = uintOf(b.Flags["cols"])
			a.SettleMs = uintOf(b.Flags["settle-ms"])
			a.Style = b.Bool("style")
			a.Color = b.Bool("color")
			a.JSON = b.Bool("json")
			a.ANSI = b.Bool("ansi")
			a.WithoutSynth = b.Bool("without-synth")
			a.Detect = b.Bool("detect")
			a.DetectAgent = b.Str("detect-agent")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			a.Text = b.Trail
			return a, nil
		},
		"session exec\x00cli": func(b Bound) (Action, error) {
			a := SessionExecAction{}
			a.Timeout = durationOf(b.Flags["timeout"])
			a.JSON = b.Bool("json")
			a.ExitOnly = b.Bool("exit-only")
			a.Raw = b.Bool("raw")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			a.Cmd = b.Trail
			return a, nil
		},
		"session stream turn\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-turn"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			a.Text = b.Trail
			return a, nil
		},
		"session stream turn\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-turn"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			a.Text = b.Trail
			return a, nil
		},
		"session stream turn\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-turn"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			a.Text = b.Trail
			return a, nil
		},
		"notify\x00cli": func(b Bound) (Action, error) {
			a := NotifyAction{}
			a.Title = b.Str("title")
			a.Level = b.Str("level")
			a.Text = b.Trail
			return a, nil
		},
		"notify\x00tui": func(b Bound) (Action, error) {
			a := NotifyAction{}
			a.Title = b.Str("title")
			a.Level = b.Str("level")
			a.Text = b.Trail
			return a, nil
		},
		"agent send\x00cli": func(b Bound) (Action, error) {
			a := AgentSendAction{}
			a.Kind = "send"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.DataSet = b.Set["data"]
			a.Data = b.Str("data")
			a.ReplyTo = b.Str("reply-to")
			a.InReplyTo = uint64Of(b.Flags["in-reply-to"])
			a.NoRetireOnReply = b.Bool("no-retire-on-reply")
			a.Positional = b.Trail
			return a, nil
		},
		"agent dispatch\x00cli": func(b Bound) (Action, error) {
			a := AgentSendAction{}
			a.Kind = "dispatch"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.DataSet = b.Set["data"]
			a.Data = b.Str("data")
			a.ReplyTo = b.Str("reply-to")
			a.Timeout = durationOf(b.Flags["timeout"])
			a.Positional = b.Trail
			return a, nil
		},
		"grid\x00tui": func(b Bound) (Action, error) {
			a := GridAction{}
			a.Anchor = b.Str("under")
			if len(b.Args) > 0 {
				a.IDs = b.Args[0:]
			}
			if v, err := gridMode(b); err != nil {
				return nil, err
			} else {
				a.Mode = v
			}
			return a, nil
		},
		"grid\x00webui": func(b Bound) (Action, error) {
			a := GridAction{}
			a.Anchor = b.Str("under")
			if len(b.Args) > 0 {
				a.IDs = b.Args[0:]
			}
			if v, err := gridMode(b); err != nil {
				return nil, err
			} else {
				a.Mode = v
			}
			return a, nil
		},
		"cancel\x00cli": func(b Bound) (Action, error) {
			a := CancelAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"cancel\x00tui": func(b Bound) (Action, error) {
			a := CancelAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"cancel\x00webui": func(b Bound) (Action, error) {
			a := CancelAction{}
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"ls\x00cli": func(b Bound) (Action, error) {
			a := ListAction{}
			a.JSON = b.Bool("json")
			a.Tree = b.Bool("tree")
			return a, nil
		},
		"ls\x00webui": func(b Bound) (Action, error) {
			a := ListAction{}
			a.JSON = b.Bool("json")
			a.Tree = b.Bool("tree")
			a.Filtered = b.Bool("filtered")
			return a, nil
		},
		"conns\x00cli": func(b Bound) (Action, error) {
			a := ConnsAction{}
			a.JSON = b.Bool("json")
			a.Follow = b.Bool("follow")
			return a, nil
		},
		"caps\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "caps"
			a.JSON = b.Bool("json")
			return a, nil
		},
		"whoami\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "whoami"
			a.JSON = b.Bool("json")
			return a, nil
		},
		"skill\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "skill"
			a.List = b.Bool("list")
			if len(b.Args) > 0 {
				a.Name = b.Args[0]
			}
			return a, nil
		},
		"watch\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "watch"
			return a, nil
		},
		"notify-watch\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "notify-watch"
			return a, nil
		},
		"version\x00cli": func(b Bound) (Action, error) {
			a := CatalogAction{}
			a.Sub = "version"
			a.JSON = b.Bool("json")
			return a, nil
		},
		"logs\x00cli": func(b Bound) (Action, error) {
			a := LogsAction{}
			a.Follow = b.Bool("follow")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"prune-local\x00cli": func(b Bound) (Action, error) {
			a := PruneLocalAction{}
			a.Repo = b.Str("repo")
			a.Before = durationOf(b.Flags["before"])
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskIDs = b.Args[0:]
			}
			return a, nil
		},
		"caps set\x00cli": func(b Bound) (Action, error) {
			a := SetCapsAction{}
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("caps set: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("caps set: --scope: %w", err)
				}
				a.Scope = v
			}
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("caps set: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.Cascade = b.Bool("cascade")
			a.KeepConns = b.Bool("keep-conns")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"caps set\x00tui": func(b Bound) (Action, error) {
			a := SetCapsAction{}
			a.CapsPresent = b.Set["caps"]
			if b.Set["caps"] {
				v, err := parseCapsFlag(b.Str("caps"))
				if err != nil {
					return nil, fmt.Errorf("caps set: --caps: %w", err)
				}
				a.Caps = v
			}
			a.ScopePresent = b.Set["scope"]
			if b.Set["scope"] {
				v, err := parseScopeFlag(b.Str("scope"))
				if err != nil {
					return nil, fmt.Errorf("caps set: --scope: %w", err)
				}
				a.Scope = v
			}
			if b.Set["scope-for"] {
				v, err := parseScopeForList(stringsOf(b.Custom["scope-for"]))
				if err != nil {
					return nil, fmt.Errorf("caps set: --scope-for: %w", err)
				}
				a.Overrides = v
			}
			a.Cascade = b.Bool("cascade")
			a.KeepConns = b.Bool("keep-conns")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"caps set-parent\x00cli": func(b Bound) (Action, error) {
			a := SetParentAction{}
			a.ParentID = b.Str("parent")
			a.None = b.Bool("none")
			a.Swap = b.Bool("swap")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"caps set-parent\x00tui": func(b Bound) (Action, error) {
			a := SetParentAction{}
			a.ParentID = b.Str("parent")
			a.None = b.Bool("none")
			a.Swap = b.Bool("swap")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"caps set-parent\x00webui": func(b Bound) (Action, error) {
			a := SetParentAction{}
			a.ParentID = b.Str("parent")
			a.None = b.Bool("none")
			a.Swap = b.Bool("swap")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session attach\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "attach"
			a.View = b.Bool("view")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session attach\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "attach"
			a.View = b.Bool("view")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session ls\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "ls"
			return a, nil
		},
		"session ls\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "ls"
			return a, nil
		},
		"session kill\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "kill"
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session kill\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "kill"
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session await-idle\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "await-idle"
			a.ThresholdMs = uintOf(b.Flags["threshold-ms"])
			a.Notify = b.Bool("notify")
			a.Topic = b.Str("topic")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session await-idle\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "await-idle"
			a.ThresholdMs = uintOf(b.Flags["threshold-ms"])
			a.Notify = b.Bool("notify")
			a.Topic = b.Str("topic")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session await-idle\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "await-idle"
			a.ThresholdMs = uintOf(b.Flags["threshold-ms"])
			a.Notify = b.Bool("notify")
			a.Topic = b.Str("topic")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session resize\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "resize"
			a.Size = b.Str("size")
			a.WaitMs = uintOf(b.Flags["wait-ms"])
			a.Quiet = b.Bool("quiet")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session snapshot\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "snapshot"
			a.Rows = uintOf(b.Flags["rows"])
			a.Cols = uintOf(b.Flags["cols"])
			a.SettleMs = uintOf(b.Flags["settle-ms"])
			a.Style = b.Bool("style")
			a.Color = b.Bool("color")
			a.WithoutSynth = b.Bool("without-synth")
			a.Raw = b.Bool("raw")
			a.JSON = b.Bool("json")
			a.ANSI = b.Bool("ansi")
			a.Detect = b.Bool("detect")
			a.DetectAgent = b.Str("detect-agent")
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream attach\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-attach"
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream attach\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-attach"
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream attach\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-attach"
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream interrupt\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-interrupt"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream interrupt\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-interrupt"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream interrupt\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-interrupt"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream finish\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-finish"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream finish\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-finish"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream finish\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-finish"
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			return a, nil
		},
		"session stream approve\x00cli": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-approve"
			a.Allow = b.Bool("allow")
			a.Deny = b.Bool("deny")
			a.Message = b.Str("message")
			a.SuggestionSet = b.Set["suggestion"]
			a.Suggestion = uintOf(b.Flags["suggestion"])
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RequestID = b.Args[1]
			}
			return a, nil
		},
		"session stream approve\x00tui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-approve"
			a.Allow = b.Bool("allow")
			a.Deny = b.Bool("deny")
			a.Message = b.Str("message")
			a.SuggestionSet = b.Set["suggestion"]
			a.Suggestion = uintOf(b.Flags["suggestion"])
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RequestID = b.Args[1]
			}
			return a, nil
		},
		"session stream approve\x00webui": func(b Bound) (Action, error) {
			a := SessionAction{}
			a.Sub = "stream-approve"
			a.Allow = b.Bool("allow")
			a.Deny = b.Bool("deny")
			a.Message = b.Str("message")
			a.SuggestionSet = b.Set["suggestion"]
			a.Suggestion = uintOf(b.Flags["suggestion"])
			a.FlushMs = uintOf(b.Flags["flush-ms"])
			if len(b.Args) > 0 {
				a.TaskID = b.Args[0]
			}
			if len(b.Args) > 1 {
				a.RequestID = b.Args[1]
			}
			return a, nil
		},
		"agent inbox\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "inbox"
			a.ServerCID = b.Str("server-cid")
			a.Since = uint64Of(b.Flags["since"])
			a.JSON = b.Bool("json")
			a.UserPromptSubmitHook = b.Bool("user-prompt-submit-hook")
			a.InReplyTo = uint64Of(b.Flags["in-reply-to"])
			return a, nil
		},
		"agent wait\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "wait"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.Since = uint64Of(b.Flags["since"])
			a.InReplyTo = uint64Of(b.Flags["in-reply-to"])
			a.Timeout = durationOf(b.Flags["timeout"])
			return a, nil
		},
		"agent subscribe\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "subscribe"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.Self = b.Bool("self")
			return a, nil
		},
		"agent unsubscribe\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "unsubscribe"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.Self = b.Bool("self")
			return a, nil
		},
		"agent topics\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "topics"
			a.ServerCID = b.Str("server-cid")
			return a, nil
		},
		"agent subscriptions\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "subscriptions"
			a.ServerCID = b.Str("server-cid")
			return a, nil
		},
		"agent retained\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "retained"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.Self = b.Bool("self")
			return a, nil
		},
		"agent purge\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "purge"
			a.ServerCID = b.Str("server-cid")
			a.Topic = b.Str("topic")
			a.Self = b.Bool("self")
			a.Seq = uint64Of(b.Flags["seq"])
			return a, nil
		},
		"agent read\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "read"
			a.ServerCID = b.Str("server-cid")
			if len(b.Args) > 0 {
				n, err := strconv.ParseUint(b.Args[0], 10, 64)
				if err != nil {
					return nil, fmt.Errorf("agent read: bad seq %q", b.Args[0])
				}
				a.Seq = n
			}
			return a, nil
		},
		"agent retract\x00cli": func(b Bound) (Action, error) {
			a := AgentAction{}
			a.Sub = "retract"
			a.ServerCID = b.Str("server-cid")
			if len(b.Args) > 0 {
				n, err := strconv.ParseUint(b.Args[0], 10, 64)
				if err != nil {
					return nil, fmt.Errorf("agent retract: bad seq %q", b.Args[0])
				}
				a.Seq = n
			}
			return a, nil
		},
	})
}
