// Code generated by cli/verb/gen. DO NOT EDIT.
//
// The struct fields and the assignments that fill them both come from the
// declaration in table.go, so the two cannot disagree. Adding an option means
// adding a Flag with a Field -- never editing this file, and never a matching
// edit in two places.

package verb

import "time"

// PruneAction is built by: prune.
type PruneAction struct {
	ActionMarker
	// forget terminal tasks older than this (ignored when TASK_IDs are passed)
	Before time.Duration
	// with TASK_IDs: also forget tasks the server still considers active (Queued/Running/Detached)
	Force   bool
	TaskIDs []string
}

// The builds the declaration implies, one per verb path, registered into
// generated.go's map at init. Registering rather than declaring is what lets
// the package compile when this file is absent -- which it must, because the
// generator imports it.
func init() {
	registerGenerated(map[string]func(Bound) (Action, error){
		"prune": func(b Bound) (Action, error) {
			a := PruneAction{}
			a.Before = durationOf(b.Flags["before"])
			a.Force = b.Bool("force")
			if len(b.Args) > 0 {
				a.TaskIDs = b.Args[0:]
			}
			return a, nil
		},
	})
}
