package tui

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/charmbracelet/bubbles/textinput"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/on-keyday/agent-harness/cli"
)

// FilePickerListingMsg carries the result of a ListFiles call back to
// the picker. Generated by DoListFilesFor.
type FilePickerListingMsg struct {
	TaskID  string
	RelDir  string
	Entries []cli.FileEntryView
	Err     error
}

type pickerInputMode int

const (
	pickerNone pickerInputMode = iota
	pickerAskPushSrc
	pickerAskPullDst
	pickerAskNewDirName
	pickerConfirmDelete
	pickerConfirmPullOverwrite
	pickerConfirmPushOverwrite
)

// FilePickerModel is the file-picker popup state. The picker takes
// over keyboard handling while open. It browses a task's worktree
// (via cli.Client.ListFiles), supports descending / ascending
// directories, and can trigger push / pull / delete actions through
// short-form keyboard shortcuts plus textinput subpopups for the
// local path side of push / pull. Delete is single-step for files
// (`d`) and a y/n confirm for recursive directory delete (`D`).
type FilePickerModel struct {
	open      bool
	client    *cli.Client
	taskID    string
	taskShort string
	curDir    string // "" = worktree root; otherwise like "subdir/nested"
	entries   []cli.FileEntryView
	cursor    int

	inputMode        pickerInputMode
	input            textinput.Model
	deleteTarget     string
	deleteRecursive  bool
	deleteForce      bool
	deleteIsLocal    bool            // true when the pending confirm is for a local fs delete
	deleteReturnMode pickerInputMode // inputMode to restore after confirm (so local-delete from inside push/pull subpopup returns to that subpopup)

	// Pending pull args queued behind a pickerConfirmPullOverwrite
	// prompt. Populated by commitInputPath when the local destination
	// already exists; consumed by the confirm handler on y.
	pendingPullSrc       string
	pendingPullDst       string
	pendingPullRecursive bool

	// Pending push args queued behind a pickerConfirmPushOverwrite
	// prompt. Populated when the first send with force=false comes
	// back as AlreadyExists from the runner; consumed by the confirm
	// handler on y for the force=true retry.
	pendingPushLocal     string
	pendingPushRemote    string
	pendingPushRecursive bool

	// Local file browser state, active when inputMode is
	// pickerAskPushSrc / pickerAskPullDst AND localBrowseActive is on.
	// Tab in the typing input toggles into this mode; Tab here toggles
	// back. Esc cancels the whole input flow.
	localBrowseActive bool
	localCurDir       string
	localEntries      []localEntry
	localCursor       int
	localErr          string

	msg         string // ephemeral status line (loading / hint / cancel)
	opResult    string // sticky push/pull/delete result line; stays visible across listing refreshes until the next op
	opResultErr bool   // true when opResult should render in ErrorStyle, false for OKStyle
	width       int
	height      int
}

// localEntry is the local-fs equivalent of cli.FileEntryView used by
// the picker's local browser. Kept independent so the local mode does
// not pretend to be a wire-side listing.
type localEntry struct {
	Name  string
	IsDir bool
	Size  int64
}

// NewFilePicker constructs an idle picker.
func NewFilePicker() FilePickerModel {
	ti := textinput.New()
	ti.Prompt = "> "
	ti.CharLimit = 4096
	return FilePickerModel{input: ti}
}

// IsOpen reports whether the picker is currently active.
func (m *FilePickerModel) IsOpen() bool { return m.open }

// SetSize records the host viewport size used to clamp the popup box width.
func (m *FilePickerModel) SetSize(w, h int) { m.width, m.height = w, h }

// OpenFor begins a picker session for taskID. Returns a Cmd that
// loads the worktree root listing — App should run it.
func (m *FilePickerModel) OpenFor(c *cli.Client, taskID string) tea.Cmd {
	m.open = true
	m.client = c
	m.taskID = taskID
	m.taskShort = shortTaskID(taskID)
	m.curDir = ""
	m.entries = nil
	m.cursor = 0
	m.inputMode = pickerNone
	m.msg = "loading..."
	return DoListFilesFor(c, taskID, "")
}

// Close tears the picker down and clears state.
func (m *FilePickerModel) Close() {
	m.open = false
	m.client = nil
	m.taskID = ""
	m.taskShort = ""
	m.curDir = ""
	m.entries = nil
	m.cursor = 0
	m.input.Reset()
	m.input.Blur()
	m.inputMode = pickerNone
	m.deleteTarget = ""
	m.deleteRecursive = false
	m.deleteForce = false
	m.deleteIsLocal = false
	m.deleteReturnMode = pickerNone
	m.pendingPullSrc = ""
	m.pendingPullDst = ""
	m.pendingPullRecursive = false
	m.pendingPushLocal = ""
	m.pendingPushRemote = ""
	m.pendingPushRecursive = false
	m.localBrowseActive = false
	m.localCurDir = ""
	m.localEntries = nil
	m.localCursor = 0
	m.localErr = ""
	m.msg = ""
	m.opResult = ""
	m.opResultErr = false
}

// DoListFilesFor is the tea.Cmd that fetches a worktree directory
// listing for the picker. Result lands as a FilePickerListingMsg.
func DoListFilesFor(c *cli.Client, taskID, relPath string) tea.Cmd {
	return func() tea.Msg {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		entries, err := c.ListFiles(ctx, taskID, relPath)
		return FilePickerListingMsg{TaskID: taskID, RelDir: relPath, Entries: entries, Err: err}
	}
}

// Update advances the picker on any message. The picker only consumes
// messages relevant to itself; the caller may pass everything in. When
// the picker is closed, Update is a no-op.
func (m FilePickerModel) Update(msg tea.Msg) (FilePickerModel, tea.Cmd) {
	if !m.open {
		return m, nil
	}
	switch x := msg.(type) {
	case FilePickerListingMsg:
		if x.TaskID != m.taskID || x.RelDir != m.curDir {
			return m, nil // stale: user navigated away before response
		}
		if x.Err != nil {
			m.msg = "ls error: " + x.Err.Error()
			m.entries = nil
			m.cursor = 0
			return m, nil
		}
		m.entries = sortedFileEntries(x.Entries)
		if m.cursor >= len(m.entries) {
			m.cursor = 0
		}
		// Clear only transient "loading..." style placeholders. Sticky
		// op results (opResult) live in their own field and are
		// preserved across listing refreshes so the user still sees
		// the push/pull/delete outcome after the auto-refresh runs.
		if strings.HasPrefix(m.msg, "loading") || strings.HasPrefix(m.msg, "refreshing") {
			m.msg = ""
		}
		return m, nil
	case FileResultMsg:
		// Surface the action's result in the header and refresh the
		// listing. We don't filter on TaskID since the picker is only
		// open for one task at a time; messages for other taskIDs
		// won't be generated while the picker is up.
		if x.Err != nil {
			// AlreadyExists on push (force=false first try) means we
			// should ask the user before retrying with force=true.
			// Recognise it here and switch into the confirm mode
			// instead of just rendering the raw error string as a
			// terminal failure.
			if x.Op == "push" && cli.IsAlreadyExists(x.Err) && m.pendingPushLocal != "" {
				m.inputMode = pickerConfirmPushOverwrite
				m.opResult = "push: destination exists, awaiting overwrite confirm"
				m.opResultErr = false
				return m, nil
			}
			m.opResult = fmt.Sprintf("%s error: %s", x.Op, x.Err.Error())
			m.opResultErr = true
		} else {
			m.opResult = fmt.Sprintf("%s ok: %s", x.Op, x.Detail)
			m.opResultErr = false
			// Successful push: clear pending args so a stale retry
			// can't fire from a later, unrelated FileResultMsg.
			if x.Op == "push" {
				m.pendingPushLocal = ""
				m.pendingPushRemote = ""
				m.pendingPushRecursive = false
			}
		}
		if m.client != nil && m.taskID != "" {
			return m, DoListFilesFor(m.client, m.taskID, m.curDir)
		}
		return m, nil
	case tea.KeyMsg:
		return m.handleKey(x)
	}
	return m, nil
}

func (m FilePickerModel) handleKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch m.inputMode {
	case pickerAskPushSrc, pickerAskPullDst:
		return m.handleInputKey(k)
	case pickerAskNewDirName:
		return m.handleNewDirKey(k)
	case pickerConfirmDelete:
		return m.handleConfirmKey(k)
	case pickerConfirmPullOverwrite:
		return m.handlePullOverwriteKey(k)
	case pickerConfirmPushOverwrite:
		return m.handlePushOverwriteKey(k)
	default:
		return m.handleBrowseKey(k)
	}
}

func (m FilePickerModel) handleBrowseKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "esc":
		m.Close()
		return m, nil
	case "up", "k":
		if m.cursor > 0 {
			m.cursor--
		}
		return m, nil
	case "down", "j":
		if m.cursor < len(m.entries)-1 {
			m.cursor++
		}
		return m, nil
	case "enter", "right", "l":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if !e.IsDir {
			// Enter / → on a regular file is an inert select in the
			// remote browser — actions (u push, g pull, d delete) are
			// explicit keys. This keeps navigation key presses from
			// silently triggering file ops on misclick.
			return m, nil
		}
		newDir := joinRel(m.curDir, e.Name)
		m.curDir = newDir
		m.entries = nil
		m.cursor = 0
		m.msg = "loading..."
		return m, DoListFilesFor(m.client, m.taskID, newDir)
	case "backspace", "left", "h":
		if m.curDir == "" {
			return m, nil
		}
		newDir := parentRel(m.curDir)
		m.curDir = newDir
		m.entries = nil
		m.cursor = 0
		m.msg = "loading..."
		return m, DoListFilesFor(m.client, m.taskID, newDir)
	case "r":
		m.msg = "refreshing..."
		return m, DoListFilesFor(m.client, m.taskID, m.curDir)
	case "u":
		// Push: prompt for local source path. The destination is derived
		// when the user commits the input (curDir, or curDir/<selectedDir>
		// when the cursor is on a directory).
		m.inputMode = pickerAskPushSrc
		m.input.Reset()
		m.input.Placeholder = "local source path (file or directory)"
		m.input.Focus()
		return m, nil
	case "g":
		// Pull: require a selected entry as source. Recursive is
		// auto-derived from the entry's IsDir at commit time.
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			m.msg = "select an entry to pull"
			return m, nil
		}
		m.inputMode = pickerAskPullDst
		m.input.Reset()
		m.input.Placeholder = "local destination path"
		m.input.Focus()
		return m, nil
	case "d":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if e.IsDir {
			m.msg = "use D for directory delete (-r -f)"
			return m, nil
		}
		m.deleteTarget = e.Name
		m.deleteRecursive = false
		m.deleteForce = false
		m.deleteIsLocal = false
		m.deleteReturnMode = pickerNone
		m.inputMode = pickerConfirmDelete
		return m, nil
	case "D":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if !e.IsDir {
			m.msg = "use d for file delete"
			return m, nil
		}
		m.deleteTarget = e.Name
		m.deleteRecursive = true
		m.deleteForce = true
		m.deleteIsLocal = false
		m.deleteReturnMode = pickerNone
		m.inputMode = pickerConfirmDelete
		return m, nil
	case "+":
		// New folder: prompt for a directory name, created under the
		// current directory with mkdir -p semantics — the typed name
		// may be nested (a/b/c) and the result shows up in the
		// listing right after the auto-refresh.
		m.inputMode = pickerAskNewDirName
		m.input.Reset()
		m.input.Placeholder = "new directory name (nested ok, e.g. a/b/c)"
		m.input.Focus()
		return m, nil
	}
	return m, nil
}

// handleNewDirKey drives the pickerAskNewDirName prompt: Enter commits
// a FileMkdir (parents=true) under curDir, Esc cancels, anything else
// edits the input. Unlike handleInputKey there is no Tab/local-browser
// integration — the input is a remote-relative name, not a local path.
func (m FilePickerModel) handleNewDirKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.Type {
	case tea.KeyEsc:
		m.inputMode = pickerNone
		m.input.Blur()
		return m, nil
	case tea.KeyEnter:
		name := strings.TrimSpace(m.input.Value())
		if name == "" {
			return m, nil
		}
		rel := joinRel(m.curDir, name)
		m.inputMode = pickerNone
		m.input.Blur()
		m.msg = "creating " + rel + "..."
		return m, DoFileMkdir(m.client, m.taskID, rel, true)
	}
	var cmd tea.Cmd
	m.input, cmd = m.input.Update(k)
	return m, cmd
}

func (m FilePickerModel) handleInputKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	// Tab toggles between the typing prompt and the local file browser.
	// When returning to typing, if the local cursor is on a regular
	// file, the full path is pre-filled in the input so the user can
	// review and Enter to commit — this is the deliberate
	// confirmation step that replaces the old auto-commit-on-Enter
	// behavior. When the cursor is on a directory (or nothing is
	// selected), the typed text is left untouched.
	if k.Type == tea.KeyTab {
		if m.localBrowseActive {
			m.localBrowseActive = false
			filled := false
			if m.localCursor >= 0 && m.localCursor < len(m.localEntries) {
				if e := m.localEntries[m.localCursor]; !e.IsDir {
					full := joinLocal(m.localCurDir, e.Name)
					m.input.SetValue(full)
					m.input.SetCursor(len(full))
					m.msg = "pre-filled: " + full + " — Enter to commit, edit first if needed"
					filled = true
				}
			}
			if !filled {
				m.msg = "typing (no pre-fill — local cursor was on a dir or empty)"
			}
			m.input.Focus()
			return m, nil
		}
		m.localBrowseActive = true
		m.input.Blur()
		if m.localCurDir == "" {
			if cwd, err := os.Getwd(); err == nil {
				m.localCurDir = cwd
			} else {
				m.localCurDir = "."
			}
		}
		entries, lerr := readLocalDirEntries(m.localCurDir)
		m.localEntries = entries
		m.localCursor = 0
		if lerr != nil {
			m.localErr = lerr.Error()
		} else {
			m.localErr = ""
		}
		m.msg = "" // clear any stale pre-fill notice when entering browser
		return m, nil
	}
	if m.localBrowseActive {
		return m.handleLocalBrowseKey(k)
	}

	if k.Type == tea.KeyEsc {
		m.inputMode = pickerNone
		m.input.Reset()
		m.input.Blur()
		return m, nil
	}
	if k.Type == tea.KeyEnter {
		path := strings.TrimSpace(m.input.Value())
		if path == "" {
			m.inputMode = pickerNone
			m.input.Blur()
			return m, nil
		}
		return m.commitInputPath(path)
	}
	var cmd tea.Cmd
	m.input, cmd = m.input.Update(k)
	return m, cmd
}

// commitInputPath fires the push or pull with the supplied local path.
// Used by both the typing-input Enter handler and the local-browser
// Enter-on-file handler so the two converge on the same dispatch logic.
func (m FilePickerModel) commitInputPath(path string) (FilePickerModel, tea.Cmd) {
	switch m.inputMode {
	case pickerAskPushSrc:
		destDir := m.curDir
		if m.cursor >= 0 && m.cursor < len(m.entries) {
			if e := m.entries[m.cursor]; e.IsDir {
				destDir = joinRel(m.curDir, e.Name)
			}
		}
		base := localBase(path)
		dest := joinRel(destDir, base)
		recursive := isLocalDir(path)
		m.inputMode = pickerNone
		m.localBrowseActive = false
		m.input.Blur()
		// Save pending args so the picker can retry with force=true
		// behind a confirm prompt if the runner refuses with
		// AlreadyExists. First send uses force=false; the runner-side
		// O_EXCL guarantees we never silently overwrite without the
		// user's explicit yes.
		m.pendingPushLocal = path
		m.pendingPushRemote = dest
		m.pendingPushRecursive = recursive
		return m, DoFilePush(m.client, m.taskID, path, dest, recursive, false, false)
	case pickerAskPullDst:
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			m.inputMode = pickerNone
			m.localBrowseActive = false
			m.input.Blur()
			return m, nil
		}
		e := m.entries[m.cursor]
		src := joinRel(m.curDir, e.Name)
		recursive := e.IsDir
		m.input.Blur()
		// If the local destination already exists, queue the pull
		// behind an overwrite-confirm prompt instead of clobbering
		// silently. The picker passes force=true on the wire (so the
		// runner side overwrites) — that's only safe AFTER the user
		// has explicitly said yes.
		if _, statErr := os.Lstat(path); statErr == nil {
			m.pendingPullSrc = src
			m.pendingPullDst = path
			m.pendingPullRecursive = recursive
			m.inputMode = pickerConfirmPullOverwrite
			return m, nil
		}
		m.inputMode = pickerNone
		m.localBrowseActive = false
		return m, DoFilePull(m.client, m.taskID, src, path, recursive, true)
	}
	return m, nil
}

// handleLocalBrowseKey handles keys while the local file browser is
// active inside the push/pull input subpopup.
func (m FilePickerModel) handleLocalBrowseKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "esc":
		// Exit the input flow entirely.
		m.inputMode = pickerNone
		m.localBrowseActive = false
		m.input.Reset()
		m.input.Blur()
		return m, nil
	case "up", "k":
		if m.localCursor > 0 {
			m.localCursor--
		}
		return m, nil
	case "down", "j":
		if m.localCursor < len(m.localEntries)-1 {
			m.localCursor++
		}
		return m, nil
	case "enter", "right", "l":
		if m.localCursor < 0 || m.localCursor >= len(m.localEntries) {
			return m, nil
		}
		e := m.localEntries[m.localCursor]
		full := joinLocal(m.localCurDir, e.Name)
		if e.IsDir {
			m.localCurDir = full
			entries, lerr := readLocalDirEntries(full)
			m.localEntries = entries
			m.localCursor = 0
			if lerr != nil {
				m.localErr = lerr.Error()
			} else {
				m.localErr = ""
			}
			return m, nil
		}
		// Enter / → on a regular file is an inert select. To commit
		// the file as the local side of push / pull, the user presses
		// Tab back to the typing prompt (which pre-fills the input
		// with the selected file's path), reviews, and then presses
		// Enter in typing mode. This separation prevents misclick on
		// navigation keys from kicking off a transfer.
		return m, nil
	case "backspace", "left", "h":
		parent := localParent(m.localCurDir)
		if parent == m.localCurDir {
			return m, nil
		}
		m.localCurDir = parent
		entries, lerr := readLocalDirEntries(parent)
		m.localEntries = entries
		m.localCursor = 0
		if lerr != nil {
			m.localErr = lerr.Error()
		} else {
			m.localErr = ""
		}
		return m, nil
	case "r":
		entries, lerr := readLocalDirEntries(m.localCurDir)
		m.localEntries = entries
		if lerr != nil {
			m.localErr = lerr.Error()
		} else {
			m.localErr = ""
		}
		return m, nil
	case ".":
		// '.' commits the action with the current dir as the local
		// path. Useful for pull-into-this-dir without descending into
		// a specific file.
		return m.commitInputPath(m.localCurDir)
	case "d":
		if m.localCursor < 0 || m.localCursor >= len(m.localEntries) {
			return m, nil
		}
		e := m.localEntries[m.localCursor]
		if e.IsDir {
			m.localErr = "use D for directory delete"
			return m, nil
		}
		m.deleteTarget = joinLocal(m.localCurDir, e.Name)
		m.deleteRecursive = false
		m.deleteForce = false
		m.deleteIsLocal = true
		m.deleteReturnMode = m.inputMode // restore push/pull subpopup after confirm
		m.inputMode = pickerConfirmDelete
		return m, nil
	case "D":
		if m.localCursor < 0 || m.localCursor >= len(m.localEntries) {
			return m, nil
		}
		e := m.localEntries[m.localCursor]
		if !e.IsDir {
			m.localErr = "use d for file delete"
			return m, nil
		}
		m.deleteTarget = joinLocal(m.localCurDir, e.Name)
		m.deleteRecursive = true
		m.deleteForce = true
		m.deleteIsLocal = true
		m.deleteReturnMode = m.inputMode
		m.inputMode = pickerConfirmDelete
		return m, nil
	}
	return m, nil
}

func (m FilePickerModel) handleConfirmKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "y", "Y":
		target := m.deleteTarget
		rec := m.deleteRecursive
		force := m.deleteForce
		isLocal := m.deleteIsLocal
		returnMode := m.deleteReturnMode
		// Reset the pending-delete fields up front so the state is
		// clean whether we dispatch a Cmd (remote) or run synchronously
		// (local) below.
		m.deleteTarget = ""
		m.deleteRecursive = false
		m.deleteForce = false
		m.deleteIsLocal = false
		m.deleteReturnMode = pickerNone

		if isLocal {
			var err error
			if rec {
				err = os.RemoveAll(target)
			} else {
				err = os.Remove(target)
			}
			if err != nil {
				m.opResult = "local delete error: " + err.Error()
				m.opResultErr = true
			} else {
				m.opResult = "local delete ok: " + target
				m.opResultErr = false
				// Refresh the local listing in place so the picker
				// reflects the change without an explicit reload key.
				entries, lerr := readLocalDirEntries(m.localCurDir)
				m.localEntries = entries
				if m.localCursor >= len(entries) && len(entries) > 0 {
					m.localCursor = len(entries) - 1
				}
				if lerr != nil {
					m.localErr = lerr.Error()
				}
			}
			m.inputMode = returnMode
			return m, nil
		}
		// Remote delete dispatch.
		m.inputMode = returnMode
		return m, DoFileDelete(m.client, m.taskID, joinRel(m.curDir, target), rec, force)

	case "n", "N", "esc":
		returnMode := m.deleteReturnMode
		m.deleteTarget = ""
		m.deleteRecursive = false
		m.deleteForce = false
		m.deleteIsLocal = false
		m.deleteReturnMode = pickerNone
		m.inputMode = returnMode
		m.msg = "delete cancelled"
		return m, nil
	}
	return m, nil
}

// handlePushOverwriteKey handles the y/n prompt for "the remote push
// destination already exists — overwrite?". Triggered when the first
// push send (with force=false) comes back as AlreadyExists from the
// runner. On y, the pending push args are retried with force=true;
// on n they are cleared and the picker returns to browse mode.
func (m FilePickerModel) handlePushOverwriteKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "y", "Y":
		local := m.pendingPushLocal
		remote := m.pendingPushRemote
		rec := m.pendingPushRecursive
		m.pendingPushLocal = ""
		m.pendingPushRemote = ""
		m.pendingPushRecursive = false
		m.inputMode = pickerNone
		return m, DoFilePush(m.client, m.taskID, local, remote, rec, true, false)
	case "n", "N", "esc":
		m.pendingPushLocal = ""
		m.pendingPushRemote = ""
		m.pendingPushRecursive = false
		m.inputMode = pickerNone
		m.msg = "push cancelled"
		return m, nil
	}
	return m, nil
}

// handlePullOverwriteKey handles the y/n prompt for "the local pull
// destination already exists — overwrite?". On y the pending pull is
// dispatched with force=true; on n the pending fields are cleared and
// the user lands back in browse mode without any wire activity.
func (m FilePickerModel) handlePullOverwriteKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "y", "Y":
		src := m.pendingPullSrc
		dst := m.pendingPullDst
		rec := m.pendingPullRecursive
		m.pendingPullSrc = ""
		m.pendingPullDst = ""
		m.pendingPullRecursive = false
		m.inputMode = pickerNone
		m.localBrowseActive = false
		return m, DoFilePull(m.client, m.taskID, src, dst, rec, true)
	case "n", "N", "esc":
		m.pendingPullSrc = ""
		m.pendingPullDst = ""
		m.pendingPullRecursive = false
		m.inputMode = pickerNone
		m.localBrowseActive = false
		m.msg = "pull cancelled"
		return m, nil
	}
	return m, nil
}

// View renders the picker box. Caller composes it into the screen via
// lipgloss.Place (matching the existing PopupModel pattern).
//
// The box height is clamped to the terminal height (minus a margin
// for borders / outer placement) so the popup never overflows beyond
// the visible area. Entry lists scroll internally to keep the cursor
// in view. When the local file browser subpopup is active, the
// remote entry list is hidden to free vertical space for the local
// browser.
func (m FilePickerModel) View() string {
	if !m.open {
		return ""
	}
	// Box budget: terminal rows minus a small margin for the outer
	// border + lipgloss.Place padding. innerH is the number of lines
	// available for content INSIDE the box (after subtracting the
	// border rows lipgloss draws around the Render).
	const boxBorderRows = 2 // top and bottom border
	const outerMargin = 2   // breathing room from Place's edges
	innerH := m.height - boxBorderRows - outerMargin
	if innerH < 8 {
		innerH = 8
	}

	// Compose header (always shown).
	var header strings.Builder
	fmt.Fprintf(&header, "File picker · task %s · /%s\n", m.taskShort, m.curDir)
	if !m.localBrowseActive {
		header.WriteString("↑↓ nav · → / Enter descend · ← / Backspace back · u push · g pull · d delete · D rm -rf · + new dir · r reload · Esc close\n")
	} else {
		header.WriteString("Tab → typing (pre-fills selected file) · ↑↓ → / Enter descend · ← / Backspace back · . use this dir · d/D delete · r reload · Esc cancel\n")
	}
	if m.opResult != "" {
		if m.opResultErr {
			header.WriteString(ErrorStyle.Render(m.opResult) + "\n")
		} else {
			header.WriteString(OKStyle.Render(m.opResult) + "\n")
		}
	}
	if m.msg != "" {
		header.WriteString(m.msg + "\n")
	}
	header.WriteString(strings.Repeat("─", 60) + "\n")
	headerLines := lineCount(header.String())

	// Compose footer / subpopup (varies by inputMode).
	var footer strings.Builder
	switch m.inputMode {
	case pickerAskPushSrc, pickerAskPullDst:
		var label string
		if m.inputMode == pickerAskPushSrc {
			label = "push source (local)"
		} else {
			label = "pull destination (local)"
		}
		if m.localBrowseActive {
			fmt.Fprintf(&footer, "\n[%s] local browser · %s\n", label, m.localCurDir)
			// Status line: tell the user up-front what Tab will do
			// from the current cursor position. Files pre-fill the
			// typing prompt with their full path; directories don't
			// (you'd descend into them with Enter / →).
			footer.WriteString("Tab→ ")
			if m.localCursor >= 0 && m.localCursor < len(m.localEntries) {
				e := m.localEntries[m.localCursor]
				if e.IsDir {
					footer.WriteString("typing (no pre-fill — cursor is on a directory)\n")
				} else {
					full := joinLocal(m.localCurDir, e.Name)
					fmt.Fprintf(&footer, "typing (will pre-fill: %s)\n", full)
				}
			} else {
				footer.WriteString("typing (no pre-fill — empty selection)\n")
			}
			if m.localErr != "" {
				footer.WriteString("err: " + m.localErr + "\n")
			}
		} else {
			fmt.Fprintf(&footer, "\n%s: %s\n(Tab: browse local fs · Esc: cancel)\n", label, m.input.View())
		}
	case pickerAskNewDirName:
		dir := m.curDir
		if dir == "" {
			dir = "."
		}
		fmt.Fprintf(&footer, "\nnew directory under %s: %s\n(Enter: create (mkdir -p) · Esc: cancel)\n",
			dir, m.input.View())
	case pickerConfirmDelete:
		mode := "rm"
		if m.deleteRecursive {
			mode = "rm -rf"
		}
		scope := "remote"
		if m.deleteIsLocal {
			scope = "local"
		}
		fmt.Fprintf(&footer, "\n%s (%s) %s  ? (y/n)\n", mode, scope, m.deleteTarget)
	case pickerConfirmPullOverwrite:
		fmt.Fprintf(&footer, "\nlocal file %s already exists. overwrite? (y/n)\n", m.pendingPullDst)
	case pickerConfirmPushOverwrite:
		fmt.Fprintf(&footer, "\nremote destination %s already exists. overwrite? (y/n)\n", m.pendingPushRemote)
	}
	footerLines := lineCount(footer.String())

	// Remaining rows for entries.
	entryCapacity := innerH - headerLines - footerLines
	if entryCapacity < 3 {
		entryCapacity = 3
	}

	// Render entries — either remote (default) or local (when local
	// browser is active). We don't show both at once; the local
	// browser intentionally takes the whole entry area so the user
	// has maximum vertical room while picking.
	var entries strings.Builder
	if m.localBrowseActive {
		renderEntryList(&entries, len(m.localEntries), m.localCursor, entryCapacity,
			func(i int) (name string, size uint64, isDir bool) {
				e := m.localEntries[i]
				return e.Name, uint64(e.Size), e.IsDir
			})
	} else {
		renderEntryList(&entries, len(m.entries), m.cursor, entryCapacity,
			func(i int) (name string, size uint64, isDir bool) {
				e := m.entries[i]
				return e.Name, e.Size, e.IsDir
			})
	}

	// Pad entries area to fill the remaining rows so the footer sticks
	// to the bottom of the clamped box rather than floating just below
	// the entries when the list is short.
	body := entries.String()
	bodyLines := lineCount(body)
	if pad := entryCapacity - bodyLines; pad > 0 {
		body += strings.Repeat("\n", pad)
	}

	w := m.width - 4
	if w < 40 {
		w = 40
	}
	box := lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).
		Padding(0, 1).
		Width(w).
		Height(innerH)
	return box.Render(header.String() + body + footer.String())
}

// renderEntryList renders up to capacity lines of entries into b,
// scrolling so cursor is visible. The accessor returns the per-entry
// fields without forcing the caller to use a single concrete type.
func renderEntryList(b *strings.Builder, total, cursor, capacity int, accessor func(i int) (name string, size uint64, isDir bool)) {
	if total == 0 {
		b.WriteString("(empty)\n")
		return
	}
	if capacity < 1 {
		capacity = 1
	}
	start := 0
	if total > capacity {
		// Center the cursor in the visible window when possible.
		start = cursor - capacity/2
		if start < 0 {
			start = 0
		}
		if start+capacity > total {
			start = total - capacity
		}
	}
	end := start + capacity
	if end > total {
		end = total
	}
	if start > 0 {
		fmt.Fprintf(b, "  ... %d more above\n", start)
	}
	for i := start; i < end; i++ {
		name, size, isDir := accessor(i)
		prefix := "  "
		if i == cursor {
			prefix = "> "
		}
		if isDir {
			name += "/"
		}
		sz := strings.Repeat(" ", 10)
		if !isDir {
			sz = fmt.Sprintf("%10d", size)
		}
		fmt.Fprintf(b, "%s%s %s\n", prefix, sz, name)
	}
	if end < total {
		fmt.Fprintf(b, "  ... %d more below\n", total-end)
	}
}

// lineCount returns the number of newline-terminated rows a string
// occupies in the rendered output. Trailing strings without a final
// newline count as one extra row.
func lineCount(s string) int {
	if s == "" {
		return 0
	}
	n := strings.Count(s, "\n")
	if !strings.HasSuffix(s, "\n") {
		n++
	}
	return n
}

// --- helpers ---

func sortedFileEntries(es []cli.FileEntryView) []cli.FileEntryView {
	out := make([]cli.FileEntryView, len(es))
	copy(out, es)
	sort.Slice(out, func(i, j int) bool {
		// Directories first, files after, alphabetic within each group.
		if out[i].IsDir != out[j].IsDir {
			return out[i].IsDir
		}
		return out[i].Name < out[j].Name
	})
	return out
}

// joinRel concatenates two worktree-relative path components. POSIX
// slash form on the wire (the runner / server treat the path as a
// POSIX string regardless of host OS).
func joinRel(a, b string) string {
	a = strings.Trim(a, "/")
	b = strings.Trim(b, "/")
	if a == "" {
		return b
	}
	if b == "" {
		return a
	}
	return a + "/" + b
}

// parentRel returns the parent of a worktree-relative path. parentRel("a/b") = "a",
// parentRel("a") = "", parentRel("") = "".
func parentRel(p string) string {
	p = strings.Trim(p, "/")
	idx := strings.LastIndex(p, "/")
	if idx < 0 {
		return ""
	}
	return p[:idx]
}

// localBase returns the basename of a local path, cross-OS (handles
// both `/` and `\` separators). Trailing separators are stripped first.
func localBase(p string) string {
	p = strings.TrimRight(p, "/\\")
	if i := strings.LastIndexAny(p, "/\\"); i >= 0 {
		return p[i+1:]
	}
	return p
}

// isLocalDir reports whether the local path exists and is a directory.
// Used to default to dir_push semantics when the user hands a directory
// to the push input. Returns false for non-existent paths and files.
func isLocalDir(p string) bool {
	fi, err := os.Stat(p)
	if err != nil {
		return false
	}
	return fi.IsDir()
}

// readLocalDirEntries lists the local filesystem directory at dir and
// returns the entries sorted dirs-first / alphabetic within group. Size
// is best-effort (0 when Stat fails — typically because of permission
// or a broken symlink); the picker tolerates this rather than refusing
// to display the directory.
func readLocalDirEntries(dir string) ([]localEntry, error) {
	es, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	out := make([]localEntry, 0, len(es))
	for _, e := range es {
		entry := localEntry{Name: e.Name(), IsDir: e.IsDir()}
		if fi, err := e.Info(); err == nil {
			entry.Size = fi.Size()
		}
		out = append(out, entry)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].IsDir != out[j].IsDir {
			return out[i].IsDir
		}
		return out[i].Name < out[j].Name
	})
	return out, nil
}

// joinLocal joins two local-fs path components using filepath.Join so
// cross-OS separators are handled correctly.
func joinLocal(a, b string) string {
	return filepath.Join(a, b)
}

// localParent returns the parent directory of a local path. At the
// filesystem root (or for "."), returns the input unchanged so the
// picker treats a no-op Backspace at the root as inert.
func localParent(p string) string {
	parent := filepath.Dir(p)
	if parent == p {
		return p
	}
	return parent
}
