package tui

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/charmbracelet/bubbles/textinput"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/on-keyday/agent-harness/cli"
)

// FilePickerListingMsg carries the result of a ListFiles call back to
// the picker. Generated by DoListFilesFor.
type FilePickerListingMsg struct {
	TaskID  string
	RelDir  string
	Entries []cli.FileEntryView
	Err     error
}

type pickerInputMode int

const (
	pickerNone pickerInputMode = iota
	pickerAskPushSrc
	pickerAskPullDst
	pickerConfirmDelete
)

// FilePickerModel is the file-picker popup state. The picker takes
// over keyboard handling while open. It browses a task's worktree
// (via cli.Client.ListFiles), supports descending / ascending
// directories, and can trigger push / pull / delete actions through
// short-form keyboard shortcuts plus textinput subpopups for the
// local path side of push / pull. Delete is single-step for files
// (`d`) and a y/n confirm for recursive directory delete (`D`).
type FilePickerModel struct {
	open      bool
	client    *cli.Client
	taskID    string
	taskShort string
	curDir    string // "" = worktree root; otherwise like "subdir/nested"
	entries   []cli.FileEntryView
	cursor    int

	inputMode       pickerInputMode
	input           textinput.Model
	deleteTarget    string
	deleteRecursive bool
	deleteForce     bool

	msg    string // ephemeral status / error line in the header
	width  int
	height int
}

// NewFilePicker constructs an idle picker.
func NewFilePicker() FilePickerModel {
	ti := textinput.New()
	ti.Prompt = "> "
	ti.CharLimit = 4096
	return FilePickerModel{input: ti}
}

// IsOpen reports whether the picker is currently active.
func (m *FilePickerModel) IsOpen() bool { return m.open }

// SetSize records the host viewport size used to clamp the popup box width.
func (m *FilePickerModel) SetSize(w, h int) { m.width, m.height = w, h }

// OpenFor begins a picker session for taskID. Returns a Cmd that
// loads the worktree root listing — App should run it.
func (m *FilePickerModel) OpenFor(c *cli.Client, taskID string) tea.Cmd {
	m.open = true
	m.client = c
	m.taskID = taskID
	m.taskShort = shortTaskID(taskID)
	m.curDir = ""
	m.entries = nil
	m.cursor = 0
	m.inputMode = pickerNone
	m.msg = "loading..."
	return DoListFilesFor(c, taskID, "")
}

// Close tears the picker down and clears state.
func (m *FilePickerModel) Close() {
	m.open = false
	m.client = nil
	m.taskID = ""
	m.taskShort = ""
	m.curDir = ""
	m.entries = nil
	m.cursor = 0
	m.input.Reset()
	m.input.Blur()
	m.inputMode = pickerNone
	m.deleteTarget = ""
	m.deleteRecursive = false
	m.deleteForce = false
	m.msg = ""
}

// DoListFilesFor is the tea.Cmd that fetches a worktree directory
// listing for the picker. Result lands as a FilePickerListingMsg.
func DoListFilesFor(c *cli.Client, taskID, relPath string) tea.Cmd {
	return func() tea.Msg {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		entries, err := c.ListFiles(ctx, taskID, relPath)
		return FilePickerListingMsg{TaskID: taskID, RelDir: relPath, Entries: entries, Err: err}
	}
}

// Update advances the picker on any message. The picker only consumes
// messages relevant to itself; the caller may pass everything in. When
// the picker is closed, Update is a no-op.
func (m FilePickerModel) Update(msg tea.Msg) (FilePickerModel, tea.Cmd) {
	if !m.open {
		return m, nil
	}
	switch x := msg.(type) {
	case FilePickerListingMsg:
		if x.TaskID != m.taskID || x.RelDir != m.curDir {
			return m, nil // stale: user navigated away before response
		}
		if x.Err != nil {
			m.msg = "ls error: " + x.Err.Error()
			m.entries = nil
			m.cursor = 0
			return m, nil
		}
		m.entries = sortedFileEntries(x.Entries)
		if m.cursor >= len(m.entries) {
			m.cursor = 0
		}
		m.msg = ""
		return m, nil
	case FileResultMsg:
		// Surface the action's result in the header and refresh the
		// listing. We don't filter on TaskID since the picker is only
		// open for one task at a time; messages for other taskIDs
		// won't be generated while the picker is up.
		if x.Err != nil {
			m.msg = fmt.Sprintf("%s error: %s", x.Op, x.Err.Error())
		} else {
			m.msg = fmt.Sprintf("%s ok: %s", x.Op, x.Detail)
		}
		if m.client != nil && m.taskID != "" {
			return m, DoListFilesFor(m.client, m.taskID, m.curDir)
		}
		return m, nil
	case tea.KeyMsg:
		return m.handleKey(x)
	}
	return m, nil
}

func (m FilePickerModel) handleKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch m.inputMode {
	case pickerAskPushSrc, pickerAskPullDst:
		return m.handleInputKey(k)
	case pickerConfirmDelete:
		return m.handleConfirmKey(k)
	default:
		return m.handleBrowseKey(k)
	}
}

func (m FilePickerModel) handleBrowseKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "esc":
		m.Close()
		return m, nil
	case "up", "k":
		if m.cursor > 0 {
			m.cursor--
		}
		return m, nil
	case "down", "j":
		if m.cursor < len(m.entries)-1 {
			m.cursor++
		}
		return m, nil
	case "enter", "right", "l":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if !e.IsDir {
			return m, nil
		}
		newDir := joinRel(m.curDir, e.Name)
		m.curDir = newDir
		m.entries = nil
		m.cursor = 0
		m.msg = "loading..."
		return m, DoListFilesFor(m.client, m.taskID, newDir)
	case "backspace", "left", "h":
		if m.curDir == "" {
			return m, nil
		}
		newDir := parentRel(m.curDir)
		m.curDir = newDir
		m.entries = nil
		m.cursor = 0
		m.msg = "loading..."
		return m, DoListFilesFor(m.client, m.taskID, newDir)
	case "r":
		m.msg = "refreshing..."
		return m, DoListFilesFor(m.client, m.taskID, m.curDir)
	case "u":
		// Push: prompt for local source path. The destination is derived
		// when the user commits the input (curDir, or curDir/<selectedDir>
		// when the cursor is on a directory).
		m.inputMode = pickerAskPushSrc
		m.input.Reset()
		m.input.Placeholder = "local source path (file or directory)"
		m.input.Focus()
		return m, nil
	case "g":
		// Pull: require a selected entry as source. Recursive is
		// auto-derived from the entry's IsDir at commit time.
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			m.msg = "select an entry to pull"
			return m, nil
		}
		m.inputMode = pickerAskPullDst
		m.input.Reset()
		m.input.Placeholder = "local destination path"
		m.input.Focus()
		return m, nil
	case "d":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if e.IsDir {
			m.msg = "use D for directory delete (-r -f)"
			return m, nil
		}
		m.deleteTarget = e.Name
		m.deleteRecursive = false
		m.deleteForce = false
		m.inputMode = pickerConfirmDelete
		return m, nil
	case "D":
		if m.cursor < 0 || m.cursor >= len(m.entries) {
			return m, nil
		}
		e := m.entries[m.cursor]
		if !e.IsDir {
			m.msg = "use d for file delete"
			return m, nil
		}
		m.deleteTarget = e.Name
		m.deleteRecursive = true
		m.deleteForce = true
		m.inputMode = pickerConfirmDelete
		return m, nil
	}
	return m, nil
}

func (m FilePickerModel) handleInputKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	if k.Type == tea.KeyEsc {
		m.inputMode = pickerNone
		m.input.Reset()
		m.input.Blur()
		return m, nil
	}
	if k.Type == tea.KeyEnter {
		path := strings.TrimSpace(m.input.Value())
		if path == "" {
			m.inputMode = pickerNone
			m.input.Blur()
			return m, nil
		}
		switch m.inputMode {
		case pickerAskPushSrc:
			destDir := m.curDir
			if m.cursor >= 0 && m.cursor < len(m.entries) {
				if e := m.entries[m.cursor]; e.IsDir {
					destDir = joinRel(m.curDir, e.Name)
				}
			}
			base := localBase(path)
			dest := joinRel(destDir, base)
			recursive := isLocalDir(path)
			m.inputMode = pickerNone
			m.input.Blur()
			return m, DoFilePush(m.client, m.taskID, path, dest, recursive, true)
		case pickerAskPullDst:
			if m.cursor < 0 || m.cursor >= len(m.entries) {
				m.inputMode = pickerNone
				m.input.Blur()
				return m, nil
			}
			e := m.entries[m.cursor]
			src := joinRel(m.curDir, e.Name)
			recursive := e.IsDir
			m.inputMode = pickerNone
			m.input.Blur()
			return m, DoFilePull(m.client, m.taskID, src, path, recursive, true)
		}
	}
	var cmd tea.Cmd
	m.input, cmd = m.input.Update(k)
	return m, cmd
}

func (m FilePickerModel) handleConfirmKey(k tea.KeyMsg) (FilePickerModel, tea.Cmd) {
	switch k.String() {
	case "y", "Y":
		target := joinRel(m.curDir, m.deleteTarget)
		rec := m.deleteRecursive
		force := m.deleteForce
		m.inputMode = pickerNone
		m.deleteTarget = ""
		m.deleteRecursive = false
		m.deleteForce = false
		return m, DoFileDelete(m.client, m.taskID, target, rec, force)
	case "n", "N", "esc":
		m.inputMode = pickerNone
		m.deleteTarget = ""
		m.deleteRecursive = false
		m.deleteForce = false
		m.msg = "delete cancelled"
		return m, nil
	}
	return m, nil
}

// View renders the picker box. Caller composes it into the screen via
// lipgloss.Place (matching the existing PopupModel pattern).
func (m FilePickerModel) View() string {
	if !m.open {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "File picker · task %s · /%s\n", m.taskShort, m.curDir)
	b.WriteString("↑↓ nav · → enter · ← back · u push · g pull · d delete · D rm -rf · r reload · Esc close\n")
	if m.msg != "" {
		b.WriteString(m.msg + "\n")
	}
	b.WriteString(strings.Repeat("─", 60) + "\n")

	if len(m.entries) == 0 {
		b.WriteString("(empty)\n")
	} else {
		for i, e := range m.entries {
			prefix := "  "
			if i == m.cursor {
				prefix = "> "
			}
			name := e.Name
			if e.IsDir {
				name += "/"
			}
			sz := strings.Repeat(" ", 10)
			if !e.IsDir {
				sz = fmt.Sprintf("%10d", e.Size)
			}
			fmt.Fprintf(&b, "%s%s %s\n", prefix, sz, name)
		}
	}

	switch m.inputMode {
	case pickerAskPushSrc:
		fmt.Fprintf(&b, "\npush source (local): %s\n(Esc to cancel)\n", m.input.View())
	case pickerAskPullDst:
		fmt.Fprintf(&b, "\npull destination (local): %s\n(Esc to cancel)\n", m.input.View())
	case pickerConfirmDelete:
		mode := "rm"
		if m.deleteRecursive {
			mode = "rm -rf"
		}
		fmt.Fprintf(&b, "\n%s %s  ? (y/n)\n", mode, m.deleteTarget)
	}

	w := m.width - 4
	if w < 40 {
		w = 40
	}
	if w > 100 {
		w = 100
	}
	box := lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).
		Padding(0, 1).
		Width(w)
	return box.Render(b.String())
}

// --- helpers ---

func sortedFileEntries(es []cli.FileEntryView) []cli.FileEntryView {
	out := make([]cli.FileEntryView, len(es))
	copy(out, es)
	sort.Slice(out, func(i, j int) bool {
		// Directories first, files after, alphabetic within each group.
		if out[i].IsDir != out[j].IsDir {
			return out[i].IsDir
		}
		return out[i].Name < out[j].Name
	})
	return out
}

// joinRel concatenates two worktree-relative path components. POSIX
// slash form on the wire (the runner / server treat the path as a
// POSIX string regardless of host OS).
func joinRel(a, b string) string {
	a = strings.Trim(a, "/")
	b = strings.Trim(b, "/")
	if a == "" {
		return b
	}
	if b == "" {
		return a
	}
	return a + "/" + b
}

// parentRel returns the parent of a worktree-relative path. parentRel("a/b") = "a",
// parentRel("a") = "", parentRel("") = "".
func parentRel(p string) string {
	p = strings.Trim(p, "/")
	idx := strings.LastIndex(p, "/")
	if idx < 0 {
		return ""
	}
	return p[:idx]
}

// localBase returns the basename of a local path, cross-OS (handles
// both `/` and `\` separators). Trailing separators are stripped first.
func localBase(p string) string {
	p = strings.TrimRight(p, "/\\")
	if i := strings.LastIndexAny(p, "/\\"); i >= 0 {
		return p[i+1:]
	}
	return p
}

// isLocalDir reports whether the local path exists and is a directory.
// Used to default to dir_push semantics when the user hands a directory
// to the push input. Returns false for non-existent paths and files.
func isLocalDir(p string) bool {
	fi, err := os.Stat(p)
	if err != nil {
		return false
	}
	return fi.IsDir()
}
