// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package protocol

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("protocol")*/
type MessageKind uint8

const (
	MessageKind_JOIN  MessageKind = 0
	MessageKind_LEAVE MessageKind = 1
)

func (e MessageKind) String() string {
	switch e {
	case MessageKind_JOIN:
		return "JOIN"
	case MessageKind_LEAVE:
		return "LEAVE"
	default:
		return fmt.Sprintf("MessageKind(%d)", e)
	}
}

type tmp99 struct {
	NickNameLen uint8
	NickName    []uint8
}

type Variant73 struct {
	tmp99 tmp99
}

type PubSubRequest struct {
	Kind      MessageKind
	RequestId uint32
	tmp96     Variant73
	Topic     []uint8
}

func (p *PubSubRequest) NickName() *[]uint8 {
	if p.Kind == MessageKind_JOIN {
		return &p.tmp96.tmp99.NickName
	}
	return nil
}
func (p *PubSubRequest) SetNickName(tmp167 []uint8) bool {
	if p.Kind == MessageKind_JOIN {
		if len(tmp167) > int(255) {
			return false
		}
		p.tmp96.tmp99.NickNameLen = uint8(len(tmp167))
		p.tmp96.tmp99.NickName = tmp167
		return true
	}
	return false
}

func (p *PubSubRequest) NickNameLen() *uint8 {
	if p.Kind == MessageKind_JOIN {
		return &p.tmp96.tmp99.NickNameLen
	}
	return nil
}
func (p *PubSubRequest) SetNickNameLen(tmp146 uint8) bool {
	if p.Kind == MessageKind_JOIN {
		p.tmp96.tmp99.NickNameLen = tmp146
		return true
	}
	return false
}

func (p *PubSubRequest) Write(tmp9 io.Writer) error {
	tmp9ByteIO, _ := tmp9.(io.ByteWriter)
	_ = tmp9ByteIO
	/* config.go.union("noheap")*/
	if tmp9ByteIO != nil {
		if err := tmp9ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp9.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	tmp88 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp88[:], uint32(p.RequestId))
	if _, err := tmp9.Write(tmp88[:4]); err != nil {
		return err
	}
	if p.Kind == MessageKind_JOIN {
		if tmp9ByteIO != nil {
			if err := tmp9ByteIO.WriteByte(p.tmp96.tmp99.NickNameLen); err != nil {
				return err
			}
		} else {
			if _, err := tmp9.Write([]byte{p.tmp96.tmp99.NickNameLen}); err != nil {
				return err
			}
		}
		if len(p.tmp96.tmp99.NickName) != int(p.tmp96.tmp99.NickNameLen) {
			return fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp96::NickName\": expected %d, got %d", int(p.tmp96.tmp99.NickNameLen), len(p.tmp96.tmp99.NickName))
		}
		if _, err := tmp9.Write(p.tmp96.tmp99.NickName); err != nil {
			return err
		}
	}
	if _, err := tmp9.Write(p.Topic); err != nil {
		return err
	}
	return nil
}
func (s *PubSubRequest) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubRequest) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) EncodeSlice(tmp9 []byte, tmp9Offset *int) error {
	/* config.go.union("noheap")*/
	tmp61 := []uint8{}
	if len(tmp9)-*tmp9Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubRequest::Kind\"")
	}
	tmp61 = tmp9[*tmp9Offset : *tmp9Offset+int(1)]
	tmp61[0] = uint8(p.Kind)
	*tmp9Offset += int(1)
	tmp88 := []uint8{}
	if len(tmp9)-*tmp9Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"PubSubRequest::RequestId\"")
	}
	tmp88 = tmp9[*tmp9Offset : *tmp9Offset+int(4)]
	binary.BigEndian.PutUint32(tmp88[:], uint32(p.RequestId))
	*tmp9Offset += int(4)
	if p.Kind == MessageKind_JOIN {
		tmp129 := []uint8{}
		if len(tmp9)-*tmp9Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"PubSubRequest::tmp96::NickNameLen\"")
		}
		tmp129 = tmp9[*tmp9Offset : *tmp9Offset+int(1)]
		tmp129[0] = p.tmp96.tmp99.NickNameLen
		*tmp9Offset += int(1)
		if len(p.tmp96.tmp99.NickName) != int(p.tmp96.tmp99.NickNameLen) {
			return fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp96::NickName\": expected %d, got %d", int(p.tmp96.tmp99.NickNameLen), len(p.tmp96.tmp99.NickName))
		}
		if len(tmp9)-*tmp9Offset < int(0+p.tmp96.tmp99.NickNameLen) {
			return errors.New("not enough space to write for field \"PubSubRequest::tmp96::NickName\"")
		}
		copy(tmp9[*tmp9Offset:*tmp9Offset+int(p.tmp96.tmp99.NickNameLen)], p.tmp96.tmp99.NickName)
		*tmp9Offset += int(p.tmp96.tmp99.NickNameLen)
	}
	if len(tmp9)-*tmp9Offset < int(0+len(p.Topic)) {
		return errors.New("not enough space to write for field \"PubSubRequest::Topic\"")
	}
	copy(tmp9[*tmp9Offset:*tmp9Offset+int(len(p.Topic))], p.Topic)
	*tmp9Offset += int(len(p.Topic))
	return nil
}
func (s *PubSubRequest) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubRequest) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) Append(tmp9 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp61 := [1]uint8{}
	tmp61[0] = uint8(p.Kind)
	tmp9 = append(tmp9, tmp61[:1]...)
	tmp88 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp88[:], uint32(p.RequestId))
	tmp9 = append(tmp9, tmp88[:4]...)
	if p.Kind == MessageKind_JOIN {
		tmp129 := [1]uint8{}
		tmp129[0] = p.tmp96.tmp99.NickNameLen
		tmp9 = append(tmp9, tmp129[:1]...)
		if len(p.tmp96.tmp99.NickName) != int(p.tmp96.tmp99.NickNameLen) {
			return nil, fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp96::NickName\": expected %d, got %d", int(p.tmp96.tmp99.NickNameLen), len(p.tmp96.tmp99.NickName))
		}
		tmp9 = append(tmp9, p.tmp96.tmp99.NickName...)
	}
	tmp9 = append(tmp9, p.Topic...)
	return tmp9, nil
}
func (s *PubSubRequest) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubRequest) Read(tmp8 io.Reader) error {
	tmp8ByteIO, _ := tmp8.(io.ByteReader)
	_ = tmp8ByteIO
	/* config.go.union("noheap")*/
	tmp97 := uint8(0)
	if tmp8ByteIO != nil {
		var err error
		tmp97, err = tmp8ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp8, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PubSubRequest::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp97 = buf[0]
	}
	p.Kind = MessageKind(tmp97)
	tmp94 := [4]uint8{}
	if _, err := io.ReadFull(tmp8, tmp94[0:0+4]); err != nil {
		return err
	}
	p.RequestId = binary.BigEndian.Uint32(tmp94[:])
	if p.Kind == MessageKind_JOIN {
		if tmp8ByteIO != nil {
			var err error
			p.tmp96.tmp99.NickNameLen, err = tmp8ByteIO.ReadByte()
			if err != nil {
				return err
			}
		} else {
			var err error
			var n int
			buf := [1]byte{0}
			if n, err = io.ReadFull(tmp8, buf[:]); err != nil {
				return err
			}
			if n != 1 {
				return fmt.Errorf("failed to read byte for field \"PubSubRequest::tmp96::NickNameLen\": expected to read 1 byte, but read %d bytes", n)
			}
			p.tmp96.tmp99.NickNameLen = buf[0]
		}
		if seeker, ok := tmp8.(io.Seeker); ok {
			current, err := seeker.Seek(0, io.SeekCurrent)
			if err != nil {
				return err
			}
			endOffset, err := seeker.Seek(0, io.SeekEnd)
			if err != nil {
				return err
			}
			_, err = seeker.Seek(current, io.SeekStart)
			if err != nil {
				return err
			}
			if (endOffset - current) < int64(int(p.tmp96.tmp99.NickNameLen)) {
				return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.tmp96.tmp99.NickNameLen)))
			}
			p.tmp96.tmp99.NickName = make([]byte, int(p.tmp96.tmp99.NickNameLen))
			if _, err := io.ReadFull(tmp8, p.tmp96.tmp99.NickName[0:0+int(p.tmp96.tmp99.NickNameLen)]); err != nil {
				return err
			}
		} else {
			// To mitigate DoS attack, use incremental buffer allocation
			// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
			io_temp_533 := bytes.NewBuffer(nil)
			if _, err := io.CopyN(io_temp_533, tmp8, int64(int(p.tmp96.tmp99.NickNameLen))); err != nil {
				return err
			}
			p.tmp96.tmp99.NickName = io_temp_533.Bytes()
		}
	}
	{
		var readErr error
		p.Topic, readErr = io.ReadAll(tmp8)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *PubSubRequest) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubRequest) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubRequest) DecodeSlice(tmp8 []byte, tmp8Offset *int) error {
	/* config.go.union("noheap")*/
	tmp97 := uint8(0)
	tmp74 := []uint8{}
	if len(tmp8)-*tmp8Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubRequest::Kind\"")
	}
	tmp74 = tmp8[*tmp8Offset : *tmp8Offset+1]
	*tmp8Offset += int(1)
	tmp97 = tmp74[0]
	p.Kind = MessageKind(tmp97)
	tmp94 := []uint8{}
	if len(tmp8)-*tmp8Offset < 4 {
		return errors.New("not enough data to read for field \"PubSubRequest::RequestId\"")
	}
	tmp94 = tmp8[*tmp8Offset : *tmp8Offset+4]
	*tmp8Offset += int(4)
	p.RequestId = binary.BigEndian.Uint32(tmp94[:])
	if p.Kind == MessageKind_JOIN {
		tmp148 := []uint8{}
		if len(tmp8)-*tmp8Offset < 1 {
			return errors.New("not enough data to read for field \"PubSubRequest::tmp96::NickNameLen\"")
		}
		tmp148 = tmp8[*tmp8Offset : *tmp8Offset+1]
		*tmp8Offset += int(1)
		p.tmp96.tmp99.NickNameLen = tmp148[0]
		if len(tmp8)-*tmp8Offset < int(p.tmp96.tmp99.NickNameLen) {
			return errors.New("not enough data to read for field \"PubSubRequest::tmp96::NickName\"")
		}
		p.tmp96.tmp99.NickName = tmp8[*tmp8Offset : *tmp8Offset+int(p.tmp96.tmp99.NickNameLen)]
		*tmp8Offset += int(int(p.tmp96.tmp99.NickNameLen))
	}
	p.Topic = tmp8[*tmp8Offset:]
	*tmp8Offset += len(p.Topic)
	return nil
}
func (s *PubSubRequest) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubRequest) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Status uint8

const (
	Status_Ok                Status = 0
	Status_AlreadySubscribed Status = 1
	Status_UnknownMessage    Status = 2
	Status_UnknownTopic      Status = 3
)

func (e Status) String() string {
	switch e {
	case Status_Ok:
		return "Ok"
	case Status_AlreadySubscribed:
		return "AlreadySubscribed"
	case Status_UnknownMessage:
		return "UnknownMessage"
	case Status_UnknownTopic:
		return "UnknownTopic"
	default:
		return fmt.Sprintf("Status(%d)", e)
	}
}

type PubSubResponse struct {
	RequestId uint32
	Status    Status
	StreamId  uint64
}

func (p *PubSubResponse) Write(tmp19 io.Writer) error {
	tmp109 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp109[:], uint32(p.RequestId))
	if _, err := tmp19.Write(tmp109[:4]); err != nil {
		return err
	}
	tmp106 := [1]uint8{}
	tmp106[0] = uint8(p.Status)
	if _, err := tmp19.Write(tmp106[:1]); err != nil {
		return err
	}
	tmp103 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp103[:], uint64(p.StreamId))
	if _, err := tmp19.Write(tmp103[:8]); err != nil {
		return err
	}
	return nil
}
func (s *PubSubResponse) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubResponse) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) EncodeSlice(tmp19 []byte, tmp19Offset *int) error {
	tmp109 := []uint8{}
	if len(tmp19)-*tmp19Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::RequestId\"")
	}
	tmp109 = tmp19[*tmp19Offset : *tmp19Offset+int(4)]
	binary.BigEndian.PutUint32(tmp109[:], uint32(p.RequestId))
	*tmp19Offset += int(4)
	tmp106 := []uint8{}
	if len(tmp19)-*tmp19Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::Status\"")
	}
	tmp106 = tmp19[*tmp19Offset : *tmp19Offset+int(1)]
	tmp106[0] = uint8(p.Status)
	*tmp19Offset += int(1)
	tmp103 := []uint8{}
	if len(tmp19)-*tmp19Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::StreamId\"")
	}
	tmp103 = tmp19[*tmp19Offset : *tmp19Offset+int(8)]
	binary.BigEndian.PutUint64(tmp103[:], uint64(p.StreamId))
	*tmp19Offset += int(8)
	return nil
}
func (s *PubSubResponse) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubResponse) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) Append(tmp19 []byte) ([]byte, error) {
	tmp109 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp109[:], uint32(p.RequestId))
	tmp19 = append(tmp19, tmp109[:4]...)
	tmp106 := [1]uint8{}
	tmp106[0] = uint8(p.Status)
	tmp19 = append(tmp19, tmp106[:1]...)
	tmp103 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp103[:], uint64(p.StreamId))
	tmp19 = append(tmp19, tmp103[:8]...)
	return tmp19, nil
}
func (s *PubSubResponse) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubResponse) Read(tmp21 io.Reader) error {
	tmp162 := [4]uint8{}
	if _, err := io.ReadFull(tmp21, tmp162[0:0+4]); err != nil {
		return err
	}
	p.RequestId = binary.BigEndian.Uint32(tmp162[:])
	tmp154 := uint8(0)
	tmp123 := [1]uint8{}
	if _, err := io.ReadFull(tmp21, tmp123[0:0+1]); err != nil {
		return err
	}
	tmp154 = tmp123[0]
	p.Status = Status(tmp154)
	tmp149 := [8]uint8{}
	if _, err := io.ReadFull(tmp21, tmp149[0:0+8]); err != nil {
		return err
	}
	p.StreamId = binary.BigEndian.Uint64(tmp149[:])
	return nil
}
func (s *PubSubResponse) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubResponse) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubResponse) DecodeSlice(tmp21 []byte, tmp21Offset *int) error {
	tmp162 := []uint8{}
	if len(tmp21)-*tmp21Offset < 4 {
		return errors.New("not enough data to read for field \"PubSubResponse::RequestId\"")
	}
	tmp162 = tmp21[*tmp21Offset : *tmp21Offset+4]
	*tmp21Offset += int(4)
	p.RequestId = binary.BigEndian.Uint32(tmp162[:])
	tmp154 := uint8(0)
	tmp123 := []uint8{}
	if len(tmp21)-*tmp21Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubResponse::Status\"")
	}
	tmp123 = tmp21[*tmp21Offset : *tmp21Offset+1]
	*tmp21Offset += int(1)
	tmp154 = tmp123[0]
	p.Status = Status(tmp154)
	tmp149 := []uint8{}
	if len(tmp21)-*tmp21Offset < 8 {
		return errors.New("not enough data to read for field \"PubSubResponse::StreamId\"")
	}
	tmp149 = tmp21[*tmp21Offset : *tmp21Offset+8]
	*tmp21Offset += int(8)
	p.StreamId = binary.BigEndian.Uint64(tmp149[:])
	return nil
}
func (s *PubSubResponse) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubResponse) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
