// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package protocol

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("protocol")*/
type MessageKind uint8

const (
	MessageKind_JOIN  MessageKind = 0
	MessageKind_LEAVE MessageKind = 1
)

func (e MessageKind) String() string {
	switch e {
	case MessageKind_JOIN:
		return "JOIN"
	case MessageKind_LEAVE:
		return "LEAVE"
	default:
		return fmt.Sprintf("MessageKind(%d)", e)
	}
}

type tmp57 struct {
	NickNameLen uint8
	NickName    []uint8
}

type Variant44 struct {
	tmp57 tmp57
}

type PubSubRequest struct {
	Kind  MessageKind
	tmp59 Variant44
	Topic []uint8
}

func (p *PubSubRequest) NickName() *[]uint8 {
	if p.Kind == MessageKind_JOIN {
		return &p.tmp59.tmp57.NickName
	}
	return nil
}
func (p *PubSubRequest) SetNickName(tmp110 []uint8) bool {
	if p.Kind == MessageKind_JOIN {
		if len(tmp110) > int(255) {
			return false
		}
		p.tmp59.tmp57.NickNameLen = uint8(len(tmp110))
		p.tmp59.tmp57.NickName = tmp110
		return true
	}
	return false
}

func (p *PubSubRequest) NickNameLen() *uint8 {
	if p.Kind == MessageKind_JOIN {
		return &p.tmp59.tmp57.NickNameLen
	}
	return nil
}
func (p *PubSubRequest) SetNickNameLen(tmp118 uint8) bool {
	if p.Kind == MessageKind_JOIN {
		p.tmp59.tmp57.NickNameLen = tmp118
		return true
	}
	return false
}

func (p *PubSubRequest) Write(tmp21 io.Writer) error {
	tmp21ByteIO, _ := tmp21.(io.ByteWriter)
	_ = tmp21ByteIO
	/* config.go.union("noheap")*/
	if tmp21ByteIO != nil {
		if err := tmp21ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp21.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	if p.Kind == MessageKind_JOIN {
		if tmp21ByteIO != nil {
			if err := tmp21ByteIO.WriteByte(p.tmp59.tmp57.NickNameLen); err != nil {
				return err
			}
		} else {
			if _, err := tmp21.Write([]byte{p.tmp59.tmp57.NickNameLen}); err != nil {
				return err
			}
		}
		if len(p.tmp59.tmp57.NickName) != int(p.tmp59.tmp57.NickNameLen) {
			return fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp59::NickName\": expected %d, got %d", int(p.tmp59.tmp57.NickNameLen), len(p.tmp59.tmp57.NickName))
		}
		if _, err := tmp21.Write(p.tmp59.tmp57.NickName); err != nil {
			return err
		}
	}
	if _, err := tmp21.Write(p.Topic); err != nil {
		return err
	}
	return nil
}
func (s *PubSubRequest) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubRequest) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) EncodeSlice(tmp21 []byte, tmp21Offset *int) error {
	/* config.go.union("noheap")*/
	tmp50 := []uint8{}
	if len(tmp21)-*tmp21Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubRequest::Kind\"")
	}
	tmp50 = tmp21[*tmp21Offset : *tmp21Offset+int(1)]
	tmp50[0] = uint8(p.Kind)
	*tmp21Offset += int(1)
	if p.Kind == MessageKind_JOIN {
		tmp103 := []uint8{}
		if len(tmp21)-*tmp21Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"PubSubRequest::tmp59::NickNameLen\"")
		}
		tmp103 = tmp21[*tmp21Offset : *tmp21Offset+int(1)]
		tmp103[0] = p.tmp59.tmp57.NickNameLen
		*tmp21Offset += int(1)
		if len(p.tmp59.tmp57.NickName) != int(p.tmp59.tmp57.NickNameLen) {
			return fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp59::NickName\": expected %d, got %d", int(p.tmp59.tmp57.NickNameLen), len(p.tmp59.tmp57.NickName))
		}
		if len(tmp21)-*tmp21Offset < int(0+p.tmp59.tmp57.NickNameLen) {
			return errors.New("not enough space to write for field \"PubSubRequest::tmp59::NickName\"")
		}
		copy(tmp21[*tmp21Offset:*tmp21Offset+int(p.tmp59.tmp57.NickNameLen)], p.tmp59.tmp57.NickName)
		*tmp21Offset += int(p.tmp59.tmp57.NickNameLen)
	}
	if len(tmp21)-*tmp21Offset < int(0+len(p.Topic)) {
		return errors.New("not enough space to write for field \"PubSubRequest::Topic\"")
	}
	copy(tmp21[*tmp21Offset:*tmp21Offset+int(len(p.Topic))], p.Topic)
	*tmp21Offset += int(len(p.Topic))
	return nil
}
func (s *PubSubRequest) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubRequest) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) Append(tmp21 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp50 := [1]uint8{}
	tmp50[0] = uint8(p.Kind)
	tmp21 = append(tmp21, tmp50[:1]...)
	if p.Kind == MessageKind_JOIN {
		tmp103 := [1]uint8{}
		tmp103[0] = p.tmp59.tmp57.NickNameLen
		tmp21 = append(tmp21, tmp103[:1]...)
		if len(p.tmp59.tmp57.NickName) != int(p.tmp59.tmp57.NickNameLen) {
			return nil, fmt.Errorf("size mismatch when writing field \"PubSubRequest::tmp59::NickName\": expected %d, got %d", int(p.tmp59.tmp57.NickNameLen), len(p.tmp59.tmp57.NickName))
		}
		tmp21 = append(tmp21, p.tmp59.tmp57.NickName...)
	}
	tmp21 = append(tmp21, p.Topic...)
	return tmp21, nil
}
func (s *PubSubRequest) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubRequest) Read(tmp17 io.Reader) error {
	tmp17ByteIO, _ := tmp17.(io.ByteReader)
	_ = tmp17ByteIO
	/* config.go.union("noheap")*/
	tmp62 := uint8(0)
	if tmp17ByteIO != nil {
		var err error
		tmp62, err = tmp17ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp17, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PubSubRequest::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp62 = buf[0]
	}
	p.Kind = MessageKind(tmp62)
	if p.Kind == MessageKind_JOIN {
		if tmp17ByteIO != nil {
			var err error
			p.tmp59.tmp57.NickNameLen, err = tmp17ByteIO.ReadByte()
			if err != nil {
				return err
			}
		} else {
			var err error
			var n int
			buf := [1]byte{0}
			if n, err = io.ReadFull(tmp17, buf[:]); err != nil {
				return err
			}
			if n != 1 {
				return fmt.Errorf("failed to read byte for field \"PubSubRequest::tmp59::NickNameLen\": expected to read 1 byte, but read %d bytes", n)
			}
			p.tmp59.tmp57.NickNameLen = buf[0]
		}
		if seeker, ok := tmp17.(io.Seeker); ok {
			current, err := seeker.Seek(0, io.SeekCurrent)
			if err != nil {
				return err
			}
			endOffset, err := seeker.Seek(0, io.SeekEnd)
			if err != nil {
				return err
			}
			_, err = seeker.Seek(current, io.SeekStart)
			if err != nil {
				return err
			}
			if (endOffset - current) < int64(int(p.tmp59.tmp57.NickNameLen)) {
				return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.tmp59.tmp57.NickNameLen)))
			}
			p.tmp59.tmp57.NickName = make([]byte, int(p.tmp59.tmp57.NickNameLen))
			if _, err := io.ReadFull(tmp17, p.tmp59.tmp57.NickName[0:0+int(p.tmp59.tmp57.NickNameLen)]); err != nil {
				return err
			}
		} else {
			// To mitigate DoS attack, use incremental buffer allocation
			// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
			io_temp_206 := bytes.NewBuffer(nil)
			if _, err := io.CopyN(io_temp_206, tmp17, int64(int(p.tmp59.tmp57.NickNameLen))); err != nil {
				return err
			}
			p.tmp59.tmp57.NickName = io_temp_206.Bytes()
		}
	}
	{
		var readErr error
		p.Topic, readErr = io.ReadAll(tmp17)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *PubSubRequest) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubRequest) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubRequest) DecodeSlice(tmp17 []byte, tmp17Offset *int) error {
	/* config.go.union("noheap")*/
	tmp62 := uint8(0)
	tmp49 := []uint8{}
	if len(tmp17)-*tmp17Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubRequest::Kind\"")
	}
	tmp49 = tmp17[*tmp17Offset : *tmp17Offset+1]
	*tmp17Offset += int(1)
	tmp62 = tmp49[0]
	p.Kind = MessageKind(tmp62)
	if p.Kind == MessageKind_JOIN {
		tmp93 := []uint8{}
		if len(tmp17)-*tmp17Offset < 1 {
			return errors.New("not enough data to read for field \"PubSubRequest::tmp59::NickNameLen\"")
		}
		tmp93 = tmp17[*tmp17Offset : *tmp17Offset+1]
		*tmp17Offset += int(1)
		p.tmp59.tmp57.NickNameLen = tmp93[0]
		if len(tmp17)-*tmp17Offset < int(p.tmp59.tmp57.NickNameLen) {
			return errors.New("not enough data to read for field \"PubSubRequest::tmp59::NickName\"")
		}
		p.tmp59.tmp57.NickName = tmp17[*tmp17Offset : *tmp17Offset+int(p.tmp59.tmp57.NickNameLen)]
		*tmp17Offset += int(int(p.tmp59.tmp57.NickNameLen))
	}
	p.Topic = tmp17[*tmp17Offset:]
	*tmp17Offset += len(p.Topic)
	return nil
}
func (s *PubSubRequest) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubRequest) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Status uint8

const (
	Status_Ok                Status = 0
	Status_AlreadySubscribed Status = 1
	Status_UnknownMessage    Status = 2
	Status_UnknownTopic      Status = 3
)

func (e Status) String() string {
	switch e {
	case Status_Ok:
		return "Ok"
	case Status_AlreadySubscribed:
		return "AlreadySubscribed"
	case Status_UnknownMessage:
		return "UnknownMessage"
	case Status_UnknownTopic:
		return "UnknownTopic"
	default:
		return fmt.Sprintf("Status(%d)", e)
	}
}

type PubSubResponse struct {
	Status   Status
	StreamId uint64
}

func (p *PubSubResponse) Write(tmp30 io.Writer) error {
	tmp138 := [1]uint8{}
	tmp138[0] = uint8(p.Status)
	if _, err := tmp30.Write(tmp138[:1]); err != nil {
		return err
	}
	tmp136 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp136[:], uint64(p.StreamId))
	if _, err := tmp30.Write(tmp136[:8]); err != nil {
		return err
	}
	return nil
}
func (s *PubSubResponse) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubResponse) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) EncodeSlice(tmp30 []byte, tmp30Offset *int) error {
	tmp138 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::Status\"")
	}
	tmp138 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp138[0] = uint8(p.Status)
	*tmp30Offset += int(1)
	tmp136 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::StreamId\"")
	}
	tmp136 = tmp30[*tmp30Offset : *tmp30Offset+int(8)]
	binary.BigEndian.PutUint64(tmp136[:], uint64(p.StreamId))
	*tmp30Offset += int(8)
	return nil
}
func (s *PubSubResponse) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubResponse) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) Append(tmp30 []byte) ([]byte, error) {
	tmp138 := [1]uint8{}
	tmp138[0] = uint8(p.Status)
	tmp30 = append(tmp30, tmp138[:1]...)
	tmp136 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp136[:], uint64(p.StreamId))
	tmp30 = append(tmp30, tmp136[:8]...)
	return tmp30, nil
}
func (s *PubSubResponse) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubResponse) Read(tmp29 io.Reader) error {
	tmp123 := uint8(0)
	tmp124 := [1]uint8{}
	if _, err := io.ReadFull(tmp29, tmp124[0:0+1]); err != nil {
		return err
	}
	tmp123 = tmp124[0]
	p.Status = Status(tmp123)
	tmp125 := [8]uint8{}
	if _, err := io.ReadFull(tmp29, tmp125[0:0+8]); err != nil {
		return err
	}
	p.StreamId = binary.BigEndian.Uint64(tmp125[:])
	return nil
}
func (s *PubSubResponse) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubResponse) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubResponse) DecodeSlice(tmp29 []byte, tmp29Offset *int) error {
	tmp123 := uint8(0)
	tmp124 := []uint8{}
	if len(tmp29)-*tmp29Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubResponse::Status\"")
	}
	tmp124 = tmp29[*tmp29Offset : *tmp29Offset+1]
	*tmp29Offset += int(1)
	tmp123 = tmp124[0]
	p.Status = Status(tmp123)
	tmp125 := []uint8{}
	if len(tmp29)-*tmp29Offset < 8 {
		return errors.New("not enough data to read for field \"PubSubResponse::StreamId\"")
	}
	tmp125 = tmp29[*tmp29Offset : *tmp29Offset+8]
	*tmp29Offset += int(8)
	p.StreamId = binary.BigEndian.Uint64(tmp125[:])
	return nil
}
func (s *PubSubResponse) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubResponse) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
