// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package protocol

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("protocol")*/
type MessageKind uint8

const (
	MessageKind_JOIN  MessageKind = 0
	MessageKind_LEAVE MessageKind = 1
)

func (e MessageKind) String() string {
	switch e {
	case MessageKind_JOIN:
		return "JOIN"
	case MessageKind_LEAVE:
		return "LEAVE"
	default:
		return fmt.Sprintf("MessageKind(%d)", e)
	}
}

type PubSubRequest struct {
	Kind  MessageKind
	Topic []uint8
}

func (p *PubSubRequest) Write(tmp23 io.Writer) error {
	tmp23ByteIO, _ := tmp23.(io.ByteWriter)
	_ = tmp23ByteIO
	if tmp23ByteIO != nil {
		if err := tmp23ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp23.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	if _, err := tmp23.Write(p.Topic); err != nil {
		return err
	}
	return nil
}
func (s *PubSubRequest) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubRequest) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) EncodeSlice(tmp23 []byte, tmp23Offset *int) error {
	tmp42 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubRequest::Kind\"")
	}
	tmp42 = tmp23[*tmp23Offset : *tmp23Offset+int(1)]
	tmp42[0] = uint8(p.Kind)
	*tmp23Offset += int(1)
	if len(tmp23)-*tmp23Offset < int(0+len(p.Topic)) {
		return errors.New("not enough space to write for field \"PubSubRequest::Topic\"")
	}
	copy(tmp23[*tmp23Offset:*tmp23Offset+int(len(p.Topic))], p.Topic)
	*tmp23Offset += int(len(p.Topic))
	return nil
}
func (s *PubSubRequest) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubRequest) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubRequest) Append(tmp23 []byte) ([]byte, error) {
	tmp42 := [1]uint8{}
	tmp42[0] = uint8(p.Kind)
	tmp23 = append(tmp23, tmp42[:1]...)
	tmp23 = append(tmp23, p.Topic...)
	return tmp23, nil
}
func (s *PubSubRequest) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubRequest) Read(tmp18 io.Reader) error {
	tmp18ByteIO, _ := tmp18.(io.ByteReader)
	_ = tmp18ByteIO
	tmp33 := uint8(0)
	if tmp18ByteIO != nil {
		var err error
		tmp33, err = tmp18ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp18, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PubSubRequest::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp33 = buf[0]
	}
	p.Kind = MessageKind(tmp33)
	{
		var readErr error
		p.Topic, readErr = io.ReadAll(tmp18)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *PubSubRequest) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubRequest) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubRequest) DecodeSlice(tmp18 []byte, tmp18Offset *int) error {
	tmp33 := uint8(0)
	tmp35 := []uint8{}
	if len(tmp18)-*tmp18Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubRequest::Kind\"")
	}
	tmp35 = tmp18[*tmp18Offset : *tmp18Offset+1]
	*tmp18Offset += int(1)
	tmp33 = tmp35[0]
	p.Kind = MessageKind(tmp33)
	p.Topic = tmp18[*tmp18Offset:]
	*tmp18Offset += len(p.Topic)
	return nil
}
func (s *PubSubRequest) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubRequest) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Status uint8

const (
	Status_Ok                Status = 0
	Status_AlreadySubscribed Status = 1
	Status_UnknownMessage    Status = 2
	Status_UnknownTopic      Status = 3
)

func (e Status) String() string {
	switch e {
	case Status_Ok:
		return "Ok"
	case Status_AlreadySubscribed:
		return "AlreadySubscribed"
	case Status_UnknownMessage:
		return "UnknownMessage"
	case Status_UnknownTopic:
		return "UnknownTopic"
	default:
		return fmt.Sprintf("Status(%d)", e)
	}
}

type PubSubResponse struct {
	Status   Status
	StreamId uint64
}

func (p *PubSubResponse) Write(tmp16 io.Writer) error {
	tmp85 := [1]uint8{}
	tmp85[0] = uint8(p.Status)
	if _, err := tmp16.Write(tmp85[:1]); err != nil {
		return err
	}
	tmp82 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp82[:], uint64(p.StreamId))
	if _, err := tmp16.Write(tmp82[:8]); err != nil {
		return err
	}
	return nil
}
func (s *PubSubResponse) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PubSubResponse) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) EncodeSlice(tmp16 []byte, tmp16Offset *int) error {
	tmp85 := []uint8{}
	if len(tmp16)-*tmp16Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::Status\"")
	}
	tmp85 = tmp16[*tmp16Offset : *tmp16Offset+int(1)]
	tmp85[0] = uint8(p.Status)
	*tmp16Offset += int(1)
	tmp82 := []uint8{}
	if len(tmp16)-*tmp16Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"PubSubResponse::StreamId\"")
	}
	tmp82 = tmp16[*tmp16Offset : *tmp16Offset+int(8)]
	binary.BigEndian.PutUint64(tmp82[:], uint64(p.StreamId))
	*tmp16Offset += int(8)
	return nil
}
func (s *PubSubResponse) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PubSubResponse) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PubSubResponse) Append(tmp16 []byte) ([]byte, error) {
	tmp85 := [1]uint8{}
	tmp85[0] = uint8(p.Status)
	tmp16 = append(tmp16, tmp85[:1]...)
	tmp82 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp82[:], uint64(p.StreamId))
	tmp16 = append(tmp16, tmp82[:8]...)
	return tmp16, nil
}
func (s *PubSubResponse) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PubSubResponse) Read(tmp15 io.Reader) error {
	tmp66 := uint8(0)
	tmp67 := [1]uint8{}
	if _, err := io.ReadFull(tmp15, tmp67[0:0+1]); err != nil {
		return err
	}
	tmp66 = tmp67[0]
	p.Status = Status(tmp66)
	tmp69 := [8]uint8{}
	if _, err := io.ReadFull(tmp15, tmp69[0:0+8]); err != nil {
		return err
	}
	p.StreamId = binary.BigEndian.Uint64(tmp69[:])
	return nil
}
func (s *PubSubResponse) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PubSubResponse) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PubSubResponse) DecodeSlice(tmp15 []byte, tmp15Offset *int) error {
	tmp66 := uint8(0)
	tmp67 := []uint8{}
	if len(tmp15)-*tmp15Offset < 1 {
		return errors.New("not enough data to read for field \"PubSubResponse::Status\"")
	}
	tmp67 = tmp15[*tmp15Offset : *tmp15Offset+1]
	*tmp15Offset += int(1)
	tmp66 = tmp67[0]
	p.Status = Status(tmp66)
	tmp69 := []uint8{}
	if len(tmp15)-*tmp15Offset < 8 {
		return errors.New("not enough data to read for field \"PubSubResponse::StreamId\"")
	}
	tmp69 = tmp15[*tmp15Offset : *tmp15Offset+8]
	*tmp15Offset += int(8)
	p.StreamId = binary.BigEndian.Uint64(tmp69[:])
	return nil
}
func (s *PubSubResponse) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PubSubResponse) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
