// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package wire

import (
	"bytes"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("wire")*/
func (v *Varint) Prefix() uint8 {
	return uint8(((v.tmp212 >> uint64(62)) & uint64(3)))
}

func (v *Varint) SetPrefix(tmp686 uint8) bool {
	v.tmp212 = (v.tmp212 & (^(uint64(3) << uint64(62)))) | ((uint64(tmp686) & uint64(3)) << uint64(62))
	return true
}

func (v *Varint) tmp708() uint64 {
	return uint64(((v.tmp212 >> uint64(0)) & uint64(4611686018427387903)))
}

func (v *Varint) settmp378(tmp706 uint64) bool {
	v.tmp212 = (v.tmp212 & (^(uint64(4611686018427387903) << uint64(0)))) | ((uint64(tmp706) & uint64(4611686018427387903)) << uint64(0))
	return true
}

type Varint struct {
	tmp212 uint64
}

func (v *Varint) Value() uint64 {
	if v.Prefix() == uint8(0) {
		return uint64(uint8(v.tmp708()))
	} else if v.Prefix() == uint8(1) {
		return uint64(uint16(v.tmp708()))
	} else if v.Prefix() == 2 {
		return uint64(uint32(v.tmp708()))
	} else if v.Prefix() == 3 {
		return uint64(uint64(v.tmp708()))
	}
	return uint64(0)
}
func (v *Varint) SetValue(tmp633 uint64) bool {
	if v.Prefix() == uint8(0) {
		v.settmp378(uint64(uint8(tmp633)))
		return true
	} else if v.Prefix() == uint8(1) {
		v.settmp378(uint64(uint16(tmp633)))
		return true
	} else if v.Prefix() == 2 {
		v.settmp378(uint64(uint32(tmp633)))
		return true
	} else if v.Prefix() == 3 {
		v.settmp378(uint64(uint64(tmp633)))
		return true
	}
	return false
}

func (v *Varint) Write(tmp69 io.Writer) error {
	tmp647 := [8]uint8{}
	tmp647[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp647[0] = tmp647[0] | uint8((uint8(v.tmp708()) & 63))
		if _, err := tmp69.Write(tmp647[:1]); err != nil {
			return err
		}
	} else if v.Prefix() == uint8(1) {
		tmp647[0] = tmp647[0] | uint8(((uint16(v.tmp708()) >> uint16(8)) & uint16(63)))
		tmp647[1] = uint8((uint16(v.tmp708()) & uint16(255)))
		if _, err := tmp69.Write(tmp647[:2]); err != nil {
			return err
		}
	} else if v.Prefix() == 2 {
		tmp647[0] = tmp647[0] | uint8(((uint32(v.tmp708()) >> uint32(24)) & uint32(63)))
		tmp647[1] = uint8(((uint32(v.tmp708()) >> uint32(16)) & uint32(255)))
		tmp647[2] = uint8(((uint32(v.tmp708()) >> uint32(8)) & uint32(255)))
		tmp647[3] = uint8((uint32(v.tmp708()) & uint32(255)))
		if _, err := tmp69.Write(tmp647[:4]); err != nil {
			return err
		}
	} else if v.Prefix() == 3 {
		tmp647[0] = tmp647[0] | uint8(((uint64(v.tmp708()) >> uint64(56)) & uint64(63)))
		tmp647[1] = uint8(((uint64(v.tmp708()) >> uint64(48)) & uint64(255)))
		tmp647[2] = uint8(((uint64(v.tmp708()) >> uint64(40)) & uint64(255)))
		tmp647[3] = uint8(((uint64(v.tmp708()) >> uint64(32)) & uint64(255)))
		tmp647[4] = uint8(((uint64(v.tmp708()) >> uint64(24)) & uint64(255)))
		tmp647[5] = uint8(((uint64(v.tmp708()) >> uint64(16)) & uint64(255)))
		tmp647[6] = uint8(((uint64(v.tmp708()) >> uint64(8)) & uint64(255)))
		tmp647[7] = uint8((uint64(v.tmp708()) & uint64(255)))
		if _, err := tmp69.Write(tmp647[:8]); err != nil {
			return err
		}
	}
	return nil
}
func (s *Varint) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Varint) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) EncodeSlice(tmp69 []byte, tmp69Offset *int) error {
	tmp647 := []uint8{}
	if len(tmp69)-*tmp69Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Varint::tmp383::Value\"")
	}
	tmp647 = tmp69[*tmp69Offset : *tmp69Offset+int(1)]
	tmp647[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		if len(tmp69)-*tmp69Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp383::Value\"")
		}
		tmp647 = tmp69[*tmp69Offset : *tmp69Offset+int(1)]
		tmp647[0] = tmp647[0] | uint8((uint8(v.tmp708()) & 63))
		*tmp69Offset += int(1)
	} else if v.Prefix() == uint8(1) {
		if len(tmp69)-*tmp69Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp383::Value\"")
		}
		tmp647 = tmp69[*tmp69Offset : *tmp69Offset+int(2)]
		tmp647[0] = tmp647[0] | uint8(((uint16(v.tmp708()) >> uint16(8)) & uint16(63)))
		tmp647[1] = uint8((uint16(v.tmp708()) & uint16(255)))
		*tmp69Offset += int(2)
	} else if v.Prefix() == 2 {
		if len(tmp69)-*tmp69Offset < int(4) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp383::Value\"")
		}
		tmp647 = tmp69[*tmp69Offset : *tmp69Offset+int(4)]
		tmp647[0] = tmp647[0] | uint8(((uint32(v.tmp708()) >> uint32(24)) & uint32(63)))
		tmp647[1] = uint8(((uint32(v.tmp708()) >> uint32(16)) & uint32(255)))
		tmp647[2] = uint8(((uint32(v.tmp708()) >> uint32(8)) & uint32(255)))
		tmp647[3] = uint8((uint32(v.tmp708()) & uint32(255)))
		*tmp69Offset += int(4)
	} else if v.Prefix() == 3 {
		if len(tmp69)-*tmp69Offset < int(8) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp383::Value\"")
		}
		tmp647 = tmp69[*tmp69Offset : *tmp69Offset+int(8)]
		tmp647[0] = tmp647[0] | uint8(((uint64(v.tmp708()) >> uint64(56)) & uint64(63)))
		tmp647[1] = uint8(((uint64(v.tmp708()) >> uint64(48)) & uint64(255)))
		tmp647[2] = uint8(((uint64(v.tmp708()) >> uint64(40)) & uint64(255)))
		tmp647[3] = uint8(((uint64(v.tmp708()) >> uint64(32)) & uint64(255)))
		tmp647[4] = uint8(((uint64(v.tmp708()) >> uint64(24)) & uint64(255)))
		tmp647[5] = uint8(((uint64(v.tmp708()) >> uint64(16)) & uint64(255)))
		tmp647[6] = uint8(((uint64(v.tmp708()) >> uint64(8)) & uint64(255)))
		tmp647[7] = uint8((uint64(v.tmp708()) & uint64(255)))
		*tmp69Offset += int(8)
	}
	return nil
}
func (s *Varint) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Varint) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) Append(tmp69 []byte) ([]byte, error) {
	tmp647 := [8]uint8{}
	tmp647[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp647[0] = tmp647[0] | uint8((uint8(v.tmp708()) & 63))
		tmp69 = append(tmp69, tmp647[:1]...)
	} else if v.Prefix() == uint8(1) {
		tmp647[0] = tmp647[0] | uint8(((uint16(v.tmp708()) >> uint16(8)) & uint16(63)))
		tmp647[1] = uint8((uint16(v.tmp708()) & uint16(255)))
		tmp69 = append(tmp69, tmp647[:2]...)
	} else if v.Prefix() == 2 {
		tmp647[0] = tmp647[0] | uint8(((uint32(v.tmp708()) >> uint32(24)) & uint32(63)))
		tmp647[1] = uint8(((uint32(v.tmp708()) >> uint32(16)) & uint32(255)))
		tmp647[2] = uint8(((uint32(v.tmp708()) >> uint32(8)) & uint32(255)))
		tmp647[3] = uint8((uint32(v.tmp708()) & uint32(255)))
		tmp69 = append(tmp69, tmp647[:4]...)
	} else if v.Prefix() == 3 {
		tmp647[0] = tmp647[0] | uint8(((uint64(v.tmp708()) >> uint64(56)) & uint64(63)))
		tmp647[1] = uint8(((uint64(v.tmp708()) >> uint64(48)) & uint64(255)))
		tmp647[2] = uint8(((uint64(v.tmp708()) >> uint64(40)) & uint64(255)))
		tmp647[3] = uint8(((uint64(v.tmp708()) >> uint64(32)) & uint64(255)))
		tmp647[4] = uint8(((uint64(v.tmp708()) >> uint64(24)) & uint64(255)))
		tmp647[5] = uint8(((uint64(v.tmp708()) >> uint64(16)) & uint64(255)))
		tmp647[6] = uint8(((uint64(v.tmp708()) >> uint64(8)) & uint64(255)))
		tmp647[7] = uint8((uint64(v.tmp708()) & uint64(255)))
		tmp69 = append(tmp69, tmp647[:8]...)
	}
	return tmp69, nil
}
func (s *Varint) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (v *Varint) Read(tmp14 io.Reader) error {
	tmp712 := [8]uint8{}
	tmp727 := uint8(0)
	if _, err := io.ReadFull(tmp14, tmp712[0:0+1]); err != nil {
		return err
	}
	tmp727 = uint8(((tmp712[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp727)
	if v.Prefix() == uint8(0) {
		tmp722 := uint8(0)
		tmp722 = uint8((tmp712[0] & uint8(63)))
		v.settmp378(uint64(tmp722))
	} else if v.Prefix() == uint8(1) {
		tmp691 := uint16(0)
		if _, err := io.ReadFull(tmp14, tmp712[1:1+1]); err != nil {
			return err
		}
		tmp691 = (uint16((tmp712[0] & uint8(63))) << uint16(8)) | uint16(tmp712[1])
		v.settmp378(uint64(tmp691))
	} else if v.Prefix() == 2 {
		tmp685 := uint32(0)
		if _, err := io.ReadFull(tmp14, tmp712[1:1+3]); err != nil {
			return err
		}
		tmp685 = (((uint32((tmp712[0] & uint8(63))) << uint32(24)) | (uint32(tmp712[1]) << uint32(16))) | (uint32(tmp712[2]) << uint32(8))) | uint32(tmp712[3])
		v.settmp378(uint64(tmp685))
	} else if v.Prefix() == 3 {
		tmp672 := uint64(0)
		if _, err := io.ReadFull(tmp14, tmp712[1:1+7]); err != nil {
			return err
		}
		tmp672 = (((((((uint64((tmp712[0] & uint8(63))) << uint64(56)) | (uint64(tmp712[1]) << uint64(48))) | (uint64(tmp712[2]) << uint64(40))) | (uint64(tmp712[3]) << uint64(32))) | (uint64(tmp712[4]) << uint64(24))) | (uint64(tmp712[5]) << uint64(16))) | (uint64(tmp712[6]) << uint64(8))) | uint64(tmp712[7])
		v.settmp378(uint64(tmp672))
	}
	return nil
}
func (s *Varint) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Varint) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (v *Varint) DecodeSlice(tmp14 []byte, tmp14Offset *int) error {
	tmp712 := []uint8{}
	tmp727 := uint8(0)
	if len(tmp14)-*tmp14Offset < 1 {
		return errors.New("not enough data to read for field \"Varint::Prefix\"")
	}
	tmp712 = tmp14[*tmp14Offset : *tmp14Offset+1]
	*tmp14Offset += int(1)
	tmp727 = uint8(((tmp712[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp727)
	if v.Prefix() == uint8(0) {
		tmp722 := uint8(0)
		tmp722 = uint8((tmp712[0] & uint8(63)))
		v.settmp378(uint64(tmp722))
	} else if v.Prefix() == uint8(1) {
		tmp691 := uint16(0)
		if len(tmp14)-*tmp14Offset < 1 {
			return errors.New("not enough data to read for field \"Varint::tmp383::Value\"")
		}
		tmp712 = tmp712[:1+1]
		*tmp14Offset += int(1)
		tmp691 = (uint16((tmp712[0] & uint8(63))) << uint16(8)) | uint16(tmp712[1])
		v.settmp378(uint64(tmp691))
	} else if v.Prefix() == 2 {
		tmp685 := uint32(0)
		if len(tmp14)-*tmp14Offset < 3 {
			return errors.New("not enough data to read for field \"Varint::tmp383::Value\"")
		}
		tmp712 = tmp712[:1+3]
		*tmp14Offset += int(3)
		tmp685 = (((uint32((tmp712[0] & uint8(63))) << uint32(24)) | (uint32(tmp712[1]) << uint32(16))) | (uint32(tmp712[2]) << uint32(8))) | uint32(tmp712[3])
		v.settmp378(uint64(tmp685))
	} else if v.Prefix() == 3 {
		tmp672 := uint64(0)
		if len(tmp14)-*tmp14Offset < 7 {
			return errors.New("not enough data to read for field \"Varint::tmp383::Value\"")
		}
		tmp712 = tmp712[:1+7]
		*tmp14Offset += int(7)
		tmp672 = (((((((uint64((tmp712[0] & uint8(63))) << uint64(56)) | (uint64(tmp712[1]) << uint64(48))) | (uint64(tmp712[2]) << uint64(40))) | (uint64(tmp712[3]) << uint64(32))) | (uint64(tmp712[4]) << uint64(24))) | (uint64(tmp712[5]) << uint64(16))) | (uint64(tmp712[6]) << uint64(8))) | uint64(tmp712[7])
		v.settmp378(uint64(tmp672))
	}
	return nil
}
func (s *Varint) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Varint) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func VarintLen(Value uint64) uint8 {
	tmp90 := uint8(0)
	if (uint64(0) <= Value) && (Value <= 63) {
		tmp90 = 1
	} else if (uint64(64) <= Value) && (Value <= 16383) {
		tmp90 = 2
	} else if (uint64(16384) <= Value) && (Value <= 1073741823) {
		tmp90 = 4
	} else if (1073741824 <= Value) && (Value <= 70368744177663) {
		tmp90 = 8
	} else {
		tmp90 = 0
	}
	return tmp90
}
func VarintPrefix(Value uint64) uint8 {
	Len := VarintLen(Value)
	tmp158 := uint8(0)
	if Len == uint8(1) {
		tmp158 = 0
	} else if Len == uint8(2) {
		tmp158 = 1
	} else if Len == uint8(4) {
		tmp158 = 2
	} else if Len == uint8(8) {
		tmp158 = 3
	} else {
		tmp158 = 255
	}
	return tmp158
}
func (v *StreamPacket) HasId() bool {
	intVal := v.hasId()
	return intVal != 0
}
func (s *StreamPacket) hasId() uint8 {
	return uint8(((s.tmp45 >> uint8(7)) & uint8(1)))
}

func (s *StreamPacket) SetHasId(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasId(intVal)
}
func (s *StreamPacket) setHasId(tmp698 uint8) bool {
	s.tmp45 = (s.tmp45 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp698) & uint8(1)) << uint8(7))
	return true
}

func (s *StreamPacket) HasOffset() bool {
	intVal := s.hasOffset()
	return intVal != 0
}
func (s *StreamPacket) hasOffset() uint8 {
	return uint8(((s.tmp45 >> uint8(6)) & uint8(1)))
}

func (s *StreamPacket) SetHasOffset(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasOffset(intVal)
}
func (s *StreamPacket) setHasOffset(tmp635 uint8) bool {
	s.tmp45 = (s.tmp45 & (^(uint8(1) << uint8(6)))) | ((uint8(tmp635) & uint8(1)) << uint8(6))
	return true
}

func (s *StreamPacket) IsEof() bool {
	intVal := s.isEof()
	return intVal != 0
}
func (s *StreamPacket) isEof() uint8 {
	return uint8(((s.tmp45 >> uint8(5)) & uint8(1)))
}

func (s *StreamPacket) SetIsEof(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsEof(intVal)
}
func (s *StreamPacket) setIsEof(tmp678 uint8) bool {
	s.tmp45 = (s.tmp45 & (^(uint8(1) << uint8(5)))) | ((uint8(tmp678) & uint8(1)) << uint8(5))
	return true
}

func (s *StreamPacket) IsProbe() bool {
	intVal := s.isProbe()
	return intVal != 0
}
func (s *StreamPacket) isProbe() uint8 {
	return uint8(((s.tmp45 >> uint8(4)) & uint8(1)))
}

func (s *StreamPacket) SetIsProbe(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsProbe(intVal)
}
func (s *StreamPacket) setIsProbe(tmp577 uint8) bool {
	s.tmp45 = (s.tmp45 & (^(uint8(1) << uint8(4)))) | ((uint8(tmp577) & uint8(1)) << uint8(4))
	return true
}

func (s *StreamPacket) Reserved() uint8 {
	return uint8(((s.tmp45 >> uint8(0)) & uint8(15)))
}

func (s *StreamPacket) SetReserved(tmp584 uint8) bool {
	s.tmp45 = (s.tmp45 & (^(uint8(15) << uint8(0)))) | ((uint8(tmp584) & uint8(15)) << uint8(0))
	return true
}

type tmp599 struct {
	Id Varint
}

type Variant256 struct {
	tmp599 tmp599
}

type tmp634 struct {
	Offset Varint
}

type Variant273 struct {
	tmp634 tmp634
}

type StreamPacket struct {
	tmp45  uint8
	tmp335 Variant256
	tmp339 Variant273
	Data   []uint8
}

func (s *StreamPacket) Id() *Varint {
	if s.hasId() == 1 {
		return &s.tmp335.tmp599.Id
	}
	return nil
}
func (s *StreamPacket) SetId(tmp575 Varint) bool {
	if s.hasId() == 1 {
		s.tmp335.tmp599.Id = tmp575
		return true
	}
	return false
}

func (s *StreamPacket) Offset() *Varint {
	if s.hasOffset() == 1 {
		return &s.tmp339.tmp634.Offset
	}
	return nil
}
func (s *StreamPacket) SetOffset(tmp552 Varint) bool {
	if s.hasOffset() == 1 {
		s.tmp339.tmp634.Offset = tmp552
		return true
	}
	return false
}

func (s *StreamPacket) Write(tmp48 io.Writer) error {
	tmp48ByteIO, _ := tmp48.(io.ByteWriter)
	_ = tmp48ByteIO
	/* config.go.union("noheap")*/
	tmp649 := [1]uint8{}
	tmp649[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp649[0] = tmp649[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp649[0] = tmp649[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp649[0] = tmp649[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp649[0] = tmp649[0] | uint8((s.Reserved() & 15))
	if tmp48ByteIO != nil {
		if err := tmp48ByteIO.WriteByte(tmp649[0]); err != nil {
			return err
		}
	} else {
		if _, err := tmp48.Write([]byte{tmp649[0]}); err != nil {
			return err
		}
	}
	if s.hasId() == 1 {
		tmp630 := s.tmp335.tmp599.Id.Write(tmp48)
		if tmp630 != nil {
			return tmp630
		}
	}
	if s.hasOffset() == 1 {
		tmp626 := s.tmp339.tmp634.Offset.Write(tmp48)
		if tmp626 != nil {
			return tmp626
		}
	}
	if _, err := tmp48.Write(s.Data); err != nil {
		return err
	}
	return nil
}
func (s *StreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) EncodeSlice(tmp48 []byte, tmp48Offset *int) error {
	/* config.go.union("noheap")*/
	tmp649 := []uint8{}
	if len(tmp48)-*tmp48Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"StreamPacket::Reserved\"")
	}
	tmp649 = tmp48[*tmp48Offset : *tmp48Offset+int(1)]
	tmp649[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp649[0] = tmp649[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp649[0] = tmp649[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp649[0] = tmp649[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp649[0] = tmp649[0] | uint8((s.Reserved() & 15))
	*tmp48Offset += int(1)
	if s.hasId() == 1 {
		tmp630 := s.tmp335.tmp599.Id.EncodeSlice(tmp48, tmp48Offset)
		if tmp630 != nil {
			return tmp630
		}
	}
	if s.hasOffset() == 1 {
		tmp626 := s.tmp339.tmp634.Offset.EncodeSlice(tmp48, tmp48Offset)
		if tmp626 != nil {
			return tmp626
		}
	}
	if len(tmp48)-*tmp48Offset < int(0+len(s.Data)) {
		return errors.New("not enough space to write for field \"StreamPacket::Data\"")
	}
	copy(tmp48[*tmp48Offset:*tmp48Offset+int(len(s.Data))], s.Data)
	*tmp48Offset += int(len(s.Data))
	return nil
}
func (s *StreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) Append(tmp48 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp649 := [1]uint8{}
	tmp649[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp649[0] = tmp649[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp649[0] = tmp649[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp649[0] = tmp649[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp649[0] = tmp649[0] | uint8((s.Reserved() & 15))
	tmp48 = append(tmp48, tmp649[:1]...)
	if s.hasId() == 1 {
		var tmp630 error
		tmp48, tmp630 = s.tmp335.tmp599.Id.Append(tmp48)

		if tmp630 != nil {
			return nil, tmp630
		}
	}
	if s.hasOffset() == 1 {
		var tmp626 error
		tmp48, tmp626 = s.tmp339.tmp634.Offset.Append(tmp48)

		if tmp626 != nil {
			return nil, tmp626
		}
	}
	tmp48 = append(tmp48, s.Data...)
	return tmp48, nil
}
func (s *StreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamPacket) Read(tmp36 io.Reader) error {
	tmp36ByteIO, _ := tmp36.(io.ByteReader)
	_ = tmp36ByteIO
	/* config.go.union("noheap")*/
	tmp574 := [1]uint8{}
	if tmp36ByteIO != nil {
		var err error
		tmp574[0], err = tmp36ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp36, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"tmp252\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp574[0] = buf[0]
	}
	tmp192 := uint8(0)
	tmp192 = uint8(((tmp574[0] & 128) >> uint8(7)))
	s.setHasId(tmp192)
	tmp569 := uint8(0)
	tmp569 = uint8(((tmp574[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp569)
	tmp566 := uint8(0)
	tmp566 = uint8(((tmp574[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp566)
	tmp564 := uint8(0)
	tmp564 = uint8(((tmp574[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp564)
	tmp562 := uint8(0)
	tmp562 = uint8((tmp574[0] & uint8(15)))
	s.SetReserved(tmp562)
	if s.hasId() == 1 {
		tmp559 := s.tmp335.tmp599.Id.Read(tmp36)
		if tmp559 != nil {
			return tmp559
		}
	}
	if s.hasOffset() == 1 {
		tmp555 := s.tmp339.tmp634.Offset.Read(tmp36)
		if tmp555 != nil {
			return tmp555
		}
	}
	{
		var readErr error
		s.Data, readErr = io.ReadAll(tmp36)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *StreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamPacket) DecodeSlice(tmp36 []byte, tmp36Offset *int) error {
	/* config.go.union("noheap")*/
	tmp574 := []uint8{}
	if len(tmp36)-*tmp36Offset < 1 {
		return errors.New("not enough data to read for field \"tmp252\"")
	}
	tmp574 = tmp36[*tmp36Offset : *tmp36Offset+1]
	*tmp36Offset += int(1)
	tmp192 := uint8(0)
	tmp192 = uint8(((tmp574[0] & 128) >> uint8(7)))
	s.setHasId(tmp192)
	tmp569 := uint8(0)
	tmp569 = uint8(((tmp574[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp569)
	tmp566 := uint8(0)
	tmp566 = uint8(((tmp574[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp566)
	tmp564 := uint8(0)
	tmp564 = uint8(((tmp574[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp564)
	tmp562 := uint8(0)
	tmp562 = uint8((tmp574[0] & uint8(15)))
	s.SetReserved(tmp562)
	if s.hasId() == 1 {
		tmp559 := s.tmp335.tmp599.Id.DecodeSlice(tmp36, tmp36Offset)
		if tmp559 != nil {
			return tmp559
		}
	}
	if s.hasOffset() == 1 {
		tmp555 := s.tmp339.tmp634.Offset.DecodeSlice(tmp36, tmp36Offset)
		if tmp555 != nil {
			return tmp555
		}
	}
	s.Data = tmp36[*tmp36Offset:]
	*tmp36Offset += len(s.Data)
	return nil
}
func (s *StreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ACKRange struct {
	Offset Varint
	Delta  Varint
}

func (a *ACKRange) Write(tmp245 io.Writer) error {
	tmp542 := a.Offset.Write(tmp245)
	if tmp542 != nil {
		return tmp542
	}
	tmp540 := a.Delta.Write(tmp245)
	if tmp540 != nil {
		return tmp540
	}
	return nil
}
func (s *ACKRange) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ACKRange) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) EncodeSlice(tmp245 []byte, tmp245Offset *int) error {
	tmp542 := a.Offset.EncodeSlice(tmp245, tmp245Offset)
	if tmp542 != nil {
		return tmp542
	}
	tmp540 := a.Delta.EncodeSlice(tmp245, tmp245Offset)
	if tmp540 != nil {
		return tmp540
	}
	return nil
}
func (s *ACKRange) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ACKRange) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) Append(tmp245 []byte) ([]byte, error) {
	var tmp542 error
	tmp245, tmp542 = a.Offset.Append(tmp245)

	if tmp542 != nil {
		return nil, tmp542
	}
	var tmp540 error
	tmp245, tmp540 = a.Delta.Append(tmp245)

	if tmp540 != nil {
		return nil, tmp540
	}
	return tmp245, nil
}
func (s *ACKRange) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (a *ACKRange) Read(tmp246 io.Reader) error {
	tmp547 := a.Offset.Read(tmp246)
	if tmp547 != nil {
		return tmp547
	}
	tmp545 := a.Delta.Read(tmp246)
	if tmp545 != nil {
		return tmp545
	}
	return nil
}
func (s *ACKRange) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ACKRange) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (a *ACKRange) DecodeSlice(tmp246 []byte, tmp246Offset *int) error {
	tmp547 := a.Offset.DecodeSlice(tmp246, tmp246Offset)
	if tmp547 != nil {
		return tmp547
	}
	tmp545 := a.Delta.DecodeSlice(tmp246, tmp246Offset)
	if tmp545 != nil {
		return tmp545
	}
	return nil
}
func (s *ACKRange) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ACKRange) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type StreamACKPacket struct {
	LargestAck Varint
	FirstDelta Varint
	Len        Varint
	Ranges     []ACKRange
}

func (s *StreamACKPacket) Write(tmp114 io.Writer) error {
	tmp525 := s.LargestAck.Write(tmp114)
	if tmp525 != nil {
		return tmp525
	}
	tmp523 := s.FirstDelta.Write(tmp114)
	if tmp523 != nil {
		return tmp523
	}
	tmp521 := s.Len.Write(tmp114)
	if tmp521 != nil {
		return tmp521
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp241 := int(0)
	for tmp241 < int(s.Len.Value()) {
		tmp515 := s.Ranges[tmp241].Write(tmp114)
		if tmp515 != nil {
			return tmp515
		}
		tmp241 = tmp241 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamACKPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) EncodeSlice(tmp114 []byte, tmp114Offset *int) error {
	tmp525 := s.LargestAck.EncodeSlice(tmp114, tmp114Offset)
	if tmp525 != nil {
		return tmp525
	}
	tmp523 := s.FirstDelta.EncodeSlice(tmp114, tmp114Offset)
	if tmp523 != nil {
		return tmp523
	}
	tmp521 := s.Len.EncodeSlice(tmp114, tmp114Offset)
	if tmp521 != nil {
		return tmp521
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp241 := int(0)
	for tmp241 < int(s.Len.Value()) {
		tmp515 := s.Ranges[tmp241].EncodeSlice(tmp114, tmp114Offset)
		if tmp515 != nil {
			return tmp515
		}
		tmp241 = tmp241 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamACKPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) Append(tmp114 []byte) ([]byte, error) {
	var tmp525 error
	tmp114, tmp525 = s.LargestAck.Append(tmp114)

	if tmp525 != nil {
		return nil, tmp525
	}
	var tmp523 error
	tmp114, tmp523 = s.FirstDelta.Append(tmp114)

	if tmp523 != nil {
		return nil, tmp523
	}
	var tmp521 error
	tmp114, tmp521 = s.Len.Append(tmp114)

	if tmp521 != nil {
		return nil, tmp521
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return nil, fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp241 := int(0)
	for tmp241 < int(s.Len.Value()) {
		var tmp515 error
		tmp114, tmp515 = s.Ranges[tmp241].Append(tmp114)

		if tmp515 != nil {
			return nil, tmp515
		}
		tmp241 = tmp241 + int(1)
	}
	return tmp114, nil
}
func (s *StreamACKPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamACKPacket) Read(tmp115 io.Reader) error {
	tmp538 := s.LargestAck.Read(tmp115)
	if tmp538 != nil {
		return tmp538
	}
	tmp536 := s.FirstDelta.Read(tmp115)
	if tmp536 != nil {
		return tmp536
	}
	tmp534 := s.Len.Read(tmp115)
	if tmp534 != nil {
		return tmp534
	}
	tmp322 := int(0)
	for tmp322 < int(s.Len.Value()) {
		tmp532 := ACKRange{}
		tmp530 := tmp532.Read(tmp115)
		if tmp530 != nil {
			return tmp530
		}
		s.Ranges = append(s.Ranges, tmp532)
		tmp322 = tmp322 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamACKPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamACKPacket) DecodeSlice(tmp115 []byte, tmp115Offset *int) error {
	tmp538 := s.LargestAck.DecodeSlice(tmp115, tmp115Offset)
	if tmp538 != nil {
		return tmp538
	}
	tmp536 := s.FirstDelta.DecodeSlice(tmp115, tmp115Offset)
	if tmp536 != nil {
		return tmp536
	}
	tmp534 := s.Len.DecodeSlice(tmp115, tmp115Offset)
	if tmp534 != nil {
		return tmp534
	}
	tmp322 := int(0)
	for tmp322 < int(s.Len.Value()) {
		tmp532 := ACKRange{}
		tmp530 := tmp532.DecodeSlice(tmp115, tmp115Offset)
		if tmp530 != nil {
			return tmp530
		}
		s.Ranges = append(s.Ranges, tmp532)
		tmp322 = tmp322 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamACKPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type UpdateWindow struct {
	Id        Varint
	WindowMax Varint
}

func (u *UpdateWindow) Write(tmp232 io.Writer) error {
	tmp504 := u.Id.Write(tmp232)
	if tmp504 != nil {
		return tmp504
	}
	tmp502 := u.WindowMax.Write(tmp232)
	if tmp502 != nil {
		return tmp502
	}
	return nil
}
func (s *UpdateWindow) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *UpdateWindow) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) EncodeSlice(tmp232 []byte, tmp232Offset *int) error {
	tmp504 := u.Id.EncodeSlice(tmp232, tmp232Offset)
	if tmp504 != nil {
		return tmp504
	}
	tmp502 := u.WindowMax.EncodeSlice(tmp232, tmp232Offset)
	if tmp502 != nil {
		return tmp502
	}
	return nil
}
func (s *UpdateWindow) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *UpdateWindow) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) Append(tmp232 []byte) ([]byte, error) {
	var tmp504 error
	tmp232, tmp504 = u.Id.Append(tmp232)

	if tmp504 != nil {
		return nil, tmp504
	}
	var tmp502 error
	tmp232, tmp502 = u.WindowMax.Append(tmp232)

	if tmp502 != nil {
		return nil, tmp502
	}
	return tmp232, nil
}
func (s *UpdateWindow) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (u *UpdateWindow) Read(tmp234 io.Reader) error {
	tmp509 := u.Id.Read(tmp234)
	if tmp509 != nil {
		return tmp509
	}
	tmp507 := u.WindowMax.Read(tmp234)
	if tmp507 != nil {
		return tmp507
	}
	return nil
}
func (s *UpdateWindow) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *UpdateWindow) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (u *UpdateWindow) DecodeSlice(tmp234 []byte, tmp234Offset *int) error {
	tmp509 := u.Id.DecodeSlice(tmp234, tmp234Offset)
	if tmp509 != nil {
		return tmp509
	}
	tmp507 := u.WindowMax.DecodeSlice(tmp234, tmp234Offset)
	if tmp507 != nil {
		return tmp507
	}
	return nil
}
func (s *UpdateWindow) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *UpdateWindow) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CancelStreamPacket struct {
	Id Varint
}

func (c *CancelStreamPacket) Write(tmp317 io.Writer) error {
	tmp498 := c.Id.Write(tmp317)
	if tmp498 != nil {
		return tmp498
	}
	return nil
}
func (s *CancelStreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CancelStreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) EncodeSlice(tmp317 []byte, tmp317Offset *int) error {
	tmp498 := c.Id.EncodeSlice(tmp317, tmp317Offset)
	if tmp498 != nil {
		return tmp498
	}
	return nil
}
func (s *CancelStreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CancelStreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) Append(tmp317 []byte) ([]byte, error) {
	var tmp498 error
	tmp317, tmp498 = c.Id.Append(tmp317)

	if tmp498 != nil {
		return nil, tmp498
	}
	return tmp317, nil
}
func (s *CancelStreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CancelStreamPacket) Read(tmp318 io.Reader) error {
	tmp500 := c.Id.Read(tmp318)
	if tmp500 != nil {
		return tmp500
	}
	return nil
}
func (s *CancelStreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CancelStreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CancelStreamPacket) DecodeSlice(tmp318 []byte, tmp318Offset *int) error {
	tmp500 := c.Id.DecodeSlice(tmp318, tmp318Offset)
	if tmp500 != nil {
		return tmp500
	}
	return nil
}
func (s *CancelStreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CancelStreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ApplicationPayloadKind uint8

const (
	ApplicationPayloadKind_Ping               ApplicationPayloadKind = 0
	ApplicationPayloadKind_Pong               ApplicationPayloadKind = 1
	ApplicationPayloadKind_StreamData         ApplicationPayloadKind = 2
	ApplicationPayloadKind_StreamCancel       ApplicationPayloadKind = 3
	ApplicationPayloadKind_StreamAck          ApplicationPayloadKind = 4
	ApplicationPayloadKind_StreamWindowUpdate ApplicationPayloadKind = 5
	ApplicationPayloadKind_Pubsub             ApplicationPayloadKind = 6
	ApplicationPayloadKind_TaskControl        ApplicationPayloadKind = 7
	ApplicationPayloadKind_RelayControl       ApplicationPayloadKind = 8
	ApplicationPayloadKind_RunnerControl      ApplicationPayloadKind = 9
	ApplicationPayloadKind_Close              ApplicationPayloadKind = 10
	ApplicationPayloadKind_AgentMessage       ApplicationPayloadKind = 11
	ApplicationPayloadKind_PskAuth            ApplicationPayloadKind = 12
)

func (e ApplicationPayloadKind) String() string {
	switch e {
	case ApplicationPayloadKind_Ping:
		return "Ping"
	case ApplicationPayloadKind_Pong:
		return "Pong"
	case ApplicationPayloadKind_StreamData:
		return "StreamData"
	case ApplicationPayloadKind_StreamCancel:
		return "StreamCancel"
	case ApplicationPayloadKind_StreamAck:
		return "StreamAck"
	case ApplicationPayloadKind_StreamWindowUpdate:
		return "StreamWindowUpdate"
	case ApplicationPayloadKind_Pubsub:
		return "Pubsub"
	case ApplicationPayloadKind_TaskControl:
		return "TaskControl"
	case ApplicationPayloadKind_RelayControl:
		return "RelayControl"
	case ApplicationPayloadKind_RunnerControl:
		return "RunnerControl"
	case ApplicationPayloadKind_Close:
		return "Close"
	case ApplicationPayloadKind_AgentMessage:
		return "AgentMessage"
	case ApplicationPayloadKind_PskAuth:
		return "PskAuth"
	default:
		return fmt.Sprintf("ApplicationPayloadKind(%d)", e)
	}
}

type PacketHeader struct {
	Kind ApplicationPayloadKind
}

func (p *PacketHeader) Write(tmp225 io.Writer) error {
	tmp225ByteIO, _ := tmp225.(io.ByteWriter)
	_ = tmp225ByteIO
	if tmp225ByteIO != nil {
		if err := tmp225ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp225.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp225 []byte, tmp225Offset *int) error {
	tmp324 := []uint8{}
	if len(tmp225)-*tmp225Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp324 = tmp225[*tmp225Offset : *tmp225Offset+int(1)]
	tmp324[0] = uint8(p.Kind)
	*tmp225Offset += int(1)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp225 []byte) ([]byte, error) {
	tmp324 := [1]uint8{}
	tmp324[0] = uint8(p.Kind)
	tmp225 = append(tmp225, tmp324[:1]...)
	return tmp225, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp228 io.Reader) error {
	tmp228ByteIO, _ := tmp228.(io.ByteReader)
	_ = tmp228ByteIO
	tmp494 := uint8(0)
	if tmp228ByteIO != nil {
		var err error
		tmp494, err = tmp228ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp228, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PacketHeader::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp494 = buf[0]
	}
	p.Kind = ApplicationPayloadKind(tmp494)
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp228 []byte, tmp228Offset *int) error {
	tmp494 := uint8(0)
	tmp35 := []uint8{}
	if len(tmp228)-*tmp228Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp35 = tmp228[*tmp228Offset : *tmp228Offset+1]
	*tmp228Offset += int(1)
	tmp494 = tmp35[0]
	p.Kind = ApplicationPayloadKind(tmp494)
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func IsStreamRelated(Kind ApplicationPayloadKind) bool {
	tmp314 := false
	if (((ApplicationPayloadKind_StreamData == Kind) || (ApplicationPayloadKind_StreamCancel == Kind)) || (ApplicationPayloadKind_StreamAck == Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == Kind) {
		tmp314 = true
	} else {
		tmp314 = false
	}
	return tmp314
}

type tmp480 struct {
	StreamData StreamPacket
}

type tmp478 struct {
	StreamCancel CancelStreamPacket
}

type tmp476 struct {
	StreamAck StreamACKPacket
}

type tmp474 struct {
	WindowUpdate UpdateWindow
}

type tmp1045 struct {
}

type Variant85 struct {
	tmp480  tmp480
	tmp478  tmp478
	tmp476  tmp476
	tmp474  tmp474
	tmp1045 tmp1045
}

type StreamAppPacket struct {
	Header PacketHeader
	tmp313 Variant85
}

func (s *StreamAppPacket) StreamAck() *StreamACKPacket {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		return &s.tmp313.tmp476.StreamAck
	}
	return nil
}
func (s *StreamAppPacket) SetStreamAck(tmp404 StreamACKPacket) bool {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		s.tmp313.tmp476.StreamAck = tmp404
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamCancel() *CancelStreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		return &s.tmp313.tmp478.StreamCancel
	}
	return nil
}
func (s *StreamAppPacket) SetStreamCancel(tmp401 CancelStreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		s.tmp313.tmp478.StreamCancel = tmp401
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamData() *StreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return &s.tmp313.tmp480.StreamData
	}
	return nil
}
func (s *StreamAppPacket) SetStreamData(tmp398 StreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		s.tmp313.tmp480.StreamData = tmp398
		return true
	}
	return false
}

func (s *StreamAppPacket) WindowUpdate() *UpdateWindow {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		return &s.tmp313.tmp474.WindowUpdate
	}
	return nil
}
func (s *StreamAppPacket) SetWindowUpdate(tmp387 UpdateWindow) bool {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		s.tmp313.tmp474.WindowUpdate = tmp387
		return true
	}
	return false
}

func (s *StreamAppPacket) Write(tmp106 io.Writer) error {
	tmp106ByteIO, _ := tmp106.(io.ByteWriter)
	_ = tmp106ByteIO
	/* config.go.union("noheap")*/
	tmp433 := s.Header.Write(tmp106)
	if tmp433 != nil {
		return tmp433
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp429 := s.tmp313.tmp480.StreamData.Write(tmp106)
		if tmp429 != nil {
			return tmp429
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp424 := s.tmp313.tmp478.StreamCancel.Write(tmp106)
		if tmp424 != nil {
			return tmp424
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp419 := s.tmp313.tmp476.StreamAck.Write(tmp106)
		if tmp419 != nil {
			return tmp419
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp414 := s.tmp313.tmp474.WindowUpdate.Write(tmp106)
		if tmp414 != nil {
			return tmp414
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamAppPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) EncodeSlice(tmp106 []byte, tmp106Offset *int) error {
	/* config.go.union("noheap")*/
	tmp433 := s.Header.EncodeSlice(tmp106, tmp106Offset)
	if tmp433 != nil {
		return tmp433
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp429 := s.tmp313.tmp480.StreamData.EncodeSlice(tmp106, tmp106Offset)
		if tmp429 != nil {
			return tmp429
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp424 := s.tmp313.tmp478.StreamCancel.EncodeSlice(tmp106, tmp106Offset)
		if tmp424 != nil {
			return tmp424
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp419 := s.tmp313.tmp476.StreamAck.EncodeSlice(tmp106, tmp106Offset)
		if tmp419 != nil {
			return tmp419
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp414 := s.tmp313.tmp474.WindowUpdate.EncodeSlice(tmp106, tmp106Offset)
		if tmp414 != nil {
			return tmp414
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamAppPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) Append(tmp106 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	var tmp433 error
	tmp106, tmp433 = s.Header.Append(tmp106)

	if tmp433 != nil {
		return nil, tmp433
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		var tmp429 error
		tmp106, tmp429 = s.tmp313.tmp480.StreamData.Append(tmp106)

		if tmp429 != nil {
			return nil, tmp429
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		var tmp424 error
		tmp106, tmp424 = s.tmp313.tmp478.StreamCancel.Append(tmp106)

		if tmp424 != nil {
			return nil, tmp424
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		var tmp419 error
		tmp106, tmp419 = s.tmp313.tmp476.StreamAck.Append(tmp106)

		if tmp419 != nil {
			return nil, tmp419
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		var tmp414 error
		tmp106, tmp414 = s.tmp313.tmp474.WindowUpdate.Append(tmp106)

		if tmp414 != nil {
			return nil, tmp414
		}
	} else {
		return nil, errors.New("Unexpected packet")
	}
	return tmp106, nil
}
func (s *StreamAppPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamAppPacket) Read(tmp107 io.Reader) error {
	tmp107ByteIO, _ := tmp107.(io.ByteReader)
	_ = tmp107ByteIO
	/* config.go.union("noheap")*/
	tmp464 := s.Header.Read(tmp107)
	if tmp464 != nil {
		return tmp464
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp459 := s.tmp313.tmp480.StreamData.Read(tmp107)
		if tmp459 != nil {
			return tmp459
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp453 := s.tmp313.tmp478.StreamCancel.Read(tmp107)
		if tmp453 != nil {
			return tmp453
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp447 := s.tmp313.tmp476.StreamAck.Read(tmp107)
		if tmp447 != nil {
			return tmp447
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp441 := s.tmp313.tmp474.WindowUpdate.Read(tmp107)
		if tmp441 != nil {
			return tmp441
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamAppPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamAppPacket) DecodeSlice(tmp107 []byte, tmp107Offset *int) error {
	/* config.go.union("noheap")*/
	tmp464 := s.Header.DecodeSlice(tmp107, tmp107Offset)
	if tmp464 != nil {
		return tmp464
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp459 := s.tmp313.tmp480.StreamData.DecodeSlice(tmp107, tmp107Offset)
		if tmp459 != nil {
			return tmp459
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp453 := s.tmp313.tmp478.StreamCancel.DecodeSlice(tmp107, tmp107Offset)
		if tmp453 != nil {
			return tmp453
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp447 := s.tmp313.tmp476.StreamAck.DecodeSlice(tmp107, tmp107Offset)
		if tmp447 != nil {
			return tmp447
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp441 := s.tmp313.tmp474.WindowUpdate.DecodeSlice(tmp107, tmp107Offset)
		if tmp441 != nil {
			return tmp441
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamAppPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
