// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package wire

import (
	"bytes"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("wire")*/
func (v *Varint) Prefix() uint8 {
	return uint8(((v.tmp176 >> uint64(62)) & uint64(3)))
}

func (v *Varint) SetPrefix(tmp412 uint8) bool {
	v.tmp176 = (v.tmp176 & (^(uint64(3) << uint64(62)))) | ((uint64(tmp412) & uint64(3)) << uint64(62))
	return true
}

func (v *Varint) tmp437() uint64 {
	return uint64(((v.tmp176 >> uint64(0)) & uint64(4611686018427387903)))
}

func (v *Varint) settmp307(tmp441 uint64) bool {
	v.tmp176 = (v.tmp176 & (^(uint64(4611686018427387903) << uint64(0)))) | ((uint64(tmp441) & uint64(4611686018427387903)) << uint64(0))
	return true
}

type Varint struct {
	tmp176 uint64
}

func (v *Varint) Value() uint64 {
	if v.Prefix() == uint8(0) {
		return uint64(uint8(v.tmp437()))
	} else if v.Prefix() == uint8(1) {
		return uint64(uint16(v.tmp437()))
	} else if v.Prefix() == 2 {
		return uint64(uint32(v.tmp437()))
	} else if v.Prefix() == 3 {
		return uint64(uint64(v.tmp437()))
	}
	return uint64(0)
}
func (v *Varint) SetValue(tmp522 uint64) bool {
	if v.Prefix() == uint8(0) {
		v.settmp307(uint64(uint8(tmp522)))
		return true
	} else if v.Prefix() == uint8(1) {
		v.settmp307(uint64(uint16(tmp522)))
		return true
	} else if v.Prefix() == 2 {
		v.settmp307(uint64(uint32(tmp522)))
		return true
	} else if v.Prefix() == 3 {
		v.settmp307(uint64(uint64(tmp522)))
		return true
	}
	return false
}

func (v *Varint) Write(tmp68 io.Writer) error {
	tmp492 := [8]uint8{}
	tmp492[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp492[0] = tmp492[0] | uint8((uint8(v.tmp437()) & 63))
		if _, err := tmp68.Write(tmp492[:1]); err != nil {
			return err
		}
	} else if v.Prefix() == uint8(1) {
		tmp492[0] = tmp492[0] | uint8(((uint16(v.tmp437()) >> uint16(8)) & uint16(63)))
		tmp492[1] = uint8((uint16(v.tmp437()) & uint16(255)))
		if _, err := tmp68.Write(tmp492[:2]); err != nil {
			return err
		}
	} else if v.Prefix() == 2 {
		tmp492[0] = tmp492[0] | uint8(((uint32(v.tmp437()) >> uint32(24)) & uint32(63)))
		tmp492[1] = uint8(((uint32(v.tmp437()) >> uint32(16)) & uint32(255)))
		tmp492[2] = uint8(((uint32(v.tmp437()) >> uint32(8)) & uint32(255)))
		tmp492[3] = uint8((uint32(v.tmp437()) & uint32(255)))
		if _, err := tmp68.Write(tmp492[:4]); err != nil {
			return err
		}
	} else if v.Prefix() == 3 {
		tmp492[0] = tmp492[0] | uint8(((uint64(v.tmp437()) >> uint64(56)) & uint64(63)))
		tmp492[1] = uint8(((uint64(v.tmp437()) >> uint64(48)) & uint64(255)))
		tmp492[2] = uint8(((uint64(v.tmp437()) >> uint64(40)) & uint64(255)))
		tmp492[3] = uint8(((uint64(v.tmp437()) >> uint64(32)) & uint64(255)))
		tmp492[4] = uint8(((uint64(v.tmp437()) >> uint64(24)) & uint64(255)))
		tmp492[5] = uint8(((uint64(v.tmp437()) >> uint64(16)) & uint64(255)))
		tmp492[6] = uint8(((uint64(v.tmp437()) >> uint64(8)) & uint64(255)))
		tmp492[7] = uint8((uint64(v.tmp437()) & uint64(255)))
		if _, err := tmp68.Write(tmp492[:8]); err != nil {
			return err
		}
	}
	return nil
}
func (s *Varint) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Varint) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) EncodeSlice(tmp68 []byte, tmp68Offset *int) error {
	tmp492 := []uint8{}
	if len(tmp68)-*tmp68Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Varint::tmp301::Value\"")
	}
	tmp492 = tmp68[*tmp68Offset : *tmp68Offset+int(1)]
	tmp492[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		if len(tmp68)-*tmp68Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp301::Value\"")
		}
		tmp492 = tmp68[*tmp68Offset : *tmp68Offset+int(1)]
		tmp492[0] = tmp492[0] | uint8((uint8(v.tmp437()) & 63))
		*tmp68Offset += int(1)
	} else if v.Prefix() == uint8(1) {
		if len(tmp68)-*tmp68Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp301::Value\"")
		}
		tmp492 = tmp68[*tmp68Offset : *tmp68Offset+int(2)]
		tmp492[0] = tmp492[0] | uint8(((uint16(v.tmp437()) >> uint16(8)) & uint16(63)))
		tmp492[1] = uint8((uint16(v.tmp437()) & uint16(255)))
		*tmp68Offset += int(2)
	} else if v.Prefix() == 2 {
		if len(tmp68)-*tmp68Offset < int(4) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp301::Value\"")
		}
		tmp492 = tmp68[*tmp68Offset : *tmp68Offset+int(4)]
		tmp492[0] = tmp492[0] | uint8(((uint32(v.tmp437()) >> uint32(24)) & uint32(63)))
		tmp492[1] = uint8(((uint32(v.tmp437()) >> uint32(16)) & uint32(255)))
		tmp492[2] = uint8(((uint32(v.tmp437()) >> uint32(8)) & uint32(255)))
		tmp492[3] = uint8((uint32(v.tmp437()) & uint32(255)))
		*tmp68Offset += int(4)
	} else if v.Prefix() == 3 {
		if len(tmp68)-*tmp68Offset < int(8) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp301::Value\"")
		}
		tmp492 = tmp68[*tmp68Offset : *tmp68Offset+int(8)]
		tmp492[0] = tmp492[0] | uint8(((uint64(v.tmp437()) >> uint64(56)) & uint64(63)))
		tmp492[1] = uint8(((uint64(v.tmp437()) >> uint64(48)) & uint64(255)))
		tmp492[2] = uint8(((uint64(v.tmp437()) >> uint64(40)) & uint64(255)))
		tmp492[3] = uint8(((uint64(v.tmp437()) >> uint64(32)) & uint64(255)))
		tmp492[4] = uint8(((uint64(v.tmp437()) >> uint64(24)) & uint64(255)))
		tmp492[5] = uint8(((uint64(v.tmp437()) >> uint64(16)) & uint64(255)))
		tmp492[6] = uint8(((uint64(v.tmp437()) >> uint64(8)) & uint64(255)))
		tmp492[7] = uint8((uint64(v.tmp437()) & uint64(255)))
		*tmp68Offset += int(8)
	}
	return nil
}
func (s *Varint) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Varint) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) Append(tmp68 []byte) ([]byte, error) {
	tmp492 := [8]uint8{}
	tmp492[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp492[0] = tmp492[0] | uint8((uint8(v.tmp437()) & 63))
		tmp68 = append(tmp68, tmp492[:1]...)
	} else if v.Prefix() == uint8(1) {
		tmp492[0] = tmp492[0] | uint8(((uint16(v.tmp437()) >> uint16(8)) & uint16(63)))
		tmp492[1] = uint8((uint16(v.tmp437()) & uint16(255)))
		tmp68 = append(tmp68, tmp492[:2]...)
	} else if v.Prefix() == 2 {
		tmp492[0] = tmp492[0] | uint8(((uint32(v.tmp437()) >> uint32(24)) & uint32(63)))
		tmp492[1] = uint8(((uint32(v.tmp437()) >> uint32(16)) & uint32(255)))
		tmp492[2] = uint8(((uint32(v.tmp437()) >> uint32(8)) & uint32(255)))
		tmp492[3] = uint8((uint32(v.tmp437()) & uint32(255)))
		tmp68 = append(tmp68, tmp492[:4]...)
	} else if v.Prefix() == 3 {
		tmp492[0] = tmp492[0] | uint8(((uint64(v.tmp437()) >> uint64(56)) & uint64(63)))
		tmp492[1] = uint8(((uint64(v.tmp437()) >> uint64(48)) & uint64(255)))
		tmp492[2] = uint8(((uint64(v.tmp437()) >> uint64(40)) & uint64(255)))
		tmp492[3] = uint8(((uint64(v.tmp437()) >> uint64(32)) & uint64(255)))
		tmp492[4] = uint8(((uint64(v.tmp437()) >> uint64(24)) & uint64(255)))
		tmp492[5] = uint8(((uint64(v.tmp437()) >> uint64(16)) & uint64(255)))
		tmp492[6] = uint8(((uint64(v.tmp437()) >> uint64(8)) & uint64(255)))
		tmp492[7] = uint8((uint64(v.tmp437()) & uint64(255)))
		tmp68 = append(tmp68, tmp492[:8]...)
	}
	return tmp68, nil
}
func (s *Varint) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (v *Varint) Read(tmp14 io.Reader) error {
	tmp449 := [8]uint8{}
	tmp411 := uint8(0)
	if _, err := io.ReadFull(tmp14, tmp449[0:0+1]); err != nil {
		return err
	}
	tmp411 = uint8(((tmp449[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp411)
	if v.Prefix() == uint8(0) {
		tmp438 := uint8(0)
		tmp438 = uint8((tmp449[0] & uint8(63)))
		v.settmp307(uint64(tmp438))
	} else if v.Prefix() == uint8(1) {
		tmp439 := uint16(0)
		if _, err := io.ReadFull(tmp14, tmp449[1:1+1]); err != nil {
			return err
		}
		tmp439 = (uint16((tmp449[0] & uint8(63))) << uint16(8)) | uint16(tmp449[1])
		v.settmp307(uint64(tmp439))
	} else if v.Prefix() == 2 {
		tmp467 := uint32(0)
		if _, err := io.ReadFull(tmp14, tmp449[1:1+3]); err != nil {
			return err
		}
		tmp467 = (((uint32((tmp449[0] & uint8(63))) << uint32(24)) | (uint32(tmp449[1]) << uint32(16))) | (uint32(tmp449[2]) << uint32(8))) | uint32(tmp449[3])
		v.settmp307(uint64(tmp467))
	} else if v.Prefix() == 3 {
		tmp484 := uint64(0)
		if _, err := io.ReadFull(tmp14, tmp449[1:1+7]); err != nil {
			return err
		}
		tmp484 = (((((((uint64((tmp449[0] & uint8(63))) << uint64(56)) | (uint64(tmp449[1]) << uint64(48))) | (uint64(tmp449[2]) << uint64(40))) | (uint64(tmp449[3]) << uint64(32))) | (uint64(tmp449[4]) << uint64(24))) | (uint64(tmp449[5]) << uint64(16))) | (uint64(tmp449[6]) << uint64(8))) | uint64(tmp449[7])
		v.settmp307(uint64(tmp484))
	}
	return nil
}
func (s *Varint) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Varint) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (v *Varint) DecodeSlice(tmp14 []byte, tmp14Offset *int) error {
	tmp449 := []uint8{}
	tmp411 := uint8(0)
	if len(tmp14)-*tmp14Offset < 1 {
		return errors.New("not enough data to read for field \"Varint::Prefix\"")
	}
	tmp449 = tmp14[*tmp14Offset : *tmp14Offset+1]
	*tmp14Offset += int(1)
	tmp411 = uint8(((tmp449[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp411)
	if v.Prefix() == uint8(0) {
		tmp438 := uint8(0)
		tmp438 = uint8((tmp449[0] & uint8(63)))
		v.settmp307(uint64(tmp438))
	} else if v.Prefix() == uint8(1) {
		tmp439 := uint16(0)
		if len(tmp14)-*tmp14Offset < 1 {
			return errors.New("not enough data to read for field \"Varint::tmp301::Value\"")
		}
		tmp449 = tmp449[:1+1]
		*tmp14Offset += int(1)
		tmp439 = (uint16((tmp449[0] & uint8(63))) << uint16(8)) | uint16(tmp449[1])
		v.settmp307(uint64(tmp439))
	} else if v.Prefix() == 2 {
		tmp467 := uint32(0)
		if len(tmp14)-*tmp14Offset < 3 {
			return errors.New("not enough data to read for field \"Varint::tmp301::Value\"")
		}
		tmp449 = tmp449[:1+3]
		*tmp14Offset += int(3)
		tmp467 = (((uint32((tmp449[0] & uint8(63))) << uint32(24)) | (uint32(tmp449[1]) << uint32(16))) | (uint32(tmp449[2]) << uint32(8))) | uint32(tmp449[3])
		v.settmp307(uint64(tmp467))
	} else if v.Prefix() == 3 {
		tmp484 := uint64(0)
		if len(tmp14)-*tmp14Offset < 7 {
			return errors.New("not enough data to read for field \"Varint::tmp301::Value\"")
		}
		tmp449 = tmp449[:1+7]
		*tmp14Offset += int(7)
		tmp484 = (((((((uint64((tmp449[0] & uint8(63))) << uint64(56)) | (uint64(tmp449[1]) << uint64(48))) | (uint64(tmp449[2]) << uint64(40))) | (uint64(tmp449[3]) << uint64(32))) | (uint64(tmp449[4]) << uint64(24))) | (uint64(tmp449[5]) << uint64(16))) | (uint64(tmp449[6]) << uint64(8))) | uint64(tmp449[7])
		v.settmp307(uint64(tmp484))
	}
	return nil
}
func (s *Varint) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Varint) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func VarintLen(Value uint64) uint8 {
	tmp94 := uint8(0)
	if (uint64(0) <= Value) && (Value <= 63) {
		tmp94 = 1
	} else if (uint64(64) <= Value) && (Value <= 16383) {
		tmp94 = 2
	} else if (uint64(16384) <= Value) && (Value <= 1073741823) {
		tmp94 = 4
	} else if (1073741824 <= Value) && (Value <= 70368744177663) {
		tmp94 = 8
	} else {
		tmp94 = 0
	}
	return tmp94
}
func VarintPrefix(Value uint64) uint8 {
	Len := VarintLen(Value)
	tmp149 := uint8(0)
	if Len == uint8(1) {
		tmp149 = 0
	} else if Len == uint8(2) {
		tmp149 = 1
	} else if Len == uint8(4) {
		tmp149 = 2
	} else if Len == uint8(8) {
		tmp149 = 3
	} else {
		tmp149 = 255
	}
	return tmp149
}
func (v *StreamPacket) HasId() bool {
	intVal := v.hasId()
	return intVal != 0
}
func (s *StreamPacket) hasId() uint8 {
	return uint8(((s.tmp48 >> uint8(7)) & uint8(1)))
}

func (s *StreamPacket) SetHasId(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasId(intVal)
}
func (s *StreamPacket) setHasId(tmp429 uint8) bool {
	s.tmp48 = (s.tmp48 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp429) & uint8(1)) << uint8(7))
	return true
}

func (s *StreamPacket) HasOffset() bool {
	intVal := s.hasOffset()
	return intVal != 0
}
func (s *StreamPacket) hasOffset() uint8 {
	return uint8(((s.tmp48 >> uint8(6)) & uint8(1)))
}

func (s *StreamPacket) SetHasOffset(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasOffset(intVal)
}
func (s *StreamPacket) setHasOffset(tmp594 uint8) bool {
	s.tmp48 = (s.tmp48 & (^(uint8(1) << uint8(6)))) | ((uint8(tmp594) & uint8(1)) << uint8(6))
	return true
}

func (s *StreamPacket) IsEof() bool {
	intVal := s.isEof()
	return intVal != 0
}
func (s *StreamPacket) isEof() uint8 {
	return uint8(((s.tmp48 >> uint8(5)) & uint8(1)))
}

func (s *StreamPacket) SetIsEof(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsEof(intVal)
}
func (s *StreamPacket) setIsEof(tmp597 uint8) bool {
	s.tmp48 = (s.tmp48 & (^(uint8(1) << uint8(5)))) | ((uint8(tmp597) & uint8(1)) << uint8(5))
	return true
}

func (s *StreamPacket) IsProbe() bool {
	intVal := s.isProbe()
	return intVal != 0
}
func (s *StreamPacket) isProbe() uint8 {
	return uint8(((s.tmp48 >> uint8(4)) & uint8(1)))
}

func (s *StreamPacket) SetIsProbe(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsProbe(intVal)
}
func (s *StreamPacket) setIsProbe(tmp600 uint8) bool {
	s.tmp48 = (s.tmp48 & (^(uint8(1) << uint8(4)))) | ((uint8(tmp600) & uint8(1)) << uint8(4))
	return true
}

func (s *StreamPacket) Reserved() uint8 {
	return uint8(((s.tmp48 >> uint8(0)) & uint8(15)))
}

func (s *StreamPacket) SetReserved(tmp605 uint8) bool {
	s.tmp48 = (s.tmp48 & (^(uint8(15) << uint8(0)))) | ((uint8(tmp605) & uint8(15)) << uint8(0))
	return true
}

type tmp608 struct {
	Id Varint
}

type Variant226 struct {
	tmp608 tmp608
}

type tmp610 struct {
	Offset Varint
}

type Variant260 struct {
	tmp610 tmp610
}

type StreamPacket struct {
	tmp48  uint8
	tmp369 Variant226
	tmp359 Variant260
	Data   []uint8
}

func (s *StreamPacket) Id() *Varint {
	if s.hasId() == 1 {
		return &s.tmp369.tmp608.Id
	}
	return nil
}
func (s *StreamPacket) SetId(tmp649 Varint) bool {
	if s.hasId() == 1 {
		s.tmp369.tmp608.Id = tmp649
		return true
	}
	return false
}

func (s *StreamPacket) Offset() *Varint {
	if s.hasOffset() == 1 {
		return &s.tmp359.tmp610.Offset
	}
	return nil
}
func (s *StreamPacket) SetOffset(tmp654 Varint) bool {
	if s.hasOffset() == 1 {
		s.tmp359.tmp610.Offset = tmp654
		return true
	}
	return false
}

func (s *StreamPacket) Write(tmp56 io.Writer) error {
	tmp56ByteIO, _ := tmp56.(io.ByteWriter)
	_ = tmp56ByteIO
	/* config.go.union("noheap")*/
	tmp640 := [1]uint8{}
	tmp640[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp640[0] = tmp640[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp640[0] = tmp640[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp640[0] = tmp640[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp640[0] = tmp640[0] | uint8((s.Reserved() & 15))
	if tmp56ByteIO != nil {
		if err := tmp56ByteIO.WriteByte(tmp640[0]); err != nil {
			return err
		}
	} else {
		if _, err := tmp56.Write([]byte{tmp640[0]}); err != nil {
			return err
		}
	}
	if s.hasId() == 1 {
		tmp643 := s.tmp369.tmp608.Id.Write(tmp56)
		if tmp643 != nil {
			return tmp643
		}
	}
	if s.hasOffset() == 1 {
		tmp646 := s.tmp359.tmp610.Offset.Write(tmp56)
		if tmp646 != nil {
			return tmp646
		}
	}
	if _, err := tmp56.Write(s.Data); err != nil {
		return err
	}
	return nil
}
func (s *StreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) EncodeSlice(tmp56 []byte, tmp56Offset *int) error {
	/* config.go.union("noheap")*/
	tmp640 := []uint8{}
	if len(tmp56)-*tmp56Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"StreamPacket::Reserved\"")
	}
	tmp640 = tmp56[*tmp56Offset : *tmp56Offset+int(1)]
	tmp640[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp640[0] = tmp640[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp640[0] = tmp640[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp640[0] = tmp640[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp640[0] = tmp640[0] | uint8((s.Reserved() & 15))
	*tmp56Offset += int(1)
	if s.hasId() == 1 {
		tmp643 := s.tmp369.tmp608.Id.EncodeSlice(tmp56, tmp56Offset)
		if tmp643 != nil {
			return tmp643
		}
	}
	if s.hasOffset() == 1 {
		tmp646 := s.tmp359.tmp610.Offset.EncodeSlice(tmp56, tmp56Offset)
		if tmp646 != nil {
			return tmp646
		}
	}
	if len(tmp56)-*tmp56Offset < int(0+len(s.Data)) {
		return errors.New("not enough space to write for field \"StreamPacket::Data\"")
	}
	copy(tmp56[*tmp56Offset:*tmp56Offset+int(len(s.Data))], s.Data)
	*tmp56Offset += int(len(s.Data))
	return nil
}
func (s *StreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) Append(tmp56 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp640 := [1]uint8{}
	tmp640[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp640[0] = tmp640[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp640[0] = tmp640[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp640[0] = tmp640[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp640[0] = tmp640[0] | uint8((s.Reserved() & 15))
	tmp56 = append(tmp56, tmp640[:1]...)
	if s.hasId() == 1 {
		var tmp643 error
		tmp56, tmp643 = s.tmp369.tmp608.Id.Append(tmp56)

		if tmp643 != nil {
			return nil, tmp643
		}
	}
	if s.hasOffset() == 1 {
		var tmp646 error
		tmp56, tmp646 = s.tmp359.tmp610.Offset.Append(tmp56)

		if tmp646 != nil {
			return nil, tmp646
		}
	}
	tmp56 = append(tmp56, s.Data...)
	return tmp56, nil
}
func (s *StreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamPacket) Read(tmp38 io.Reader) error {
	tmp38ByteIO, _ := tmp38.(io.ByteReader)
	_ = tmp38ByteIO
	/* config.go.union("noheap")*/
	tmp415 := [1]uint8{}
	if tmp38ByteIO != nil {
		var err error
		tmp415[0], err = tmp38ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp38, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"tmp237\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp415[0] = buf[0]
	}
	tmp175 := uint8(0)
	tmp175 = uint8(((tmp415[0] & 128) >> uint8(7)))
	s.setHasId(tmp175)
	tmp531 := uint8(0)
	tmp531 = uint8(((tmp415[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp531)
	tmp526 := uint8(0)
	tmp526 = uint8(((tmp415[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp526)
	tmp620 := uint8(0)
	tmp620 = uint8(((tmp415[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp620)
	tmp623 := uint8(0)
	tmp623 = uint8((tmp415[0] & uint8(15)))
	s.SetReserved(tmp623)
	if s.hasId() == 1 {
		tmp627 := s.tmp369.tmp608.Id.Read(tmp38)
		if tmp627 != nil {
			return tmp627
		}
	}
	if s.hasOffset() == 1 {
		tmp633 := s.tmp359.tmp610.Offset.Read(tmp38)
		if tmp633 != nil {
			return tmp633
		}
	}
	{
		var readErr error
		s.Data, readErr = io.ReadAll(tmp38)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *StreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamPacket) DecodeSlice(tmp38 []byte, tmp38Offset *int) error {
	/* config.go.union("noheap")*/
	tmp415 := []uint8{}
	if len(tmp38)-*tmp38Offset < 1 {
		return errors.New("not enough data to read for field \"tmp237\"")
	}
	tmp415 = tmp38[*tmp38Offset : *tmp38Offset+1]
	*tmp38Offset += int(1)
	tmp175 := uint8(0)
	tmp175 = uint8(((tmp415[0] & 128) >> uint8(7)))
	s.setHasId(tmp175)
	tmp531 := uint8(0)
	tmp531 = uint8(((tmp415[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp531)
	tmp526 := uint8(0)
	tmp526 = uint8(((tmp415[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp526)
	tmp620 := uint8(0)
	tmp620 = uint8(((tmp415[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp620)
	tmp623 := uint8(0)
	tmp623 = uint8((tmp415[0] & uint8(15)))
	s.SetReserved(tmp623)
	if s.hasId() == 1 {
		tmp627 := s.tmp369.tmp608.Id.DecodeSlice(tmp38, tmp38Offset)
		if tmp627 != nil {
			return tmp627
		}
	}
	if s.hasOffset() == 1 {
		tmp633 := s.tmp359.tmp610.Offset.DecodeSlice(tmp38, tmp38Offset)
		if tmp633 != nil {
			return tmp633
		}
	}
	s.Data = tmp38[*tmp38Offset:]
	*tmp38Offset += len(s.Data)
	return nil
}
func (s *StreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ACKRange struct {
	Offset Varint
	Delta  Varint
}

func (a *ACKRange) Write(tmp235 io.Writer) error {
	tmp667 := a.Offset.Write(tmp235)
	if tmp667 != nil {
		return tmp667
	}
	tmp669 := a.Delta.Write(tmp235)
	if tmp669 != nil {
		return tmp669
	}
	return nil
}
func (s *ACKRange) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ACKRange) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) EncodeSlice(tmp235 []byte, tmp235Offset *int) error {
	tmp667 := a.Offset.EncodeSlice(tmp235, tmp235Offset)
	if tmp667 != nil {
		return tmp667
	}
	tmp669 := a.Delta.EncodeSlice(tmp235, tmp235Offset)
	if tmp669 != nil {
		return tmp669
	}
	return nil
}
func (s *ACKRange) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ACKRange) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) Append(tmp235 []byte) ([]byte, error) {
	var tmp667 error
	tmp235, tmp667 = a.Offset.Append(tmp235)

	if tmp667 != nil {
		return nil, tmp667
	}
	var tmp669 error
	tmp235, tmp669 = a.Delta.Append(tmp235)

	if tmp669 != nil {
		return nil, tmp669
	}
	return tmp235, nil
}
func (s *ACKRange) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (a *ACKRange) Read(tmp275 io.Reader) error {
	tmp660 := a.Offset.Read(tmp275)
	if tmp660 != nil {
		return tmp660
	}
	tmp663 := a.Delta.Read(tmp275)
	if tmp663 != nil {
		return tmp663
	}
	return nil
}
func (s *ACKRange) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ACKRange) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (a *ACKRange) DecodeSlice(tmp275 []byte, tmp275Offset *int) error {
	tmp660 := a.Offset.DecodeSlice(tmp275, tmp275Offset)
	if tmp660 != nil {
		return tmp660
	}
	tmp663 := a.Delta.DecodeSlice(tmp275, tmp275Offset)
	if tmp663 != nil {
		return tmp663
	}
	return nil
}
func (s *ACKRange) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ACKRange) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type StreamACKPacket struct {
	LargestAck Varint
	FirstDelta Varint
	Len        Varint
	Ranges     []ACKRange
}

func (s *StreamACKPacket) Write(tmp129 io.Writer) error {
	tmp613 := s.LargestAck.Write(tmp129)
	if tmp613 != nil {
		return tmp613
	}
	tmp677 := s.FirstDelta.Write(tmp129)
	if tmp677 != nil {
		return tmp677
	}
	tmp636 := s.Len.Write(tmp129)
	if tmp636 != nil {
		return tmp636
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp272 := int(0)
	for tmp272 < int(s.Len.Value()) {
		tmp504 := s.Ranges[tmp272].Write(tmp129)
		if tmp504 != nil {
			return tmp504
		}
		tmp272 = tmp272 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamACKPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) EncodeSlice(tmp129 []byte, tmp129Offset *int) error {
	tmp613 := s.LargestAck.EncodeSlice(tmp129, tmp129Offset)
	if tmp613 != nil {
		return tmp613
	}
	tmp677 := s.FirstDelta.EncodeSlice(tmp129, tmp129Offset)
	if tmp677 != nil {
		return tmp677
	}
	tmp636 := s.Len.EncodeSlice(tmp129, tmp129Offset)
	if tmp636 != nil {
		return tmp636
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp272 := int(0)
	for tmp272 < int(s.Len.Value()) {
		tmp504 := s.Ranges[tmp272].EncodeSlice(tmp129, tmp129Offset)
		if tmp504 != nil {
			return tmp504
		}
		tmp272 = tmp272 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamACKPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) Append(tmp129 []byte) ([]byte, error) {
	var tmp613 error
	tmp129, tmp613 = s.LargestAck.Append(tmp129)

	if tmp613 != nil {
		return nil, tmp613
	}
	var tmp677 error
	tmp129, tmp677 = s.FirstDelta.Append(tmp129)

	if tmp677 != nil {
		return nil, tmp677
	}
	var tmp636 error
	tmp129, tmp636 = s.Len.Append(tmp129)

	if tmp636 != nil {
		return nil, tmp636
	}
	if len(s.Ranges) != int(s.Len.Value()) {
		return nil, fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(s.Len.Value()), len(s.Ranges))
	}
	tmp272 := int(0)
	for tmp272 < int(s.Len.Value()) {
		var tmp504 error
		tmp129, tmp504 = s.Ranges[tmp272].Append(tmp129)

		if tmp504 != nil {
			return nil, tmp504
		}
		tmp272 = tmp272 + int(1)
	}
	return tmp129, nil
}
func (s *StreamACKPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamACKPacket) Read(tmp119 io.Reader) error {
	tmp631 := s.LargestAck.Read(tmp119)
	if tmp631 != nil {
		return tmp631
	}
	tmp616 := s.FirstDelta.Read(tmp119)
	if tmp616 != nil {
		return tmp616
	}
	tmp662 := s.Len.Read(tmp119)
	if tmp662 != nil {
		return tmp662
	}
	tmp363 := int(0)
	for tmp363 < int(s.Len.Value()) {
		tmp604 := ACKRange{}
		tmp675 := tmp604.Read(tmp119)
		if tmp675 != nil {
			return tmp675
		}
		s.Ranges = append(s.Ranges, tmp604)
		tmp363 = tmp363 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamACKPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamACKPacket) DecodeSlice(tmp119 []byte, tmp119Offset *int) error {
	tmp631 := s.LargestAck.DecodeSlice(tmp119, tmp119Offset)
	if tmp631 != nil {
		return tmp631
	}
	tmp616 := s.FirstDelta.DecodeSlice(tmp119, tmp119Offset)
	if tmp616 != nil {
		return tmp616
	}
	tmp662 := s.Len.DecodeSlice(tmp119, tmp119Offset)
	if tmp662 != nil {
		return tmp662
	}
	tmp363 := int(0)
	for tmp363 < int(s.Len.Value()) {
		tmp604 := ACKRange{}
		tmp675 := tmp604.DecodeSlice(tmp119, tmp119Offset)
		if tmp675 != nil {
			return tmp675
		}
		s.Ranges = append(s.Ranges, tmp604)
		tmp363 = tmp363 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamACKPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type UpdateWindow struct {
	Id        Varint
	WindowMax Varint
}

func (u *UpdateWindow) Write(tmp232 io.Writer) error {
	tmp685 := u.Id.Write(tmp232)
	if tmp685 != nil {
		return tmp685
	}
	tmp686 := u.WindowMax.Write(tmp232)
	if tmp686 != nil {
		return tmp686
	}
	return nil
}
func (s *UpdateWindow) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *UpdateWindow) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) EncodeSlice(tmp232 []byte, tmp232Offset *int) error {
	tmp685 := u.Id.EncodeSlice(tmp232, tmp232Offset)
	if tmp685 != nil {
		return tmp685
	}
	tmp686 := u.WindowMax.EncodeSlice(tmp232, tmp232Offset)
	if tmp686 != nil {
		return tmp686
	}
	return nil
}
func (s *UpdateWindow) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *UpdateWindow) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) Append(tmp232 []byte) ([]byte, error) {
	var tmp685 error
	tmp232, tmp685 = u.Id.Append(tmp232)

	if tmp685 != nil {
		return nil, tmp685
	}
	var tmp686 error
	tmp232, tmp686 = u.WindowMax.Append(tmp232)

	if tmp686 != nil {
		return nil, tmp686
	}
	return tmp232, nil
}
func (s *UpdateWindow) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (u *UpdateWindow) Read(tmp242 io.Reader) error {
	tmp682 := u.Id.Read(tmp242)
	if tmp682 != nil {
		return tmp682
	}
	tmp683 := u.WindowMax.Read(tmp242)
	if tmp683 != nil {
		return tmp683
	}
	return nil
}
func (s *UpdateWindow) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *UpdateWindow) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (u *UpdateWindow) DecodeSlice(tmp242 []byte, tmp242Offset *int) error {
	tmp682 := u.Id.DecodeSlice(tmp242, tmp242Offset)
	if tmp682 != nil {
		return tmp682
	}
	tmp683 := u.WindowMax.DecodeSlice(tmp242, tmp242Offset)
	if tmp683 != nil {
		return tmp683
	}
	return nil
}
func (s *UpdateWindow) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *UpdateWindow) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CancelStreamPacket struct {
	Id Varint
}

func (c *CancelStreamPacket) Write(tmp335 io.Writer) error {
	tmp690 := c.Id.Write(tmp335)
	if tmp690 != nil {
		return tmp690
	}
	return nil
}
func (s *CancelStreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CancelStreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) EncodeSlice(tmp335 []byte, tmp335Offset *int) error {
	tmp690 := c.Id.EncodeSlice(tmp335, tmp335Offset)
	if tmp690 != nil {
		return tmp690
	}
	return nil
}
func (s *CancelStreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CancelStreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) Append(tmp335 []byte) ([]byte, error) {
	var tmp690 error
	tmp335, tmp690 = c.Id.Append(tmp335)

	if tmp690 != nil {
		return nil, tmp690
	}
	return tmp335, nil
}
func (s *CancelStreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CancelStreamPacket) Read(tmp382 io.Reader) error {
	tmp440 := c.Id.Read(tmp382)
	if tmp440 != nil {
		return tmp440
	}
	return nil
}
func (s *CancelStreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CancelStreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CancelStreamPacket) DecodeSlice(tmp382 []byte, tmp382Offset *int) error {
	tmp440 := c.Id.DecodeSlice(tmp382, tmp382Offset)
	if tmp440 != nil {
		return tmp440
	}
	return nil
}
func (s *CancelStreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CancelStreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ApplicationPayloadKind uint8

const (
	ApplicationPayloadKind_Control            ApplicationPayloadKind = 0
	ApplicationPayloadKind_StreamData         ApplicationPayloadKind = 1
	ApplicationPayloadKind_StreamCancel       ApplicationPayloadKind = 2
	ApplicationPayloadKind_StreamAck          ApplicationPayloadKind = 3
	ApplicationPayloadKind_StreamWindowUpdate ApplicationPayloadKind = 4
)

func (e ApplicationPayloadKind) String() string {
	switch e {
	case ApplicationPayloadKind_Control:
		return "Control"
	case ApplicationPayloadKind_StreamData:
		return "StreamData"
	case ApplicationPayloadKind_StreamCancel:
		return "StreamCancel"
	case ApplicationPayloadKind_StreamAck:
		return "StreamAck"
	case ApplicationPayloadKind_StreamWindowUpdate:
		return "StreamWindowUpdate"
	default:
		return fmt.Sprintf("ApplicationPayloadKind(%d)", e)
	}
}

type PacketHeader struct {
	Kind ApplicationPayloadKind
}

func (p *PacketHeader) Write(tmp236 io.Writer) error {
	tmp236ByteIO, _ := tmp236.(io.ByteWriter)
	_ = tmp236ByteIO
	if tmp236ByteIO != nil {
		if err := tmp236ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp236.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp236 []byte, tmp236Offset *int) error {
	tmp373 := []uint8{}
	if len(tmp236)-*tmp236Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp373 = tmp236[*tmp236Offset : *tmp236Offset+int(1)]
	tmp373[0] = uint8(p.Kind)
	*tmp236Offset += int(1)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp236 []byte) ([]byte, error) {
	tmp373 := [1]uint8{}
	tmp373[0] = uint8(p.Kind)
	tmp236 = append(tmp236, tmp373[:1]...)
	return tmp236, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp234 io.Reader) error {
	tmp234ByteIO, _ := tmp234.(io.ByteReader)
	_ = tmp234ByteIO
	tmp595 := uint8(0)
	if tmp234ByteIO != nil {
		var err error
		tmp595, err = tmp234ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp234, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PacketHeader::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp595 = buf[0]
	}
	p.Kind = ApplicationPayloadKind(tmp595)
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp234 []byte, tmp234Offset *int) error {
	tmp595 := uint8(0)
	tmp35 := []uint8{}
	if len(tmp234)-*tmp234Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp35 = tmp234[*tmp234Offset : *tmp234Offset+1]
	*tmp234Offset += int(1)
	tmp595 = tmp35[0]
	p.Kind = ApplicationPayloadKind(tmp595)
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func IsStreamRelated(Kind ApplicationPayloadKind) bool {
	tmp350 := false
	if (((ApplicationPayloadKind_StreamData == Kind) || (ApplicationPayloadKind_StreamCancel == Kind)) || (ApplicationPayloadKind_StreamAck == Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == Kind) {
		tmp350 = true
	} else {
		tmp350 = false
	}
	return tmp350
}

type tmp706 struct {
	Control []uint8
}

type tmp708 struct {
	StreamData StreamPacket
}

type tmp710 struct {
	StreamCancel CancelStreamPacket
}

type tmp711 struct {
	StreamAck StreamACKPacket
}

type tmp712 struct {
	WindowUpdate UpdateWindow
}

type tmp2041 struct {
}

type Variant81 struct {
	tmp706  tmp706
	tmp708  tmp708
	tmp710  tmp710
	tmp711  tmp711
	tmp712  tmp712
	tmp2041 tmp2041
}

type AppPacket struct {
	Header PacketHeader
	tmp326 Variant81
}

func (a *AppPacket) Control() *[]uint8 {
	if a.Header.Kind == ApplicationPayloadKind_Control {
		return &a.tmp326.tmp706.Control
	}
	return nil
}
func (a *AppPacket) SetControl(tmp688 []uint8) bool {
	if a.Header.Kind == ApplicationPayloadKind_Control {
		a.tmp326.tmp706.Control = tmp688
		return true
	}
	return false
}

func (a *AppPacket) StreamAck() *StreamACKPacket {
	if ((ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind)) || (ApplicationPayloadKind_StreamCancel == a.Header.Kind) {
		return nil
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		return &a.tmp326.tmp711.StreamAck
	}
	return nil
}
func (a *AppPacket) SetStreamAck(tmp748 StreamACKPacket) bool {
	if ((ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind)) || (ApplicationPayloadKind_StreamCancel == a.Header.Kind) {
		return false
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		a.tmp326.tmp711.StreamAck = tmp748
		return true
	}
	return false
}

func (a *AppPacket) StreamCancel() *CancelStreamPacket {
	if (ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind) {
		return nil
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		return &a.tmp326.tmp710.StreamCancel
	}
	return nil
}
func (a *AppPacket) SetStreamCancel(tmp751 CancelStreamPacket) bool {
	if (ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind) {
		return false
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		a.tmp326.tmp710.StreamCancel = tmp751
		return true
	}
	return false
}

func (a *AppPacket) StreamData() *StreamPacket {
	if a.Header.Kind == ApplicationPayloadKind_Control {
		return nil
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		return &a.tmp326.tmp708.StreamData
	}
	return nil
}
func (a *AppPacket) SetStreamData(tmp754 StreamPacket) bool {
	if a.Header.Kind == ApplicationPayloadKind_Control {
		return false
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		a.tmp326.tmp708.StreamData = tmp754
		return true
	}
	return false
}

func (a *AppPacket) WindowUpdate() *UpdateWindow {
	if (((ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind)) || (ApplicationPayloadKind_StreamCancel == a.Header.Kind)) || (ApplicationPayloadKind_StreamAck == a.Header.Kind) {
		return nil
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		return &a.tmp326.tmp712.WindowUpdate
	}
	return nil
}
func (a *AppPacket) SetWindowUpdate(tmp761 UpdateWindow) bool {
	if (((ApplicationPayloadKind_Control == a.Header.Kind) || (ApplicationPayloadKind_StreamData == a.Header.Kind)) || (ApplicationPayloadKind_StreamCancel == a.Header.Kind)) || (ApplicationPayloadKind_StreamAck == a.Header.Kind) {
		return false
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		a.tmp326.tmp712.WindowUpdate = tmp761
		return true
	}
	return false
}

func (a *AppPacket) Write(tmp104 io.Writer) error {
	tmp104ByteIO, _ := tmp104.(io.ByteWriter)
	_ = tmp104ByteIO
	/* config.go.union("noheap")*/
	tmp731 := a.Header.Write(tmp104)
	if tmp731 != nil {
		return tmp731
	}
	if a.Header.Kind == ApplicationPayloadKind_Control {
		if _, err := tmp104.Write(a.tmp326.tmp706.Control); err != nil {
			return err
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp612 := a.tmp326.tmp708.StreamData.Write(tmp104)
		if tmp612 != nil {
			return tmp612
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp737 := a.tmp326.tmp710.StreamCancel.Write(tmp104)
		if tmp737 != nil {
			return tmp737
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp588 := a.tmp326.tmp711.StreamAck.Write(tmp104)
		if tmp588 != nil {
			return tmp588
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp700 := a.tmp326.tmp712.WindowUpdate.Write(tmp104)
		if tmp700 != nil {
			return tmp700
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *AppPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *AppPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *AppPacket) EncodeSlice(tmp104 []byte, tmp104Offset *int) error {
	/* config.go.union("noheap")*/
	tmp731 := a.Header.EncodeSlice(tmp104, tmp104Offset)
	if tmp731 != nil {
		return tmp731
	}
	if a.Header.Kind == ApplicationPayloadKind_Control {
		if len(tmp104)-*tmp104Offset < int(0+len(a.tmp326.tmp706.Control)) {
			return errors.New("not enough space to write for field \"AppPacket::tmp326::Control\"")
		}
		copy(tmp104[*tmp104Offset:*tmp104Offset+int(len(a.tmp326.tmp706.Control))], a.tmp326.tmp706.Control)
		*tmp104Offset += int(len(a.tmp326.tmp706.Control))
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp612 := a.tmp326.tmp708.StreamData.EncodeSlice(tmp104, tmp104Offset)
		if tmp612 != nil {
			return tmp612
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp737 := a.tmp326.tmp710.StreamCancel.EncodeSlice(tmp104, tmp104Offset)
		if tmp737 != nil {
			return tmp737
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp588 := a.tmp326.tmp711.StreamAck.EncodeSlice(tmp104, tmp104Offset)
		if tmp588 != nil {
			return tmp588
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp700 := a.tmp326.tmp712.WindowUpdate.EncodeSlice(tmp104, tmp104Offset)
		if tmp700 != nil {
			return tmp700
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *AppPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *AppPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *AppPacket) Append(tmp104 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	var tmp731 error
	tmp104, tmp731 = a.Header.Append(tmp104)

	if tmp731 != nil {
		return nil, tmp731
	}
	if a.Header.Kind == ApplicationPayloadKind_Control {
		tmp104 = append(tmp104, a.tmp326.tmp706.Control...)
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		var tmp612 error
		tmp104, tmp612 = a.tmp326.tmp708.StreamData.Append(tmp104)

		if tmp612 != nil {
			return nil, tmp612
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		var tmp737 error
		tmp104, tmp737 = a.tmp326.tmp710.StreamCancel.Append(tmp104)

		if tmp737 != nil {
			return nil, tmp737
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		var tmp588 error
		tmp104, tmp588 = a.tmp326.tmp711.StreamAck.Append(tmp104)

		if tmp588 != nil {
			return nil, tmp588
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		var tmp700 error
		tmp104, tmp700 = a.tmp326.tmp712.WindowUpdate.Append(tmp104)

		if tmp700 != nil {
			return nil, tmp700
		}
	} else {
		return nil, errors.New("Unexpected packet")
	}
	return tmp104, nil
}
func (s *AppPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (a *AppPacket) Read(tmp80 io.Reader) error {
	tmp80ByteIO, _ := tmp80.(io.ByteReader)
	_ = tmp80ByteIO
	/* config.go.union("noheap")*/
	tmp715 := a.Header.Read(tmp80)
	if tmp715 != nil {
		return tmp715
	}
	if a.Header.Kind == ApplicationPayloadKind_Control {
		{
			var readErr error
			a.tmp326.tmp706.Control, readErr = io.ReadAll(tmp80)
			if readErr != nil {
				return readErr
			}
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp552 := a.tmp326.tmp708.StreamData.Read(tmp80)
		if tmp552 != nil {
			return tmp552
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp723 := a.tmp326.tmp710.StreamCancel.Read(tmp80)
		if tmp723 != nil {
			return tmp723
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp705 := a.tmp326.tmp711.StreamAck.Read(tmp80)
		if tmp705 != nil {
			return tmp705
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp611 := a.tmp326.tmp712.WindowUpdate.Read(tmp80)
		if tmp611 != nil {
			return tmp611
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *AppPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *AppPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (a *AppPacket) DecodeSlice(tmp80 []byte, tmp80Offset *int) error {
	/* config.go.union("noheap")*/
	tmp715 := a.Header.DecodeSlice(tmp80, tmp80Offset)
	if tmp715 != nil {
		return tmp715
	}
	if a.Header.Kind == ApplicationPayloadKind_Control {
		a.tmp326.tmp706.Control = tmp80[*tmp80Offset:]
		*tmp80Offset += len(a.tmp326.tmp706.Control)
	} else if a.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp552 := a.tmp326.tmp708.StreamData.DecodeSlice(tmp80, tmp80Offset)
		if tmp552 != nil {
			return tmp552
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp723 := a.tmp326.tmp710.StreamCancel.DecodeSlice(tmp80, tmp80Offset)
		if tmp723 != nil {
			return tmp723
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp705 := a.tmp326.tmp711.StreamAck.DecodeSlice(tmp80, tmp80Offset)
		if tmp705 != nil {
			return tmp705
		}
	} else if a.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp611 := a.tmp326.tmp712.WindowUpdate.DecodeSlice(tmp80, tmp80Offset)
		if tmp611 != nil {
			return tmp611
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *AppPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *AppPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
