// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package packet

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("packet")*/
type IPAddress struct {
	Len     uint8
	Address []uint8
}

func (i *IPAddress) SetAddress(tmp371 []uint8) bool {
	if len(tmp371) > int(255) {
		return false
	}
	i.Len = uint8(len(tmp371))
	i.Address = tmp371
	return true
}

func (i *IPAddress) Write(tmp176 io.Writer) error {
	tmp176ByteIO, _ := tmp176.(io.ByteWriter)
	_ = tmp176ByteIO
	if tmp176ByteIO != nil {
		if err := tmp176ByteIO.WriteByte(i.Len); err != nil {
			return err
		}
	} else {
		if _, err := tmp176.Write([]byte{i.Len}); err != nil {
			return err
		}
	}
	if !((i.Len == 4) || (i.Len == 6)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	if _, err := tmp176.Write(i.Address); err != nil {
		return err
	}
	return nil
}
func (s *IPAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *IPAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) EncodeSlice(tmp176 []byte, tmp176Offset *int) error {
	tmp175 := []uint8{}
	if len(tmp176)-*tmp176Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"IPAddress::Len\"")
	}
	tmp175 = tmp176[*tmp176Offset : *tmp176Offset+int(1)]
	tmp175[0] = i.Len
	*tmp176Offset += int(1)
	if !((i.Len == 4) || (i.Len == 6)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	if len(tmp176)-*tmp176Offset < int(0+i.Len) {
		return errors.New("not enough space to write for field \"IPAddress::Address\"")
	}
	copy(tmp176[*tmp176Offset:*tmp176Offset+int(i.Len)], i.Address)
	*tmp176Offset += int(i.Len)
	return nil
}
func (s *IPAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *IPAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) Append(tmp176 []byte) ([]byte, error) {
	tmp175 := [1]uint8{}
	tmp175[0] = i.Len
	tmp176 = append(tmp176, tmp175[:1]...)
	if !((i.Len == 4) || (i.Len == 6)) {
		return nil, errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	tmp176 = append(tmp176, i.Address...)
	return tmp176, nil
}
func (s *IPAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (i *IPAddress) Read(tmp184 io.Reader) error {
	tmp184ByteIO, _ := tmp184.(io.ByteReader)
	_ = tmp184ByteIO
	if tmp184ByteIO != nil {
		var err error
		i.Len, err = tmp184ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp184, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"IPAddress::Len\": expected to read 1 byte, but read %d bytes", n)
		}
		i.Len = buf[0]
	}
	if !((i.Len == 4) || (i.Len == 6)) {
		return errors.New("Assertion failed")
	}
	if seeker, ok := tmp184.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(i.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(i.Len)))
		}
		i.Address = make([]byte, int(i.Len))
		if _, err := io.ReadFull(tmp184, i.Address[0:0+int(i.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1141 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1141, tmp184, int64(int(i.Len))); err != nil {
			return err
		}
		i.Address = io_temp_1141.Bytes()
	}
	return nil
}
func (s *IPAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *IPAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (i *IPAddress) DecodeSlice(tmp184 []byte, tmp184Offset *int) error {
	tmp28 := []uint8{}
	if len(tmp184)-*tmp184Offset < 1 {
		return errors.New("not enough data to read for field \"IPAddress::Len\"")
	}
	tmp28 = tmp184[*tmp184Offset : *tmp184Offset+1]
	*tmp184Offset += int(1)
	i.Len = tmp28[0]
	if !((i.Len == 4) || (i.Len == 6)) {
		return errors.New("Assertion failed")
	}
	if len(tmp184)-*tmp184Offset < int(i.Len) {
		return errors.New("not enough data to read for field \"IPAddress::Address\"")
	}
	i.Address = tmp184[*tmp184Offset : *tmp184Offset+int(i.Len)]
	*tmp184Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *IPAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type MacAddress struct {
	Address [6]uint8
}

func (m *MacAddress) Write(tmp343 io.Writer) error {
	if _, err := tmp343.Write(m.Address[:6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *MacAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) EncodeSlice(tmp343 []byte, tmp343Offset *int) error {
	if len(tmp343)-*tmp343Offset < int(6) {
		return errors.New("not enough space to write for field \"MacAddress::Address\"")
	}
	copy(tmp343[*tmp343Offset:*tmp343Offset+int(6)], m.Address[:])
	*tmp343Offset += int(6)
	return nil
}
func (s *MacAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *MacAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) Append(tmp343 []byte) ([]byte, error) {
	tmp343 = append(tmp343, m.Address[:6]...)
	return tmp343, nil
}
func (s *MacAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (m *MacAddress) Read(tmp347 io.Reader) error {
	if _, err := io.ReadFull(tmp347, m.Address[0:0+6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *MacAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (m *MacAddress) DecodeSlice(tmp347 []byte, tmp347Offset *int) error {
	if len(tmp347)-*tmp347Offset < 6 {
		return errors.New("not enough data to read for field \"MacAddress::Address\"")
	}
	copy(m.Address[:], tmp347[*tmp347Offset:*tmp347Offset+6])
	*tmp347Offset += int(6)
	return nil
}
func (s *MacAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *MacAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Probe struct {
	MacAddress MacAddress
	IpAddress  IPAddress
	Port       uint16
}

func (p *Probe) Write(tmp95 io.Writer) error {
	tmp333 := p.MacAddress.Write(tmp95)
	if tmp333 != nil {
		return tmp333
	}
	tmp330 := p.IpAddress.Write(tmp95)
	if tmp330 != nil {
		return tmp330
	}
	tmp51 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	if _, err := tmp95.Write(tmp51[:2]); err != nil {
		return err
	}
	return nil
}
func (s *Probe) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Probe) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) EncodeSlice(tmp95 []byte, tmp95Offset *int) error {
	tmp333 := p.MacAddress.EncodeSlice(tmp95, tmp95Offset)
	if tmp333 != nil {
		return tmp333
	}
	tmp330 := p.IpAddress.EncodeSlice(tmp95, tmp95Offset)
	if tmp330 != nil {
		return tmp330
	}
	tmp51 := []uint8{}
	if len(tmp95)-*tmp95Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Probe::Port\"")
	}
	tmp51 = tmp95[*tmp95Offset : *tmp95Offset+int(2)]
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	*tmp95Offset += int(2)
	return nil
}
func (s *Probe) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Probe) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) Append(tmp95 []byte) ([]byte, error) {
	var tmp333 error
	tmp95, tmp333 = p.MacAddress.Append(tmp95)

	if tmp333 != nil {
		return nil, tmp333
	}
	var tmp330 error
	tmp95, tmp330 = p.IpAddress.Append(tmp95)

	if tmp330 != nil {
		return nil, tmp330
	}
	tmp51 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	tmp95 = append(tmp95, tmp51[:2]...)
	return tmp95, nil
}
func (s *Probe) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Probe) Read(tmp98 io.Reader) error {
	tmp364 := p.MacAddress.Read(tmp98)
	if tmp364 != nil {
		return tmp364
	}
	tmp355 := p.IpAddress.Read(tmp98)
	if tmp355 != nil {
		return tmp355
	}
	tmp59 := [2]uint8{}
	if _, err := io.ReadFull(tmp98, tmp59[0:0+2]); err != nil {
		return err
	}
	p.Port = binary.BigEndian.Uint16(tmp59[:])
	return nil
}
func (s *Probe) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Probe) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Probe) DecodeSlice(tmp98 []byte, tmp98Offset *int) error {
	tmp364 := p.MacAddress.DecodeSlice(tmp98, tmp98Offset)
	if tmp364 != nil {
		return tmp364
	}
	tmp355 := p.IpAddress.DecodeSlice(tmp98, tmp98Offset)
	if tmp355 != nil {
		return tmp355
	}
	tmp59 := []uint8{}
	if len(tmp98)-*tmp98Offset < 2 {
		return errors.New("not enough data to read for field \"Probe::Port\"")
	}
	tmp59 = tmp98[*tmp98Offset : *tmp98Offset+2]
	*tmp98Offset += int(2)
	p.Port = binary.BigEndian.Uint16(tmp59[:])
	return nil
}
func (s *Probe) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Probe) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type KeyKind uint16

const (
	KeyKind_Offset KeyKind = 24
	KeyKind_X25519 KeyKind = 52
	KeyKind_P256   KeyKind = 249
	KeyKind_P384   KeyKind = 36
	KeyKind_P521   KeyKind = 51
)

func (e KeyKind) String() string {
	switch e {
	case KeyKind_Offset:
		return "Offset"
	case KeyKind_X25519:
		return "X25519"
	case KeyKind_P256:
		return "P256"
	case KeyKind_P384:
		return "P384"
	case KeyKind_P521:
		return "P521"
	default:
		return fmt.Sprintf("KeyKind(%d)", e)
	}
}

type CommonKeyKind uint16

const (
	CommonKeyKind_Aes128Gcm        CommonKeyKind = 115
	CommonKeyKind_Aes192Gcm        CommonKeyKind = 67
	CommonKeyKind_Aes256Gcm        CommonKeyKind = 34
	CommonKeyKind_Chacha20Poly1305 CommonKeyKind = 62
)

func (e CommonKeyKind) String() string {
	switch e {
	case CommonKeyKind_Aes128Gcm:
		return "Aes128Gcm"
	case CommonKeyKind_Aes192Gcm:
		return "Aes192Gcm"
	case CommonKeyKind_Aes256Gcm:
		return "Aes256Gcm"
	case CommonKeyKind_Chacha20Poly1305:
		return "Chacha20Poly1305"
	default:
		return fmt.Sprintf("CommonKeyKind(%d)", e)
	}
}

type PacketKind uint8

const (
	PacketKind_Handshake    PacketKind = 94
	PacketKind_HandshakeAck PacketKind = 137
	PacketKind_Application  PacketKind = 51
	PacketKind_Probe        PacketKind = 103
)

func (e PacketKind) String() string {
	switch e {
	case PacketKind_Handshake:
		return "Handshake"
	case PacketKind_HandshakeAck:
		return "HandshakeAck"
	case PacketKind_Application:
		return "Application"
	case PacketKind_Probe:
		return "Probe"
	default:
		return fmt.Sprintf("PacketKind(%d)", e)
	}
}

type tmp325 struct {
	Offset uint16
}

func (v *tmp325) isVariant163() {}

type Variant163 interface {
	isVariant163()
}

type Handshake struct {
	KeyKind       KeyKind
	CommonKeyKind CommonKeyKind
	tmp213        Variant163
	Len           uint16
	KeyShare      []uint8
}

func (h *Handshake) Offset() *uint16 {
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			return nil
		}
		_ = tmp324 // to prevent unused warnings
		return &tmp324.Offset
	}
	return nil
}
func (h *Handshake) SetOffset(tmp315 uint16) bool {
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp213 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp324.Offset = tmp315
		return true
	}
	return false
}

func (h *Handshake) SetKeyShare(tmp312 []uint8) bool {
	if len(tmp312) > int(65535) {
		return false
	}
	h.Len = uint16(len(tmp312))
	h.KeyShare = tmp312
	return true
}

func (h *Handshake) Write(tmp23 io.Writer) error {
	tmp321 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp321[:], uint16(uint16(h.KeyKind)))
	if _, err := tmp23.Write(tmp321[:2]); err != nil {
		return err
	}
	tmp317 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp317[:], uint16(uint16(h.CommonKeyKind)))
	if _, err := tmp23.Write(tmp317[:2]); err != nil {
		return err
	}
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp370 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp370[:], uint16(tmp324.Offset))
		if _, err := tmp23.Write(tmp370[:2]); err != nil {
			return err
		}
	}
	tmp311 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp311[:], uint16(h.Len))
	if _, err := tmp23.Write(tmp311[:2]); err != nil {
		return err
	}
	if len(h.KeyShare) != int(h.Len) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	if _, err := tmp23.Write(h.KeyShare); err != nil {
		return err
	}
	return nil
}
func (s *Handshake) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Handshake) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) EncodeSlice(tmp23 []byte, tmp23Offset *int) error {
	tmp321 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::KeyKind\"")
	}
	tmp321 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp321[:], uint16(uint16(h.KeyKind)))
	*tmp23Offset += int(2)
	tmp317 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::CommonKeyKind\"")
	}
	tmp317 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp317[:], uint16(uint16(h.CommonKeyKind)))
	*tmp23Offset += int(2)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp370 := []uint8{}
		if len(tmp23)-*tmp23Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Handshake::tmp213::Offset\"")
		}
		tmp370 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
		binary.BigEndian.PutUint16(tmp370[:], uint16(tmp324.Offset))
		*tmp23Offset += int(2)
	}
	tmp311 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::Len\"")
	}
	tmp311 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp311[:], uint16(h.Len))
	*tmp23Offset += int(2)
	if len(h.KeyShare) != int(h.Len) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	if len(tmp23)-*tmp23Offset < int(0+h.Len) {
		return errors.New("not enough space to write for field \"Handshake::KeyShare\"")
	}
	copy(tmp23[*tmp23Offset:*tmp23Offset+int(h.Len)], h.KeyShare)
	*tmp23Offset += int(h.Len)
	return nil
}
func (s *Handshake) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Handshake) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) Append(tmp23 []byte) ([]byte, error) {
	tmp321 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp321[:], uint16(uint16(h.KeyKind)))
	tmp23 = append(tmp23, tmp321[:2]...)
	tmp317 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp317[:], uint16(uint16(h.CommonKeyKind)))
	tmp23 = append(tmp23, tmp317[:2]...)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp370 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp370[:], uint16(tmp324.Offset))
		tmp23 = append(tmp23, tmp370[:2]...)
	}
	tmp311 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp311[:], uint16(h.Len))
	tmp23 = append(tmp23, tmp311[:2]...)
	if len(h.KeyShare) != int(h.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	tmp23 = append(tmp23, h.KeyShare...)
	return tmp23, nil
}
func (s *Handshake) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (h *Handshake) Read(tmp24 io.Reader) error {
	tmp223 := uint16(0)
	tmp374 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp374[0:0+2]); err != nil {
		return err
	}
	tmp223 = binary.BigEndian.Uint16(tmp374[:])
	h.KeyKind = KeyKind(tmp223)
	tmp352 := uint16(0)
	tmp351 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp351[0:0+2]); err != nil {
		return err
	}
	tmp352 = binary.BigEndian.Uint16(tmp351[:])
	h.CommonKeyKind = CommonKeyKind(tmp352)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp213 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp346 := [2]uint8{}
		if _, err := io.ReadFull(tmp24, tmp346[0:0+2]); err != nil {
			return err
		}
		tmp324.Offset = binary.BigEndian.Uint16(tmp346[:])
	}
	tmp319 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp319[0:0+2]); err != nil {
		return err
	}
	h.Len = binary.BigEndian.Uint16(tmp319[:])
	if seeker, ok := tmp24.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(h.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(h.Len)))
		}
		h.KeyShare = make([]byte, int(h.Len))
		if _, err := io.ReadFull(tmp24, h.KeyShare[0:0+int(h.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_894 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_894, tmp24, int64(int(h.Len))); err != nil {
			return err
		}
		h.KeyShare = io_temp_894.Bytes()
	}
	return nil
}
func (s *Handshake) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Handshake) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (h *Handshake) DecodeSlice(tmp24 []byte, tmp24Offset *int) error {
	tmp223 := uint16(0)
	tmp374 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::KeyKind\"")
	}
	tmp374 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	tmp223 = binary.BigEndian.Uint16(tmp374[:])
	h.KeyKind = KeyKind(tmp223)
	tmp352 := uint16(0)
	tmp351 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::CommonKeyKind\"")
	}
	tmp351 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	tmp352 = binary.BigEndian.Uint16(tmp351[:])
	h.CommonKeyKind = CommonKeyKind(tmp352)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp213.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp213 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp346 := []uint8{}
		if len(tmp24)-*tmp24Offset < 2 {
			return errors.New("not enough data to read for field \"Handshake::tmp213::Offset\"")
		}
		tmp346 = tmp24[*tmp24Offset : *tmp24Offset+2]
		*tmp24Offset += int(2)
		tmp324.Offset = binary.BigEndian.Uint16(tmp346[:])
	}
	tmp319 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::Len\"")
	}
	tmp319 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	h.Len = binary.BigEndian.Uint16(tmp319[:])
	if len(tmp24)-*tmp24Offset < int(h.Len) {
		return errors.New("not enough data to read for field \"Handshake::KeyShare\"")
	}
	h.KeyShare = tmp24[*tmp24Offset : *tmp24Offset+int(h.Len)]
	*tmp24Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Handshake) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type PacketHeader struct {
	Version      uint8
	Kind         PacketKind
	ConnectionId uint16
	Len          uint16
}

func (p *PacketHeader) Write(tmp30 io.Writer) error {
	tmp296 := [1]uint8{}
	tmp296[0] = p.Version
	if _, err := tmp30.Write(tmp296[:1]); err != nil {
		return err
	}
	tmp292 := [1]uint8{}
	tmp292[0] = uint8(p.Kind)
	if _, err := tmp30.Write(tmp292[:1]); err != nil {
		return err
	}
	tmp289 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp289[:], uint16(p.ConnectionId))
	if _, err := tmp30.Write(tmp289[:2]); err != nil {
		return err
	}
	tmp287 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.Len))
	if _, err := tmp30.Write(tmp287[:2]); err != nil {
		return err
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp30 []byte, tmp30Offset *int) error {
	tmp296 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Version\"")
	}
	tmp296 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp296[0] = p.Version
	*tmp30Offset += int(1)
	tmp292 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp292 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp292[0] = uint8(p.Kind)
	*tmp30Offset += int(1)
	tmp289 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::ConnectionId\"")
	}
	tmp289 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp289[:], uint16(p.ConnectionId))
	*tmp30Offset += int(2)
	tmp287 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Len\"")
	}
	tmp287 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.Len))
	*tmp30Offset += int(2)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp30 []byte) ([]byte, error) {
	tmp296 := [1]uint8{}
	tmp296[0] = p.Version
	tmp30 = append(tmp30, tmp296[:1]...)
	tmp292 := [1]uint8{}
	tmp292[0] = uint8(p.Kind)
	tmp30 = append(tmp30, tmp292[:1]...)
	tmp289 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp289[:], uint16(p.ConnectionId))
	tmp30 = append(tmp30, tmp289[:2]...)
	tmp287 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.Len))
	tmp30 = append(tmp30, tmp287[:2]...)
	return tmp30, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp31 io.Reader) error {
	tmp304 := [1]uint8{}
	if _, err := io.ReadFull(tmp31, tmp304[0:0+1]); err != nil {
		return err
	}
	p.Version = tmp304[0]
	tmp302 := uint8(0)
	tmp301 := [1]uint8{}
	if _, err := io.ReadFull(tmp31, tmp301[0:0+1]); err != nil {
		return err
	}
	tmp302 = tmp301[0]
	p.Kind = PacketKind(tmp302)
	tmp299 := [2]uint8{}
	if _, err := io.ReadFull(tmp31, tmp299[0:0+2]); err != nil {
		return err
	}
	p.ConnectionId = binary.BigEndian.Uint16(tmp299[:])
	tmp298 := [2]uint8{}
	if _, err := io.ReadFull(tmp31, tmp298[0:0+2]); err != nil {
		return err
	}
	p.Len = binary.BigEndian.Uint16(tmp298[:])
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp31 []byte, tmp31Offset *int) error {
	tmp304 := []uint8{}
	if len(tmp31)-*tmp31Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Version\"")
	}
	tmp304 = tmp31[*tmp31Offset : *tmp31Offset+1]
	*tmp31Offset += int(1)
	p.Version = tmp304[0]
	tmp302 := uint8(0)
	tmp301 := []uint8{}
	if len(tmp31)-*tmp31Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp301 = tmp31[*tmp31Offset : *tmp31Offset+1]
	*tmp31Offset += int(1)
	tmp302 = tmp301[0]
	p.Kind = PacketKind(tmp302)
	tmp299 := []uint8{}
	if len(tmp31)-*tmp31Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::ConnectionId\"")
	}
	tmp299 = tmp31[*tmp31Offset : *tmp31Offset+2]
	*tmp31Offset += int(2)
	p.ConnectionId = binary.BigEndian.Uint16(tmp299[:])
	tmp298 := []uint8{}
	if len(tmp31)-*tmp31Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::Len\"")
	}
	tmp298 = tmp31[*tmp31Offset : *tmp31Offset+2]
	*tmp31Offset += int(2)
	p.Len = binary.BigEndian.Uint16(tmp298[:])
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (p *ProtectedHeader) RawPayload() bool {
	intVal := p.rawPayload()
	return intVal != 0
}
func (p *ProtectedHeader) rawPayload() uint8 {
	return uint8(((p.tmp69 >> uint64(63)) & uint64(1)))
}

func (p *ProtectedHeader) SetRawPayload(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setRawPayload(intVal)
}
func (p *ProtectedHeader) setRawPayload(tmp326 uint8) bool {
	p.tmp69 = (p.tmp69 & (^(uint64(1) << uint64(63)))) | ((uint64(tmp326) & uint64(1)) << uint64(63))
	return true
}

func (p *ProtectedHeader) NonceCounter() uint64 {
	return uint64(((p.tmp69 >> uint64(0)) & uint64(9223372036854775807)))
}

func (p *ProtectedHeader) SetNonceCounter(tmp306 uint64) bool {
	p.tmp69 = (p.tmp69 & (^(uint64(9223372036854775807) << uint64(0)))) | ((uint64(tmp306) & uint64(9223372036854775807)) << uint64(0))
	return true
}

type ProtectedHeader struct {
	tmp69 uint64
}

func (p *ProtectedHeader) Write(tmp108 io.Writer) error {
	tmp251 := [8]uint8{}
	tmp251[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp251[0] = tmp251[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp251[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp251[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp251[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp251[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp251[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp251[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp251[7] = uint8((p.NonceCounter() & uint64(255)))
	if _, err := tmp108.Write(tmp251[:8]); err != nil {
		return err
	}
	return nil
}
func (s *ProtectedHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ProtectedHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) EncodeSlice(tmp108 []byte, tmp108Offset *int) error {
	tmp251 := []uint8{}
	if len(tmp108)-*tmp108Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"ProtectedHeader::NonceCounter\"")
	}
	tmp251 = tmp108[*tmp108Offset : *tmp108Offset+int(8)]
	tmp251[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp251[0] = tmp251[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp251[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp251[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp251[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp251[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp251[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp251[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp251[7] = uint8((p.NonceCounter() & uint64(255)))
	*tmp108Offset += int(8)
	return nil
}
func (s *ProtectedHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ProtectedHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) Append(tmp108 []byte) ([]byte, error) {
	tmp251 := [8]uint8{}
	tmp251[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp251[0] = tmp251[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp251[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp251[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp251[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp251[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp251[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp251[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp251[7] = uint8((p.NonceCounter() & uint64(255)))
	tmp108 = append(tmp108, tmp251[:8]...)
	return tmp108, nil
}
func (s *ProtectedHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *ProtectedHeader) Read(tmp8 io.Reader) error {
	tmp283 := [8]uint8{}
	if _, err := io.ReadFull(tmp8, tmp283[0:0+8]); err != nil {
		return err
	}
	tmp269 := uint8(0)
	tmp269 = uint8(((tmp283[0] & 128) >> uint8(7)))
	p.setRawPayload(tmp269)
	tmp266 := uint64(0)
	tmp266 = (((((((uint64((tmp283[0] & uint8(127))) << uint64(56)) | (uint64(tmp283[1]) << uint64(48))) | (uint64(tmp283[2]) << uint64(40))) | (uint64(tmp283[3]) << uint64(32))) | (uint64(tmp283[4]) << uint64(24))) | (uint64(tmp283[5]) << uint64(16))) | (uint64(tmp283[6]) << uint64(8))) | uint64(tmp283[7])
	p.SetNonceCounter(tmp266)
	return nil
}
func (s *ProtectedHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ProtectedHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *ProtectedHeader) DecodeSlice(tmp8 []byte, tmp8Offset *int) error {
	tmp283 := []uint8{}
	if len(tmp8)-*tmp8Offset < 8 {
		return errors.New("not enough data to read for field \"tmp15\"")
	}
	tmp283 = tmp8[*tmp8Offset : *tmp8Offset+8]
	*tmp8Offset += int(8)
	tmp269 := uint8(0)
	tmp269 = uint8(((tmp283[0] & 128) >> uint8(7)))
	p.setRawPayload(tmp269)
	tmp266 := uint64(0)
	tmp266 = (((((((uint64((tmp283[0] & uint8(127))) << uint64(56)) | (uint64(tmp283[1]) << uint64(48))) | (uint64(tmp283[2]) << uint64(40))) | (uint64(tmp283[3]) << uint64(32))) | (uint64(tmp283[4]) << uint64(24))) | (uint64(tmp283[5]) << uint64(16))) | (uint64(tmp283[6]) << uint64(8))) | uint64(tmp283[7])
	p.SetNonceCounter(tmp266)
	return nil
}
func (s *ProtectedHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ProtectedHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type EncryptedData struct {
	NonceCounter uint64
	Data         []uint8
}

func (e *EncryptedData) Write(tmp133 io.Writer) error {
	tmp193 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp193[:], uint64(e.NonceCounter))
	if _, err := tmp133.Write(tmp193[:8]); err != nil {
		return err
	}
	if _, err := tmp133.Write(e.Data); err != nil {
		return err
	}
	return nil
}
func (s *EncryptedData) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *EncryptedData) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) EncodeSlice(tmp133 []byte, tmp133Offset *int) error {
	tmp193 := []uint8{}
	if len(tmp133)-*tmp133Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"EncryptedData::NonceCounter\"")
	}
	tmp193 = tmp133[*tmp133Offset : *tmp133Offset+int(8)]
	binary.BigEndian.PutUint64(tmp193[:], uint64(e.NonceCounter))
	*tmp133Offset += int(8)
	if len(tmp133)-*tmp133Offset < int(0+len(e.Data)) {
		return errors.New("not enough space to write for field \"EncryptedData::Data\"")
	}
	copy(tmp133[*tmp133Offset:*tmp133Offset+int(len(e.Data))], e.Data)
	*tmp133Offset += int(len(e.Data))
	return nil
}
func (s *EncryptedData) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *EncryptedData) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) Append(tmp133 []byte) ([]byte, error) {
	tmp193 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp193[:], uint64(e.NonceCounter))
	tmp133 = append(tmp133, tmp193[:8]...)
	tmp133 = append(tmp133, e.Data...)
	return tmp133, nil
}
func (s *EncryptedData) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (e *EncryptedData) Read(tmp106 io.Reader) error {
	tmp225 := [8]uint8{}
	if _, err := io.ReadFull(tmp106, tmp225[0:0+8]); err != nil {
		return err
	}
	e.NonceCounter = binary.BigEndian.Uint64(tmp225[:])
	{
		var readErr error
		e.Data, readErr = io.ReadAll(tmp106)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *EncryptedData) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *EncryptedData) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (e *EncryptedData) DecodeSlice(tmp106 []byte, tmp106Offset *int) error {
	tmp225 := []uint8{}
	if len(tmp106)-*tmp106Offset < 8 {
		return errors.New("not enough data to read for field \"EncryptedData::NonceCounter\"")
	}
	tmp225 = tmp106[*tmp106Offset : *tmp106Offset+8]
	*tmp106Offset += int(8)
	e.NonceCounter = binary.BigEndian.Uint64(tmp225[:])
	e.Data = tmp106[*tmp106Offset:]
	return nil
}
func (s *EncryptedData) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *EncryptedData) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Packet struct {
	Header PacketHeader
	Data   []uint8
}

func (p *Packet) SetData(tmp230 []uint8) bool {
	if len(tmp230) > int(65535) {
		return false
	}
	p.Header.Len = uint16(len(tmp230))
	p.Data = tmp230
	return true
}

func (p *Packet) Write(tmp129 io.Writer) error {
	tmp234 := p.Header.Write(tmp129)
	if tmp234 != nil {
		return tmp234
	}
	if len(p.Data) != int(p.Header.Len) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	if _, err := tmp129.Write(p.Data); err != nil {
		return err
	}
	return nil
}
func (s *Packet) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Packet) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) EncodeSlice(tmp129 []byte, tmp129Offset *int) error {
	tmp234 := p.Header.EncodeSlice(tmp129, tmp129Offset)
	if tmp234 != nil {
		return tmp234
	}
	if len(p.Data) != int(p.Header.Len) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	if len(tmp129)-*tmp129Offset < int(0+p.Header.Len) {
		return errors.New("not enough space to write for field \"Packet::Data\"")
	}
	copy(tmp129[*tmp129Offset:*tmp129Offset+int(p.Header.Len)], p.Data)
	*tmp129Offset += int(p.Header.Len)
	return nil
}
func (s *Packet) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Packet) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) Append(tmp129 []byte) ([]byte, error) {
	var tmp234 error
	tmp129, tmp234 = p.Header.Append(tmp129)

	if tmp234 != nil {
		return nil, tmp234
	}
	if len(p.Data) != int(p.Header.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	tmp129 = append(tmp129, p.Data...)
	return tmp129, nil
}
func (s *Packet) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Packet) Read(tmp131 io.Reader) error {
	tmp237 := p.Header.Read(tmp131)
	if tmp237 != nil {
		return tmp237
	}
	if seeker, ok := tmp131.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(p.Header.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.Header.Len)))
		}
		p.Data = make([]byte, int(p.Header.Len))
		if _, err := io.ReadFull(tmp131, p.Data[0:0+int(p.Header.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_423 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_423, tmp131, int64(int(p.Header.Len))); err != nil {
			return err
		}
		p.Data = io_temp_423.Bytes()
	}
	return nil
}
func (s *Packet) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Packet) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Packet) DecodeSlice(tmp131 []byte, tmp131Offset *int) error {
	tmp237 := p.Header.DecodeSlice(tmp131, tmp131Offset)
	if tmp237 != nil {
		return tmp237
	}
	if len(tmp131)-*tmp131Offset < int(p.Header.Len) {
		return errors.New("not enough data to read for field \"Packet::Data\"")
	}
	p.Data = tmp131[*tmp131Offset : *tmp131Offset+int(p.Header.Len)]
	*tmp131Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Packet) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ApplicationPayloadKind uint8

const (
	ApplicationPayloadKind_Control            ApplicationPayloadKind = 0
	ApplicationPayloadKind_StreamData         ApplicationPayloadKind = 1
	ApplicationPayloadKind_StreamCancel       ApplicationPayloadKind = 2
	ApplicationPayloadKind_StreamAck          ApplicationPayloadKind = 3
	ApplicationPayloadKind_StreamWindowUpdate ApplicationPayloadKind = 4
)

func (e ApplicationPayloadKind) String() string {
	switch e {
	case ApplicationPayloadKind_Control:
		return "Control"
	case ApplicationPayloadKind_StreamData:
		return "StreamData"
	case ApplicationPayloadKind_StreamCancel:
		return "StreamCancel"
	case ApplicationPayloadKind_StreamAck:
		return "StreamAck"
	case ApplicationPayloadKind_StreamWindowUpdate:
		return "StreamWindowUpdate"
	default:
		return fmt.Sprintf("ApplicationPayloadKind(%d)", e)
	}
}
