#!/usr/bin/env bash
# Regenerate Go code from .bgn schemas via the brgen local api server.
#
# - First run downloads and installs the brgen server-kit into a user
#   cache (~/.cache/brgen-kit), about 20 MB tarball + 330 npm packages.
# - Subsequent runs reuse the cache; only the api server start (~5 s)
#   and the codegen round-trip (~1 s) are paid per invocation.
# - The server runs on port 8181 by default (override BRGEN_PORT env).
#
# Usage:
#   scripts/protoregen.sh                # regenerate the default set
#   scripts/protoregen.sh path/to/x.bgn  # regenerate a single file (out path inferred)
#   scripts/protoregen.sh --all          # regenerate every .bgn under the repo
#
# Output language is fixed to go3 (= ebm2go, matching the existing
# `// Code generated by ebm2go ...` headers).
set -euo pipefail

BRGEN_CACHE="${BRGEN_CACHE:-${HOME}/.cache/brgen-kit}"
BRGEN_PORT="${BRGEN_PORT:-8181}"
BRGEN_URL="${BRGEN_URL:-https://on-keyday.github.io/brgen/server-kit.tar.gz}"
BRGEN_LANG="${BRGEN_LANG:-go3}"

# Default set: only runner/protocol is touched frequently. Other .bgn
# files in the tree (objproto/packet, pubsub/protocol, trsf/wire,
# exec/frame) are stable; pass them explicitly or use --all.
DEFAULT_BGNS=(
    "runner/protocol/message.bgn"
)

# --- arg parsing ----------------------------------------------------------

ARGS=("$@")
TARGETS=()
if [ ${#ARGS[@]} -eq 0 ]; then
    TARGETS=("${DEFAULT_BGNS[@]}")
elif [ "${ARGS[0]}" = "--all" ]; then
    while IFS= read -r f; do
        TARGETS+=("$f")
    done < <(find . -name '*.bgn' \
        -not -path '*/node_modules/*' \
        -not -path '*/.harness-worktrees/*' \
        -not -path '*/.cache/*' \
        | sed 's|^\./||')
else
    TARGETS=("${ARGS[@]}")
fi

if [ ${#TARGETS[@]} -eq 0 ]; then
    echo "no .bgn targets to regenerate" >&2
    exit 1
fi

# --- setup cache ----------------------------------------------------------

if [ ! -f "${BRGEN_CACHE}/.installed" ]; then
    echo "==> Setting up brgen server-kit cache at ${BRGEN_CACHE}..."
    mkdir -p "${BRGEN_CACHE}"
    curl -fsSL "${BRGEN_URL}" | tar xz -C "${BRGEN_CACHE}"
    (cd "${BRGEN_CACHE}/web/dev" && npm install)
    touch "${BRGEN_CACHE}/.installed"
fi

# --- start api server -----------------------------------------------------

echo "==> Starting brgen api server on port ${BRGEN_PORT}..."
LOG_FILE="$(mktemp)"
(cd "${BRGEN_CACHE}/web/dev" && PORT="${BRGEN_PORT}" npm run serve >"${LOG_FILE}" 2>&1) &
SERVER_PID=$!

cleanup() {
    kill "${SERVER_PID}" 2>/dev/null || true
    wait "${SERVER_PID}" 2>/dev/null || true
    rm -f "${LOG_FILE}"
}
trap cleanup EXIT

# Wait for /api/languages to respond (server is ready when ebmgen worker is up).
for _ in $(seq 1 30); do
    if curl -fsS "http://localhost:${BRGEN_PORT}/api/languages" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done
if ! curl -fsS "http://localhost:${BRGEN_PORT}/api/languages" >/dev/null 2>&1; then
    echo "brgen api server did not become ready within 30 s" >&2
    cat "${LOG_FILE}" >&2 || true
    exit 1
fi

# --- regen each target ----------------------------------------------------

REQ_FILE="$(mktemp)"
RESP_FILE="$(mktemp)"
trap 'cleanup; rm -f "${REQ_FILE}" "${RESP_FILE}"' EXIT

for bgn in "${TARGETS[@]}"; do
    if [ ! -f "${bgn}" ]; then
        echo "no such .bgn: ${bgn}" >&2
        exit 1
    fi
    out="${bgn%.bgn}.go"
    echo "==> Regenerating ${out} (lang=${BRGEN_LANG})..."
    python3 - "${bgn}" "${BRGEN_LANG}" >"${REQ_FILE}" <<'PY'
import json, sys
src = open(sys.argv[1]).read()
print(json.dumps({"source": src, "lang": sys.argv[2]}))
PY
    curl -fsS -X POST \
        -H "Content-Type: application/json" \
        --data @"${REQ_FILE}" \
        "http://localhost:${BRGEN_PORT}/api/generate" \
        -o "${RESP_FILE}"
    python3 - "${RESP_FILE}" "${out}" <<'PY'
import json, sys
r = json.load(open(sys.argv[1]))
if r.get("isError"):
    print("GENERATION ERROR:")
    print(r.get("code", "")[:4000])
    raise SystemExit(1)
open(sys.argv[2], "w").write(r["code"])
PY
    gofmt -w "${out}"
done

echo "==> Done. Regenerated: ${TARGETS[*]}"
